README.md
1. Added link to requirements document.
2. Divided installation into steps
3. Refactored demo code to put @op decorator later in the script.
=> Revised main readme to improve clarity

README.md
This should have been merged in my previous PR but somehow I failed to merge my edits correctly using the Github web editor.
=> Fixing inconsistency in punctuation

README.md
* Adds the Aqueduct logo
* Adds some badges
* Cleans up some wording
=> Spruces up README.md based on feedback

.github/workflows/integration-tests.yml
1) 3.10 doesn't work
2) Comment trigger job doesn't work when its a push-trigger, so we gate it off to only issue_comment triggers.
=> Fix broken integration tests

src/ui/common/package-lock.json
Bumps ui package-lock.json 0.0.4 -> 0.0.5
=> Bumps ui package-lock.json 0.0.4 -> 0.0.5

README.md
Link to our community slack channel
=> Adding Slack Badge

.github/workflows/integration-tests.yml, src/python/aqueduct_executor/operators/function_executor/extract_function.py
I confirmed the tests passed via the following github actions: https://github.com/aqueducthq/aqueduct/actions/runs/2457196019
=> Fix 3.7 compatibility and enable integration test

integration_tests/sdk/checks_test.py, integration_tests/sdk/conftest.py, integration_tests/sdk/flow_test.py, integration_tests/sdk/local_test.py, integration_tests/sdk/metrics_test.py, integration_tests/sdk/naming_test.py, integration_tests/sdk/param_test.py, integration_tests/sdk/sql_integration_test.py, integration_tests/sdk/table_artifact_test.py, integration_tests/sdk/to_df_test.py, integration_tests/sdk/utils.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/metric_artifact.py, sdk/aqueduct/tests/metric_test.py, sdk/aqueduct/utils.py, sdk/examples/run_notebook.py, sdk/setup.py, src/python/aqueduct_executor/operators/connectors/tabular/connector.py, src/python/aqueduct_executor/operators/connectors/tabular/s3.py, src/python/aqueduct_executor/operators/connectors/tabular/snowflake.py, src/python/aqueduct_executor/operators/connectors/tabular/spec.py, src/python/bin/aqueduct, src/python/setup.py
`sp_client` is a remnant of what once was...
Also ran `autoflake` over all the python to get rid of all unused python imports.
=> Replace mentions of `sp_client` with `client`

README.md
The previous logo looked funny in dark mode.
=> Adds logo with colored background to README

.github/workflows/integration-tests.yml, src/python/setup.py
Also removed a TODO i forgot to strip
=> Fix bug in setup.py

CONTRIBUTING.md
I still need to put together the issue and PR templates, but here is an initial draft of the contribution guide. Please comment on improvements we can make.
=> Draft OSS contribution guide

src/golang/cmd/server/main.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/cmd/server/server/server.go, src/python/bin/aqueduct
=> Eng 1180 automatically find the next available port for the server

.github/workflows/unit-tests-backend.yml, .github/workflows/unit-tests-sdk.yml, sdk/aqueduct/tests/decorator_test.py
For both the backend and the sdk.
=> Port Unit Test Github Actions over

integration_tests/sdk/param_test.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/check_artifact.py, sdk/aqueduct/dag.py, sdk/aqueduct/generic_artifact.py, sdk/aqueduct/metric_artifact.py, sdk/aqueduct/operators.py, sdk/aqueduct/param_artifact.py, sdk/aqueduct/table_artifact.py
This is a strict port of https://github.com/aqueducthq/enterprise/pull/514. Turns out it wasn't included when we ported everything over to OSS.
=> Allow users to realize artifacts with custom parameters

README.md
=> Improves README code example based on feedback

integration_tests/sdk/param_test.py, sdk/aqueduct/api_client.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/dag.py, src/golang/cmd/executor/executor/workflow.go, src/golang/cmd/server/handler/edit_workflow.go, src/golang/cmd/server/handler/refresh_workflow.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/request/parameters.go, src/golang/cmd/server/routes/headers.go, src/golang/lib/collections/workflow_dag/workflow_dag.go, src/golang/lib/job/spec.go
Ported over from my demo a few weeks ago. Unfortunately, there's not a great way to test that we're actually triggering with the new parameters, until we build the ability to fetch and inspect flow versions.
However, I was able to verify that this works from the UI :)
=> Add ability to trigger existing flows with different parameters

sdk/aqueduct/utils.py
Checked in the following environments:
- interactive interpreter
- Python script
- Jupyter notebook in browser
Here are the cases checked:
Case 1
```
import aqueduct
from aqueduct import op
client = aqueduct.Client("NH264SBCGTV91RXDJOYLKQ78M0PAZIEW", "localhost:8080")
db = client.integration("aqueduct_demo")
sql = db.sql("SELECT * FROM hotel_reviews")
@op()
def foo(df):
return df
foo(sql).get()
```
Returns:
```
hotel_name review_date reviewer_nationality                                             review
0                          H10 Itaca  2017-08-03           Australia    Damaged bathroom shower screen sealant and ti...
1            De Vere Devonport House  2016-03-28      United Kingdom   No Negative The location and the hotel was ver...
2                Ramada Plaza Milano …
```
=> Eng 1111 fix bug when using oss sdk in python

src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/tsconfig.json
Resolves:
https://linear.app/aqueducthq/issue/ENG-1248/bug-npm-run-start-fails-on-m1-mac
=> Fix build error for parcel/css on m1 mac.

README.md
The previous metric in the example code was not computed correctly.
=> Fixing metric in example code

integration_tests/sdk/table_artifact_test.py, sdk/aqueduct/table_artifact.py, sdk/requirements/python-3-10.txt, sdk/requirements/python-3-7.txt, sdk/requirements/python-3-8.txt, sdk/requirements/python-3-9.txt
We have a new method on tables that allows us to take a expectation string and arguments and creates a check that returns a true/false based on the validation of the expectation.
=> Add ability to create checks on table artifacts from Expectations

src/golang/cmd/migrator/migrator/create.go, src/python/aqueduct_executor/operators/connectors/tabular/bigquery.py, src/python/aqueduct_executor/operators/connectors/tests/README.md, src/python/aqueduct_executor/operators/connectors/tests/conf.py, src/python/aqueduct_executor/operators/connectors/tests/conftest.py, src/python/aqueduct_executor/operators/connectors/tests/requirements.txt, src/python/aqueduct_executor/operators/connectors/tests/test_bigquery.py, src/python/bin/aqueduct
* Update connector to use `google-cloud-big-query` (this is because `pandas_gbq` cannot perform the functionality desired in the `discover` function)
* Update tests to work with our current project structure
* Add test for the `discover` function
=> Eng 708 investigate how to list tables for

src/ui/common/src/components/notifications/NotificationListItem.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/version_selector.tsx
- implement logics to append workflowDagResultId to workflow id page so user would not see a workflow id page without knowing the exact dagResultId being rendered
- https://www.loom.com/share/a4fc483d4d254d4d88f39f06e1b0ad60
=> Eng-1267-append-dag-result-id-to-workflow-id-page0-url

.github/pull_request_template.md, src/python/bin/aqueduct
I noticed that the PR template header will actually appear as part of the template, and we don't need that, so this PR removes it.
N/A
=> Remove the unneeded header section in the PR template

src/ui/common/src/components/layouts/data_previewer.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/nodes/JsonArtifactNode.tsx, src/ui/common/src/components/workflows/nodes/nodeTypes.tsx, src/ui/common/src/reducers/nodeSelection.ts, src/ui/common/src/utils/artifacts.ts, src/ui/common/src/utils/operators.ts, src/ui/common/src/utils/reactflow.ts, src/ui/common/src/utils/sidesheets.tsx
Shows the parameter artifact in the reactflow dag, but not the parameter operator. I picked a Pencil icon because parameters are configurable, but open to other suggestions :P
A parameter named "dictionary" looks like this:
=> Show parameters correctly on the UI

src/ui/README.md
Updates README for building and making changes to ui codebase.
https://linear.app/aqueducthq/issue/ENG-1280/cleanup-outdated-ui-documentation-in-our-repo
https://linear.app/aqueducthq/issue/ENG-1268/update-ui-readme-file
=> Update README for ui development.

src/ui/common/src/components/pages/integration/id/index.tsx
ENG-1271 Show user a message saying that we do not support previewing base data for an S3 integration
- Not a new feature.
- I don't think we have integration tests for UI.
=> ENG-1271 Show user a message saying that we do not support previewing base data for an S3 integration

.github/workflows/integration-tests.yml
- [Y ] I have performed a self-review of my code.
- [ NA] If this is a new feature, I have added unit tests and integration tests.
- [ Y] I have manually run the integration tests and they are passing.
- [NA ] All features on the UI continue to work correctly.
=> Add executor files to integration tests server logs

scripts/install_local.py, scripts/run_linters.py, sdk/aqueduct/table_artifact.py, sdk/requirements/python-3-10.txt, sdk/requirements/python-3-7.txt, sdk/requirements/python-3-8.txt, sdk/requirements/python-3-9.txt
This PR adds a Python script that the developers can use to run all linters. We should be running this prior to making future PRs so that the code is cleaned before the reviewers review them. The exact usage of the script is described in the script.
This PR also does a cleanup of an unnecessary module import of `ruamel` and includes `ruamel.yaml` to our SDK's `requirements.txt`s.
=> Implement a script to run all linters

.github/workflows/pre-merge-ci.yml
Updates the branch of the reused workflow to main.
=> Changes branch of reused workflow to main

CONTRIBUTING.md
Edit the contribution guide to reflect new integration testing step.
[1299](https://linear.app/aqueducthq/issue/ENG-1299/update-contributingmd-to-reflect-integration-test-step-in-dev-workflow)
=> Adds integration test step to dev workflow in contribution guide

.github/workflows/pre-merge-ci.yml
Follow up to #173 
- [n/a] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [n/a] I have performed a self-review of my code.
- [n/a] I have manually run the integration tests and they are passing.
=> Follow up to Eng 1305

src/ui/common/src/components/layouts/menu-sidebar-styles.module.css
fixed the "report issue" button weird margin
Linear: https://linear.app/aqueducthq/team/ENG/active
Final Look:
=> fixed "report issue" button weird margin

.github/workflows/pre-merge-ci.yml
This fixes bug in the pre-merge-ci config, changing the branch of the reused workflow to main.
=> Fixes bug in the pre-merge-ci config

.github/workflows/periodic-integration-tests.yml
Adds a workflow for periodic integration tests that runs across params of [python versions, concurrency]
https://linear.app/aqueducthq/issue/ENG-1300/enable-periodic-full-integration-tests-on-open-source-repo
=> Adds periodic integration tests

.github/workflows/periodic-integration-tests.yml
Updates periodic integration test with new install-local.py invocation
=> Updates periodic integration test

examples/parameterization/Using Workflow Parameters.ipynb
None, this is just a quick doc fix.
=> Fix link in parameterization demo notebook

README.md
A user ran into two silly bugs with this set up script
=> Fix bugs in README script from set up call

CHANGELOG.md
Updating the changelog for the v0.0.4 release.
=> Updates changelog for v0.0.4 release

examples/churn_prediction/Build and Deploy Churn Ensemble.ipynb
Updates the churn example notebook to use port 8080 instead of 3000.
- [n/a] I have run the integration tests locally and they are passing.
- [n/a] Added one of the following CI labels:
=> Updates churn example to use correct port for UI

src/python/aqueduct_executor/operators/connectors/tabular/postgres.py, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/postgresDialog.tsx, src/ui/common/src/utils/integrations.ts
`postgresql://{username}@{host}:{port}/{database}` if no password else `postgresql://{username}:{password}@{host}:{port}/{database}`
Details about connection uris schema: [connection uris](https://www.prisma.io/dataguide/postgresql/short-guides/connection-uris)
Was able to create an integration with no password. 
Output:
```
INFO[0035] Job discover-operator-b74341d0-cfb7-4463-9fe8-6fdafcef5436 Stdout:
Job Spec: 
{
"type": "discover",
"name": "discover-operator-b74341d0-cfb7-4463-9fe8-6fdafcef5436",
"storage_config": {
"type": "file",
"file_config": {
"directory": "/Users/eunice/.aqueduct/server/storage"
}
},
"metadata_path": "list-tables-metadata-c8c0c05c-fe62-11ec-8da9-16d00539493d",
"connector_name": "Postgres",
"connector_config": {
"conf": {
"database": "test",
"host": "3.142.105.48", …
```
=> Make password optional for the Postgres integration

README.md
=> Update README with latest tagline

CHANGELOG.md, sdk/setup.py, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package.json
=> Bump release version to 0.0.5

README.md
=> Fixing embarrassing bug

src/golang/.golangci.yml
See issue below.
ENG-1373
- [ x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [ N/A] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ N/A] If this is a new feature, I have added unit tests and integration tests.
- [ N/A] I have run the integration tests locally and they are passing.
- [ N/A] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [N/A ] All features on the UI continue to work correctly.
- [ x] Added one of the following CI labels:
- `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY …
=> Reenable gci in golangci linter

sdk/aqueduct/table_artifact.py
=> Fix bug where parameters argument to head() was unused.

src/ui/app/.parcelrc, src/ui/app/package-lock.json, src/ui/app/package.json
Reverts aqueducthq/aqueduct#219
=> Revert "Rmeove unnecessary files from parcel bundle"

src/ui/common/src/utils/integrations.ts
Disables Airflow integration connections until the project is fully supported.
=> Disables connecting to Airflow from UI

CHANGELOG.md, sdk/setup.py, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package.json
=> Bump version number and update changelog for release v0.0.6

sdk/aqueduct/integrations/s3_integration.py
=> Update SDK's S3 integration api documentation

README.md
The README previously didn't have an easy link to the docs, so this adds that.
=> Add docs and Slack links to top of README

src/golang/lib/storage/s3.go
This PR checks whether or not the S3 key exists, and if it does not, it returns an `ErrObjDoesNotExist` just like the File storage implementation.
ENG 1368
I manually tested this out by executing a preview operation with S3 as the storage. Previously, this was failing because the orchestrator logic was broken as the S3 storage implementation always returned that the key existed, even when it did not.
=> Returns ObjDoesNotExist error for S3 storage implementation

integration_tests/backend/test_backend.py, integration_tests/sdk/conftest.py, integration_tests/sdk/no_input_test.py, sdk/aqueduct/api_client.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/check_artifact.py, sdk/aqueduct/dag.py, sdk/aqueduct/decorator.py, sdk/aqueduct/flow.py, sdk/aqueduct/flow_run.py, sdk/aqueduct/github.py, sdk/aqueduct/integrations/google_sheets_integration.py, sdk/aqueduct/integrations/s3_integration.py, sdk/aqueduct/integrations/salesforce_integration.py, sdk/aqueduct/integrations/sql_integration.py, sdk/aqueduct/metric_artifact.py, sdk/aqueduct/param_artifact.py, sdk/aqueduct/table_artifact.py, sdk/aqueduct/tests/metric_test.py, sdk/aqueduct/tests/utils.py, sdk/aqueduct/utils.py, src/golang/lib/workflow/operator/function.go
One way to enable this is to make module-level variables for the `dag` and `api_client` objects. The following change seems to work.
=> Support operator with no input

CHANGELOG.md, README.md, sdk/setup.py, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package.json
=> Bump version number and changelog for release 0.0.7

src/ui/README.md
Update UI documentation to include information on release process for @aqueducthq/common and up to date info on development workflow
N/A
=> Update UI Documentation

examples/sentiment_analysis/Sentiment Model.ipynb
As discussed previously, this PR adds a warning about large models to the sentiment workflow, so people running in resource-constrained environments will avoid it. 
ENG-1462
=> Adds warning about large models to sentiment workflow

src/python/aqueduct_executor/operators/connectors/tabular/execute.py
=> Fixed bug where connection error wasn't properly surfaced to the UI

src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json, src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/utils/integrations.ts
This PR adds some styling improvements to the grid on the Integrations List Page.
Loom demo can be found here: https://www.loom.com/share/5b632beb968a4ebbb9de721023e88218
https://linear.app/aqueducthq/issue/ENG-1422/integrations-list-page-improvements
=> Eng 1422 Integrations List Page Improvements

src/ui/README.md
=> Update UI README for local dev with React virtualized

src/ui/common/package-lock.json, src/ui/common/src/components/layouts/menuSidebar.tsx
Our logo has been missing from our menu sidebar for quite a while. This PR adds the logo to the MenuSidebar component.
Resolves: https://linear.app/aqueducthq/issue/ENG-1225/add-logo-to-menu-sidebar-on-the-ui
Screenshot:
=> Adds logo to the menu sidebar

README.md
Simplifying and clarifying the README based on user feedback.
N/A
=> Update README based on user feedback

README.md
Tiny fix following on from yesterday's README update.
N/A
=> Updates logo to use properly colored asset

sdk/aqueduct/api_client.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/dag.py, sdk/aqueduct/enums.py, sdk/aqueduct/flow.py, sdk/aqueduct/integrations/airflow_integration.py, sdk/aqueduct/responses.py
This PR allows users to publish an Airflow workflow from the SDK. We haven't yet enabled connecting an Airflow integration yet, so users will not be immediately using the changes in this PR.
ENG 879
=> Allows for publishing Airflow workflows from the SDK

src/golang/cmd/server/handler/get_artifact_result.go
To unblock Andre. He needs a way of fetching artifact names to display.
ENG-1547
=> Add artifact name to response in get_artifact_result

sdk/aqueduct/aqueduct_client.py
And add the logic to only check when the aqueduct address is not localhost.
=> Update warning message when checking pip freeze requirements to be more informative

examples/run_notebook.py, integration_tests/sdk/requirements_tests/requirements_test.py
=> Fix minor Python linting issues

src/golang/cmd/server/handler/list_integration_objects.go
Remove debug print statements.
=> Remove prints

src/golang/lib/engine/utils.go, src/golang/lib/engine/utils_test.go
Adds function to extract AWS credentials from file
=> Adds function to extract AWS credentials from file

src/golang/cmd/migrator/versions/000016_add_artifact_type_column_to_artifact/main.go, src/golang/cmd/migrator/versions/000016_add_artifact_type_column_to_artifact/utils.go, src/golang/lib/collections/artifact/types.go
=> Fix data migration script to account for artifact result being missing due to failure

src/golang/cmd/migrator/versions/000016_add_artifact_type_column_to_artifact/utils.go
=> Fix a minor logging bug during data migration

src/ui/common/package-lock.json
Package-lock.json updates for common.
=> Updates package-lock.json for aqueducthq/common.

scripts/generate_docs.sh
=> Update our SDK doc generation script to be up-to-date with the new folder structure

CHANGELOG.md, sdk/setup.py, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json
=> Ready for v0.0.11

src/ui/common/src/utils/integrations.ts
=> Activate k8s integration on UI

sdk/aqueduct/integrations/integration.py, src/python/aqueduct_executor/operators/utils/utils.py
Add clarifying comments in Python code to changes done in part of the Integration Management project.
=> Clarifying comments in Python code

src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/cards/gcsCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/gcsDialog.tsx, src/ui/common/src/utils/integrations.ts
This PR allows users to connect a GCS integration.
ENG 1597
DEMO: https://www.loom.com/share/b9a5e16a74bf41cf85d6d0e7d98bb48d
=> Allows users to connect google cloud storage integration from UI

src/golang/cmd/server/queries/postgres.go, src/golang/cmd/server/queries/sqlite.go, src/golang/cmd/server/queries/standard.go, src/golang/lib/collections/artifact/standard.go, src/golang/lib/collections/operator/postgres.go, src/golang/lib/collections/operator/sqlite.go, src/golang/lib/collections/operator/standard.go, src/golang/lib/collections/utils/utils.go, src/golang/lib/collections/workflow/postgres.go, src/golang/lib/collections/workflow/sqlite.go, src/golang/lib/collections/workflow/standard.go, src/golang/lib/collections/workflow_dag/standard.go, src/golang/lib/collections/workflow_dag_result/sqlite.go, src/golang/lib/collections/workflow_dag_result/standard.go
Commented on all complex SQL queries in `src/golang/lib/collections` and `src/golang/cmd/server/queries` to make it easier to understand them without reading too closely.
Eng 1595
=> Eng 1595 write dev documentation for complex sql

sdk/aqueduct/responses.py, src/golang/cmd/server/handler/list_workflow_objects.go, src/golang/lib/collections/operator/postgres.go, src/golang/lib/collections/operator/sqlite.go, src/golang/lib/collections/operator/standard.go, src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/utils/workflows.tsx
Reverts aqueducthq/aqueduct#410
=> Revert "[BE/3] ENG-1509 Add flag to Update Mode indicating which is currently used"

sdk/aqueduct/artifacts/bool_artifact.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/artifacts/numeric_artifact.py, sdk/aqueduct/artifacts/table_artifact.py
I noticed a couple outdated things in the docstrings for these classes.
=> Tweaks the artifact class docstrings to be more up to date

src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile
This PR adds a Dockerfile for Athena to execute on the k8s engine.
ENG 1632
=> Adds AWS Athena Dockerfile

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/golang/lib/job/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Ready for release 0.0.13

CHANGELOG.md
=> Minor edit to changelog

CHANGELOG.md
=> Fix Changelog's indentation

src/golang/lib/workflow/artifact/response.go, src/golang/lib/workflow/dag/response.go, src/golang/lib/workflow/operator/response.go
This PR improves `getWorkflowDagResult` by adding `From` and `To` fields to artifacts. We also fixed variable names so that they start with lower case. UI: #439 
ENG-1572
Tested response in postman
=> Add from and to for artf response

src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/sqliteDialog.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/utils/integrations.ts
There was previously no SQLite dialog, so we weren't actually able to connect to SQLite. This PR fixes that. 
[Demo video](https://www.loom.com/share/d88a38640b3d48c397f76286097b087d)
ENG-1094
=> ENG-1094: Adds ability to connect to new SQLite DB

.gitignore, CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/golang/lib/job/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Ready for release 0.0.14

src/golang/cmd/server/handler/refresh_workflow.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/airflow/client.go, src/golang/lib/airflow/trigger.go
This PR adds support for triggering a new workflow run for a workflow that is using an Airflow engine.
ENG 1487
Tests: In Progress
=> Implements triggering an Airflow workflow

examples/churn_prediction/Build and Deploy Churn Ensemble.ipynb, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/StatusBar.tsx, src/ui/common/src/components/workflows/version_selector.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx
This PR loads the most recent workflow in the workflow details page after the user triggers a workflow from the UI.
This PR contains work that I did while trying to resolve ENG-1639.
It's adjacent, yet still doesn't solve the bug in 1639.
https://www.loom.com/share/92c68f4c437d48b7bed39d13d037d8e5
ENG-1639
=> ENG-1639 Switch to Newest workflow on Run

sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/responses.py, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/server/handlers.go
This PR allows users to update the metadata and DAG structure of a workflow running on Airflow.
This requires the user to copy over the updated Airflow DAG file to their server.
ENG 1423
TEST: https://www.loom.com/share/dacedfcd9a864003a158a45096f1d3a2
=> Adds support for updating Airflow workflows

src/golang/cmd/server/handler/register_airflow_workflow.go
This PR fixes a compilation bug.
=> Fixes register airflow compilation bug

src/dockerfiles/Makefile, src/ui/common/src/utils/integrations.ts
=> Activates lambda integration + adds build-connectors to make command

src/ui/common/src/utils/integrations.ts
This PR activates the Airflow integration.
=> Activates Airflow integration

CHANGELOG.md
=> Minor update to CHANGELOG

sdk/aqueduct/aqueduct_client.py
This PR adds documentation for publish_flow() to have more information on publishing workflow using Lambda/K8s Engine
https://linear.app/aqueducthq/issue/ENG-1704/add-documentation-for-connecting-engine-integration
=> Eng-1702 Update SDK Documentation on Using Lambda/K8S Engine

scripts/install_local.py
I'm just too tired to type 'gobinary' every time :)
```
ubuntu@ip-172-31-45-190:~/aqueduct$ python3 scripts/install_local.py -h
usage: install_local.py [-h] [-u] [-g] [-s] [-e]
optional arguments:
-h, --help      show this help message and exit
-u, --ui        Whether to build and replace UI files.
-g, --gobinary  Whether to build and replace Golang binaries.
-s, --sdk       Whether to build and replace the Python SDK.
-e, --executor  Whether to build and replace the Python executor.
```
=> Simplify install_local scripts

.github/pull_request_template.md
Adding a section to PR template for showing off cool work we've done 😄 
=> Adds Loom demo section to PR template

src/ui/common/src/components/layouts/default.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx
Fix for settings gear not showing properly and the workflow details page not being bounded.
https://linear.app/aqueducthq/issue/ENG-1722/0015-fix-settings-icon-not-appearing-in-workflow-details-page
https://www.loom.com/share/f8af74b142f648a58f467d63f3aade8a
=> ENG-1722: Settings Gear Fix

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/ReactFlowCanvas.tsx, src/ui/common/src/components/workflows/nodes/CheckOperatorNode.tsx, src/ui/common/src/components/workflows/nodes/MetricOperatorNode.tsx
This PR fixes various bugs related to workflow details page spacing and expanding and contracting the page. 
https://www.loom.com/share/4390cee5f1d54cf3bbbea396b6241aaf
=> UI Redesign Status Bar Bug Fixes

CHANGELOG.md, scripts/generate_docs.sh, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/job/constants.go, src/golang/lib/lambda/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Ready for release 0.0.16

examples/parameterization/Using Parameters.ipynb
Keeps the notebook in sync with the documentation: https://github.com/aqueducthq/gitbook/pull/22
ENG-1643
=> Update the parameter example notebook 

.github/workflows/run-notebooks.yml
Fixes https://github.com/aqueducthq/aqueduct/actions/runs/3145946408/jobs/5113834096
=> Fixes bug in our notebooks CI

src/golang/cmd/server/handler/get_server_version.go, src/golang/cmd/server/routes/routes.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/constants.go, src/golang/lib/constants/constants.go, src/golang/lib/job/constants.go, src/golang/lib/job/k8s.go, src/golang/lib/lambda/constants.go, src/golang/lib/lambda/utils.go
=> Implement a server endpoint that returns its version number

src/ui/app/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/index.tsx
This PR renames the Function Details Page to Operator Details Page.
ENG-1769
=> ENG-1769 Rename Function Details to Operator Details

src/dockerfiles/Makefile, src/dockerfiles/aqueduct.dockerfile
Packages Aqueduct into a Dockerfile. Separating this from the Helm chart PR. 
https://linear.app/aqueducthq/issue/ENG-1783/package-aqueduct-into-docker-container
```
(base) ubuntu@ip-172-31-46-200:~/aqueduct/src/dockerfiles$ docker run aqueducthq/aqueduct:0.0.16
Updating UI version to 0.0.16...
UI: 100%|████████████████████████████████████████████████| 3556.0/3556.0 [00:00<00:00, 94242.71KB/s]
Updated configurations.
Updating server version to 0.0.16...
Operating system is Linux with architecture amd64.
Downloading server binaries...
Server: 100%|██████████████████████████████████████████| 50508.0/50508.0 [00:00<00:00, 99057.15KB/s]
Executor: 100%|████████████████████████████████████████| 48460.0/48460.0 [00:00<00:00, 82032.38KB/s]
Migrator: 100%|███████████████████████████████████████| …
```
=> Adds a Dockerfile for Aqueduct

src/ui/common/src/components/pages/ErrorPage.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/workflows/artifact/content.tsx, src/ui/common/src/components/workflows/artifact/metric/history.tsx, src/ui/common/src/components/workflows/artifact/summaryList.tsx, src/ui/common/src/components/workflows/operator/summaryList.tsx, src/ui/common/src/utils/data.ts
* Makes the titles of the components more uniform and adds divider.
* Fixes margins on Plotly plot to remove dead space; adds light grey background.
* Fixes formatting of timestamp by converting to TS `Date` and using `toLocaleString`.
* Replaces table with success-color-coded divs -- we'll probably want to render this in a paged view in the future, but I prefer this presentation because I found the table headers confusing. Open to feedback on improvements here!
=> [UI redesign] Updates design of metrics page

src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/styles/theme/theme.tsx
Update the color scheme for the nav bar. (https://www.figma.com/file/Qz2IiYJ4NAaDHojOf2YoTm/UI-V2-Screens?node-id=579%3A24342)
Eng 933 
https://user-images.githubusercontent.com/30596854/194128007-5b710d87-7bed-4e05-b85b-3ae957e8f292.mov
- [n/a] I have run the integration tests locally and they are passing.
=> Eng 933 update nav bar color scheme

src/python/bin/aqueduct, src/resources/demo_db/sqlite/v0.1/create_tables.py
Tested that it works with both fresh install and package upgrade.
=> Implement script to add new tables to demo db for the next release

src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/tables/PaginatedTable.tsx, src/ui/common/src/components/workflows/artifact/summaryList.tsx
-Fixes bug where extra closing bracket caused a broken link in ArtifactSummaryList component. 
-Fixes bug where attempting to render null value in PaginatedTable caused app to crash.
ENG-1800
=> ENG-1800 ensure routing works properly

src/ui/common/src/handlers/responses/dag.ts
Fixes build issue when rebasing ui-redesign branch with main
=> Fix ui-redesign build

sdk/aqueduct/api_client.py
This is meant to close the loop on the discussion in: https://github.com/aqueducthq/aqueduct/pull/530
ENG-1537
=> [SDK] Link to the guide when throwing version mismatch error

src/ui/common/src/components/layouts/NavBar.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/handlers/responses/dag.ts
This PR replaces the account icon in the navbar with a settings gear icon.
ENG-1805
Screenshot:
=> Eng 1805 settings navbar icon

src/ui/common/src/components/layouts/NavBar.tsx
This PR adds cursor:pointer to the notifications bell icon in the nav bar.
Also adds to the avatar component next to it as well. 
(this avatar component will be replaced with settings button in another PR)
ENG-1804
https://www.loom.com/share/dbfaa2b900db4d9f9ca126f4ab66a694
=> ENG-1804 Cursor Pointer Fixes

src/ui/common/src/styles/theme/theme.tsx
Update the color of the selected icon to match the icon.
Eng 1806
Before:
After:
=> Eng 1806 unify color between selected icon and logo

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/workflow/utils/migrate.go
This PR migrates operator content (i.e. Python code) when the storage layer is changed. It also does some general refactoring.
ENG 1786
=> Implement storage migration for operator content

sdk/aqueduct/artifacts/numeric_artifact.py
My previous mypy fix refactor introduced a slight typing bug I didn't catch locally. This fixes it. There's no correctness issue, just a typing one.
=> Fix numpy mypy bug (again)

src/ui/common/src/components/layouts/NavBar.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx
This PR adds tooltips to our Navbar
ENG-1863
https://www.loom.com/share/51a95a029c0544909377cb830453435b
=> Eng 1863 navbar tooltips

src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx
Put default values so it does not crash when loading.
Eng 1849
Before:
https://user-images.githubusercontent.com/30596854/195947225-ae8f48a0-83d5-4eab-bc70-5aee1c14d51f.mov
After:
https://user-images.githubusercontent.com/30596854/195947227-89666bfb-4c66-4cec-a320-5b485232f697.mov
=> Eng 1849 fix blank screen when switching workflow

README.md
=> Fixes broken README link

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, .github/workflows/regression-tests.yml, .github/workflows/run-notebooks.yml
Add verbose flag to Github Actions Integration Tests for improved debugging experience.
ENG-1529
=> Add verbose flag to Github Actions Integration Tests

src/ui/common/src/components/pages/workflow/id/index.tsx
Was unable to scroll before.
ENG-1873
https://user-images.githubusercontent.com/30596854/196793756-b6f18047-21f7-4d13-8066-4ffd5e339b79.mov
=> Enable scrolling for query artifact sidesheet

src/golang/cmd/server/server/aqueduct_server.go, src/golang/cmd/server/server/vault.go, src/golang/lib/storage/file.go, src/golang/lib/storage/gcs.go, src/golang/lib/vault/gcs.go, src/golang/lib/vault/vault.go
This PR implements a GCS vault.
ENG 1797
=> [6/7] Implements GCS vault

src/golang/cmd/server/server/aqueduct_server.go, src/golang/cmd/server/server/vault.go, src/golang/lib/storage/file.go, src/golang/lib/storage/gcs.go, src/golang/lib/vault/file.go, src/golang/lib/vault/gcs.go, src/golang/lib/vault/s3.go, src/golang/lib/vault/vault.go
This PR implements an S3 vault. Underneath the hood, all vaults share the same implementation, since we are injecting a storage object into them. We will refactor the fact that currently `Vault` is an interface. In future work, we will just make the `Vault` interface a part of `Storage`.
ENG 1796
=> [5/7] Implements S3 vault

src/golang/lib/collections/workflow_dag/standard.go, src/golang/lib/collections/workflow_dag/workflow_dag.go
This PR adds a new reader method for the workflow dag table to list all dags. This is needed by the migration work.
ENG 1883
=> Implements database ListWorkflowDags

src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
MUI versions got a little out of whack and caused some build errors related to generateClassName. This PR should fix that.
=> Fixes build errors related to generateclassname

src/ui/common/src/styles/theme/theme.tsx
This PR makes sure the navbar icon matches the logo color.
ENG 1928
=> Fixes selected navbar icon color to match logo

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package.json
=> Ready for release 0.1.2

src/ui/common/package-lock.json, src/ui/common/package.json, src/ui/common/src/components/pages/AccountPage.tsx
This PR removes react-code-blocks from the project. App no longer emits a lot of .css files related to programming languages that we're not using in our project.
One thing to note here is that this PR removes the CopyBlock component, so users are no longer able to click a button to copy the connection snippet to clipboard. They can still copy by selecting the text however.
ENG-1830
Here is my terminal output with our new bundles:
```
➜  app git:(main) ✗ npm run build
> @aqueducthq/ui@0.1.2 build
> parcel build --public-url /dist --dist-dir dist/default index.html
✨ Built in 36.41s
dist/default/index.html                   474 B     197ms
dist/default/favicon.01ef7d64.ico     159.11 KB      12ms
dist/default/index.f0e0717d.js       ⚠️  6.2 MB    30.73s
dist/default/index.b8213ca0.css …
```
=> ENG-1830: Removes react-code-blocks from project.

sdk/aqueduct/artifacts/table_artifact.py
Not scalable in the long run, but should help.
ENG-1937
=> Speed up aqueduct import time by cutting great expectations

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package.json
=> Ready for release 0.1.3

src/ui/common/src/stories/Typography.stories.tsx
This PR creates a storybook story for our Typography component and it's variants.
N/A
https://www.loom.com/share/aa7b515de89f4f798538b20ed315bc08
=> Adds Typography stories to storybook docs.

src/golang/lib/models/workflow.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/workflow.go
This PR implements the workflow repo.
- Each table's table name and column names are placed in the relevant model file. Ex: `models/workflow.go`. This is how the implementation in `repos` will have access to the column and table names.
- A helper method is used internally for querying one or multiple models. Ex: `getWorkflows` and `getWorkflow`
ENG 1901 and 1902
=> [2/N] Implements workflow repo

src/golang/cmd/executor/executor/base.go, src/golang/cmd/executor/executor/executor.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/lib/models/schema.go, src/golang/lib/repos/tests/main_test.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/repos/tests/test.go, src/golang/lib/repos/tests/workflow.go
This PR sets up database integration tests for all repos.
The key decisions made are:
- Moving all tests to `repos/tests`
- Each repo should have a corresponding test file named, e.g. `workflow.go`. Inside this test file will be a test case for each repo method, such as `TestWorkflow_Exists`, `TestWorkflow_Get`.
- Any `seed` functions, such as `seedWorkflow` or `seedUser` or `seedDAGWithWorkflow` should be implemented in `seed.go`. These are essentially helper methods that each test can call to quickly generate some test data.
- The database will be wiped after EACH test case. This follows the current approach we have. This is because we just want to verify that each query is correct.
- `skip_integration_test`: Skips integration tests …
=> [3/N] Sets up testing for repos

src/ui/common/src/components/integrations/dialogs/lambdaDialog.tsx
Fixes prompt for lambda role arn
=> Fix prompt for lambda role arn

src/Makefile, src/golang/lib/repos/sqlite/user.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/tests/random.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/repos/tests/user.go, src/golang/lib/repos/user.go
This PR implements the user repo and adds integration tests for it. It changes the make command for triggering these tests.
=> Implements user repo

src/Makefile, src/golang/lib/models/schema.go, src/golang/lib/models/user.go, src/golang/lib/repos/sqlite/user.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/tests/random.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/repos/tests/user.go, src/golang/lib/repos/user.go
This PR defines the user model and repo.
ENG 1912
=> Defines user model and repo

src/golang/lib/repos/sqlite/user.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/tests/random.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/workflow.go, src/golang/lib/repos/workflow.go
This PR adds DB integration tests for the workflow repo.
ENG 1964
=> Implements workflow repo tests

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package.json
=> Ready for release 0.1.4

integration_tests/sdk/resources_test.py
Adding tests:
```
Url:  http://3.130.165.53:8080/workflow/bbd4bab2-b129-4cd0-bf6c-32b058f8066c
Workflow registration succeeded. Workflow ID bbd4bab2-b129-4cd0-bf6c-32b058f8066c. Name: test_b6e85d1295424ffda66d1807766bda3a
Workflow bbd4bab2-b129-4cd0-bf6c-32b058f8066c was created and ran successfully at least 1 times!
Url:  http://3.130.165.53:8080/workflow/2453a35f-5b25-4c00-8240-e06f993a5185
Workflow registration succeeded. Workflow ID 2453a35f-5b25-4c00-8240-e06f993a5185. Name: test_19e640e311cd4ec79285cb99d3464ea3
Workflow 2453a35f-5b25-4c00-8240-e06f993a5185 was created and ran successfully at least 1 times!
```
=> Add tests for using GPUs for K8s

src/golang/lib/repos/dag.go, src/golang/lib/repos/sqlite/dag.go, src/golang/lib/repos/tests/dag.go, src/golang/lib/repos/tests/random.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/repos/tests/workflow.go
This PR implements the DAG repo and adds tests.
ENG 2004
=> Implements DAG repo

src/golang/lib/models/dag.go, src/golang/lib/models/shared/engine.go, src/golang/lib/models/shared/storage.go, src/golang/lib/repos/dag.go, src/golang/lib/repos/sqlite/dag.go, src/golang/lib/repos/tests/dag.go, src/golang/lib/repos/tests/random.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/repos/tests/workflow.go
This PR defines the DAG model and repo.
ENG 1914
=> Defines DAG model and repo

src/golang/lib/repos/dag_edge.go, src/golang/lib/repos/sqlite/dag_edge.go, src/golang/lib/repos/tests/dag_edge.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go
Implements DAGEdge repo and tests.
ENG 2008
=> Implements DAGEdge repo

src/golang/lib/repos/sqlite/watcher.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/repos/tests/watcher.go
This PR implements the watcher repo and adds tests.
ENG 2007
=> Implements Watcher repo

src/golang/lib/repos/dag_result.go, src/golang/lib/repos/errors.go, src/golang/lib/repos/sqlite/dag.go, src/golang/lib/repos/sqlite/dag_result.go, src/golang/lib/repos/tests/dag_result.go, src/golang/lib/repos/tests/random.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go
Implements DAGResult repo and adds tests.
ENG 2006
=> Implements DAGResult repo

src/golang/lib/models/dag_edge.go, src/golang/lib/models/dag_result.go, src/golang/lib/models/shared/dag_edge.go, src/golang/lib/repos/dag_edge.go, src/golang/lib/repos/sqlite/dag_edge.go, src/golang/lib/repos/tests/dag_edge.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go
This PR defines the DAGEdge model and repo.
ENG 1915
=> Defines DAGEdge model and repo

src/golang/lib/models/dag_edge.go, src/golang/lib/models/watcher.go, src/golang/lib/repos/sqlite/watcher.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/repos/tests/watcher.go, src/golang/lib/repos/watcher.go
Defines Watcher model and repo.
ENG 1917
=> Defines watcher model and repo

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Ready for release 0.1.5

.github/workflows/periodic-integration-tests.yml
=> Fix syntax in periodic integration tests

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/execution_environment/execution_environment.go, src/golang/lib/execution_environment/integration.go, src/ui/common/src/components/integrations/cards/condaCard.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/conda/condaConnectionStatus.tsx, src/ui/common/src/components/integrations/dialogs/condaDialog.tsx
This PR adds more description and details to render conda connection state, based on the fundamentals introduced in #726 . Specifically, we added more details to explain in-progress connection, and more instructions when the connection failed.
ENG-2027
In-progress case:
In-progress case with narrow screen:
Succeeded case:
WIP: failure case
=> Eng 2027 Show more details for conda connection state.

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/collections/execution_environment/execution_environment.go, src/golang/lib/collections/execution_environment/noop.go, src/golang/lib/collections/execution_environment/standard.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/execution_environment/execution_environment.go, src/golang/lib/execution_environment/integration.go, src/ui/common/src/components/integrations/cards/condaCard.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/conda/condaConnectionStatus.tsx, src/ui/common/src/components/integrations/dialogs/condaDialog.tsx
This PR adds a 'prerequisite' check that prevents conda connection if there's already one connected.
ENG-2024
Verified in UI:
=> Eng 2024 m3 block user from connecting to conda

src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/down_postgres.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/up_postgres.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/up_sqlite.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/list_operators_for_integration.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/collections/execution_environment/execution_environment.go, src/golang/lib/collections/execution_environment/noop.go, src/golang/lib/collections/execution_environment/standard.go, src/golang/lib/collections/operator/operator.go, src/golang/lib/collections/operator/postgres.go, src/golang/lib/collections/operator/sqlite.go, src/golang/lib/collections/operator/standard.go, src/golang/lib/collections/tests/operator_test.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/execution_environment/execution_environment.go
For conda integration, we use a custom SQL query that gets all operators that has a non-null execution env id attached.
=> Update list operators for integration to work with conda

src/golang/cmd/executor/executor/database.go, src/golang/cmd/executor/executor/workflow_retention.go, src/golang/cmd/server/handler/delete_workflow.go, src/golang/cmd/server/handler/edit_workflow.go, src/golang/cmd/server/handler/get_workflow.go, src/golang/cmd/server/handler/get_workflow_dag_result.go, src/golang/cmd/server/handler/list_notifications.go, src/golang/cmd/server/handler/list_workflow_objects.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/handler/refresh_workflow.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/handler/watch_workflow.go, src/golang/cmd/server/request/dag.go, src/golang/cmd/server/server/cron.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/airflow/sync.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/models/dag.go, src/golang/lib/models/workflow.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/workflow.go, src/golang/lib/repos/workflow.go, src/golang/lib/workflow/dag/response.go, src/golang/lib/workflow/dag/workflow_dag.go, src/golang/lib/workflow/utils/database.go
=> [5/N] Replaces workflow DB reader/writer with repo

src/golang/cmd/executor/executor/database.go, src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/get_artifact_result.go, src/golang/cmd/server/handler/get_workflow.go, src/golang/cmd/server/handler/get_workflow_dag_result.go, src/golang/cmd/server/handler/list_artifact_results.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/handler/refresh_workflow.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/server/cron.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/airflow/sync.go, src/golang/lib/collections/artifact_result/types.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/job/spec.go, src/golang/lib/models/dag.go, src/golang/lib/workflow/artifact/artifact.go, src/golang/lib/workflow/artifact/response.go, src/golang/lib/workflow/dag/response.go, src/golang/lib/workflow/dag/validation_test.go, src/golang/lib/workflow/dag/workflow_dag.go, src/golang/lib/workflow/operator/extract.go, src/golang/lib/workflow/utils/database.go, src/golang/lib/workflow/utils/migrate.go
This PR replaces the artifact DB reader/writer usage with the new repo.
ENG 2057
=> [8/N] Replaces artifact DB reader/writer with repo

src/golang/cmd/executor/executor/database.go, src/golang/cmd/executor/executor/workflow_retention.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/handler/get_workflow.go, src/golang/cmd/server/handler/get_workflow_dag_result.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/airflow/sync.go, src/golang/lib/airflow/writer.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/models/operator_result.go, src/golang/lib/repos/operator_result.go, src/golang/lib/repos/sqlite/operator_result.go, src/golang/lib/workflow/dag/response.go, src/golang/lib/workflow/dag/workflow_dag.go, src/golang/lib/workflow/operator/base.go, src/golang/lib/workflow/operator/operator.go, src/golang/lib/workflow/operator/response.go
This PR replaces the operator result DB reader and writer usage with the new repo.
ENG 2056
=> [12/N] Replaces operator result DB reader/writer with repo

src/golang/cmd/executor/executor/database.go, src/golang/cmd/executor/executor/workflow_retention.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/handler/get_workflow.go, src/golang/cmd/server/handler/get_workflow_dag_result.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/airflow/sync.go, src/golang/lib/airflow/writer.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/models/operator_result.go, src/golang/lib/repos/operator_result.go, src/golang/lib/repos/sqlite/operator_result.go, src/golang/lib/workflow/dag/response.go, src/golang/lib/workflow/dag/workflow_dag.go, src/golang/lib/workflow/operator/base.go, src/golang/lib/workflow/operator/operator.go, src/golang/lib/workflow/operator/response.go
This PR implements the operator result repo. The tests will need to be added in a different PR, since it depends on operator repo being implemented.
ENG 2023
=> [11/N] Implements operator result repo

src/golang/cmd/executor/executor/database.go, src/golang/cmd/executor/executor/workflow_retention.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/handler/get_workflow.go, src/golang/cmd/server/handler/get_workflow_dag_result.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/airflow/sync.go, src/golang/lib/airflow/writer.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/models/operator_result.go, src/golang/lib/repos/operator.go, src/golang/lib/repos/operator_result.go, src/golang/lib/repos/sqlite/operator.go, src/golang/lib/repos/sqlite/operator_result.go, src/golang/lib/repos/tests/operator.go, src/golang/lib/repos/tests/require.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/repos/tests/suite.go, src/golang/lib/workflow/dag/response.go, src/golang/lib/workflow/dag/workflow_dag.go, src/golang/lib/workflow/operator/base.go, src/golang/lib/workflow/operator/operator.go, src/golang/lib/workflow/operator/response.go
This PR implements the operator repo and completes some of the integration tests. The remaining tests should be added as a follow on task.
ENG 2022
=> [10/N] Implements operator repo

src/golang/lib/models/schema.go
=> Bumps schema version to 21

src/golang/cmd/executor/executor/database.go, src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/create_table.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/delete_workflow.go, src/golang/cmd/server/handler/discover.go, src/golang/cmd/server/handler/edit_integration.go, src/golang/cmd/server/handler/list_integration_objects.go, src/golang/cmd/server/handler/list_integrations.go, src/golang/cmd/server/handler/list_operators_for_integration.go, src/golang/cmd/server/handler/preview.go, src/golang/cmd/server/handler/preview_table.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/handler/test_integration.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/cmd/server/server/test_account.go, src/golang/cmd/server/server/vault.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/execution_environment/integration.go, src/golang/lib/models/integration.go, src/golang/lib/repos/integration.go, src/golang/lib/repos/sqlite/integration.go, src/golang/lib/repos/tests/integration.go, src/golang/lib/repos/tests/seed.go, src/golang/lib/workflow/dag/validation.go, src/golang/lib/workflow/utils/migrate.go
This PR replaces the DB reader/writer for integrations with the new repo.
ENG 2055
=> [14/N] Replaces integration DB reader/writer with repo

src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/list_operators_for_integration.go, src/golang/cmd/server/server/cron.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/repos/operator.go, src/golang/lib/repos/sqlite/operator.go
This PR replaces left over calls to the operator and workflow DB readers with the relevant repo.
ENG 2078
=> Replaces remaining operator and workflow DB readers with repo

manual_qa_tests/README.md
=> Update QA readme

scripts/generate_docs.sh
Since we updated the directory structure of our SDK, we need to update the doc generation script accordingly.
=> Update Gitbook doc generation script

sdk/aqueduct/models/dag.py
Fixes bug with setting engines on operator level on SDK.
=> Fixes bug with engines on SDK

src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/pages/data/index.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/tables/PaginatedSearchTable.tsx
This PR fixes a number of linter errors on the UI.
https://linear.app/aqueducthq/issue/ENG-2091/fix-lint-error
Demo:
```
aqueduct-env) ➜  common git:(eng-2091-fix-lint-error) ✗ npm run lint:fix
> @aqueducthq/common@0.1.7 lint:fix
> eslint '*/**/*.{js,ts,tsx}' --format table --fix
╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 0 Errors                                                                                                       ║
╟────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 0 Warnings                                                                                                     ║ …
```
=> ENG-2091: Fix linter errors on UI

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Release version 0.1.8

src/ui/common/src/components/pages/workflow/id/index.tsx
Fix the right margin to take up less space.
Eng 2108
Before:
After:
=> Eng 2108 bug fix margin on right side of workflow

integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/shared/utils.py, sdk/aqueduct/backend/response_models.py, sdk/aqueduct/flow.py, sdk/aqueduct/integrations/sql_integration.py
=> Fix bug where flow.list_saved_objects() crashes if no objects were saved

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, CONTRIBUTING.md
Updates our Github Actions to run both SDK Integration Test suites against the Demo DB.
I'll check that this works before merging this stack of PRs.
ENG-2113
=> [3/3] Update the github actions to run the two SDK integration test suites

integration_tests/sdk/aqueduct_tests/flow_test.py, src/golang/lib/graph/directed_test.go, src/golang/lib/workflow/validate_test.go
This PR adds unit tests and integration tests throughout the codebase for logic involved in cascading workflow cycle detection.
=> Adds unit tests and integration tests for cycle detection in cascading workflows

src/golang/cmd/server/handler/register_workflow.go, src/golang/lib/graph/directed.go, src/golang/lib/graph/node.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/tests/workflow.go, src/golang/lib/repos/workflow.go, src/golang/lib/workflow/validate.go
I accidentally merged this work into the wrong branch earlier. We need to get it into main.
=> Prevents cycles in cascading workflows

integration_tests/sdk/README.md
Small rewrite to make things a little more clear. Additional info requests welcome!
=> Improve the Integration Tests README

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> preparing for release 0.1.9

CHANGELOG.md
=> Fix v0.1.9 release log from Jan 9 -> Jan 10

src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/components/DetailsPageHeader.tsx, src/ui/common/src/components/pages/operator/id/index.tsx
This PR updates the Details Page header to properly show the correct status of operators and artifacts.
ENG-2183
https://www.loom.com/share/a46f905d47f34a8d9f6a0b6d795bf608
=> ENG-2183 Show Correct Operator/Artifact Status

integration_tests/sdk/data_integration_tests/conftest.py, integration_tests/sdk/data_integration_tests/s3_data_validator.py, integration_tests/sdk/data_integration_tests/s3_test.py, sdk/aqueduct/artifacts/save.py, sdk/aqueduct/integrations/s3_integration.py, src/python/aqueduct_executor/operators/connectors/data/s3.py
With this, we will have added fairly complete coverage of the S3 Integration.
ENG-2113
=> [2/2] Add S3 Data Integration Tests

src/ui/common/src/components/integrations/addIntegrations.tsx
Orders both compute and data integrations by name.
=> Order integrations alphabetically on integrations page

scripts/install_local.py, src/python/bin/aqueduct, src/ui/Makefile, src/ui/app/package.json
Because there is no plan to support it in the near term.
=> Remove SageMaker from UI build

src/golang/cmd/server/handler/edit_workflow.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/graph/directed.go, src/golang/lib/workflow/validate.go
This PR adds backend support to the edit_workflow endpoint for modifying a source workflow.
=> Adds backend support for editing source workflow

src/golang/cmd/server/handler/edit_workflow.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/graph/directed.go, src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/components/workflows/triggerSourceSelector.tsx
This PR adds UI support for changing the source workflow.
ENG 2181
https://www.loom.com/share/a834542eeae7492d81c08636d87b963a
=> Adds UI support for changing the source workflow

src/ui/common/src/components/integrations/dialogs/deleteIntegrationDialog.tsx
=> Improve error message for integrations that are in-use

src/ui/common/src/utils/integrations.ts
Temporary patch that adds a duplicate entry to the UI dictionary.
=> Fix bug where K8s Logo does not show up

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
This PR bumps version numbers to prepare for our 0.1.11 release.
=> Prepare for 0.1.11 Release

src/golang/cmd/server/handler/get_operator_result.go
=> Fix bug where get operator result go routine fails to check for error

src/python/aqueduct_executor/operators/connectors/data/s3.py
Based on the solution suggested here: https://stackoverflow.com/a/26871885
=> Fix bug where S3 integration authentication step fails even when the user does have permission

src/golang/cmd/server/handler/connect_integration.go, src/golang/go.mod, src/golang/go.sum, src/golang/lib/collections/integration/constants.go, src/golang/lib/lib_utils/utils.go, src/golang/lib/models/shared/integration_config.go, src/golang/lib/notification/slack.go, src/golang/lib/workflow/operator/connector/auth/static_config.go, src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/cards/emailCard.tsx, src/ui/common/src/components/integrations/cards/slackCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/emailDialog.tsx, src/ui/common/src/components/integrations/dialogs/slackDialog.tsx, src/ui/common/src/components/notifications/NotificationLevelSelector.tsx, src/ui/common/src/components/pages/integration/id/index.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/index.tsx, src/ui/common/src/utils/integrations.ts
This PR adds UI changes for email connection. Verified (as shown in demo) that connect, edit, and deletion works properly.
The only thing for feedback is the notification level selector that automatically covers 'lower' level of notifications when certain level is selected.
ENG-2193
https://www.loom.com/share/a41ad69dece24b6c9236b3fd30d0a4dd
Add new integration: 0 - 1:05
Level selector: 37s
Edit: 1:05 - 1:30
Delete: 1:30 - end
=> [2/2][UI] Eng 2193 Allow connecting to email as integration

integration_tests/sdk/data_integration_tests/conftest.py, integration_tests/sdk/setup_integration.py, integration_tests/sdk/test-config-example.yml, sdk/aqueduct/integrations/connect_config.py
This PR adds data integration tests for Redshift.
ENG 2287
=> Adds data integration tests for Redshift

.github/workflows/integration-tests.yml, scripts/install_local.py
GH actions are failing. This PR attemps to run `pip install .` before starting the server.
ENG-2355
=> Fix a bug where demo db upload is broken in GH actions

src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/tables/CheckTableItem.tsx, src/ui/common/src/components/tables/MetricTableItem.tsx, src/ui/common/src/components/tables/OperatorExecStateTable.tsx, src/ui/common/src/components/workflows/artifact/check/history.tsx, src/ui/common/src/components/workflows/artifact/metric/history.tsx, src/ui/common/src/components/workflows/artifact/metricsAndChecksOverview.tsx, src/ui/common/src/handlers/responses/dag.ts, src/ui/common/src/utils/data.ts, src/ui/common/src/utils/shared.ts
This PR contains UI bug fixes to better handle rendering checks and metrics that have …no values due to failed workflow execution.
ENG-2309
https://www.loom.com/share/925a341bb75d472394611c41b412eee6
=> ENG-2309 UI bug fixes for better rendering metrics and checks that have no value

CHANGELOG.md
=> Add release 0.2.0 changelog

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Ready for release 0.2.0

.github/workflows/periodic-integration-tests.yml
=> Fix broken periodic integration tests

src/ui/common/src/components/integrations/dialogs/databricksDialog.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx
This PR fixes an issue where the confirm dialog did not show when all required fields were filled out.
ENG-2373
https://www.loom.com/share/26b914b4c1994050badfef874a05fea6
=> ENG-2373 Improve Databricks Add Integration Form Validation

.github/workflows/skip-pre-merge-ci.yml, .github/workflows/skipped-integration-tests.yml
=> Fix the skip integration test label

integration_tests/sdk/setup_integration.py, integration_tests/sdk/test-config-example.yml, integration_tests/sdk/test-credentials-example.yml, scripts/postgres_test_setup.sh, scripts/postgres_test_teardown.sh
This PR adds Postgres data integration to the sdk integration tests.
ENG-2286
=> ENG-2286 Postgres Integration Test Setup

src/dockerfiles/function/start-function-executor.sh, src/dockerfiles/gpu/start-function-executor-gpu.sh, src/python/aqueduct_executor/operators/connectors/data/execute.py, src/python/aqueduct_executor/operators/connectors/data/main.py, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/operators/function_executor/extract_function.py, src/python/aqueduct_executor/operators/function_executor/install_requirements.py, src/python/aqueduct_executor/operators/function_executor/main.py, src/python/aqueduct_executor/operators/spark/execute_function.py, src/python/aqueduct_executor/operators/utils/enums.py, src/python/aqueduct_executor/operators/utils/utils.py, src/python/aqueduct_executor/start-function-executor.sh
This gives us useful information about where the bottlenecks are.
=> Log performance breakdown when running Python operators

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> 0.2.1 --> 0.2.2 Release

src/ui/common/src/components/pages/workflows/components/CheckItem.tsx, src/ui/common/src/components/pages/workflows/components/ChecksListPreview.tsx, src/ui/common/src/components/pages/workflows/components/MetricItem.tsx, src/ui/common/src/components/workflows/workflowStatus.tsx, src/ui/common/src/utils/shared.ts
This PR shows check status indicators on one line when the checks metadata table cell is collapsed.
ENG-2369
https://www.loom.com/share/636740b03f744ea586b38f980e7a7297
=> ENG-2369 Checks List Overview in Check Metadata Table Cell

src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/lambda/connectors/s3.dockerfile
Installs tensorflow on S3 images so we can use keras models on K8s/Lambda.
[In progress] Test Keras workflow on K8s: 
Eng-2489
Before change:
After Change:
=> Adds tensorflow to s3 images

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Creates 0.2.3 Release

manual_qa_tests/README.md, manual_qa_tests/initialize.py, manual_qa_tests/notification.py
Updates the checklist and renames a typo function
Eng-2484
=> Updates manual qa test checklist

src/ui/common/src/components/layouts/menuSidebar.tsx
Change link behavior for docs and feedback sidebar links
ENG 2499
Before
https://user-images.githubusercontent.com/30596854/221023600-99f52916-984b-4aa7-8bd3-4e349b88762e.mov
After
https://user-images.githubusercontent.com/30596854/221023575-05f2c21a-0c1f-464c-bad6-ceb03e2039fa.mov
=> ENG 2499 open docs and feedback links in new tab

sdk/aqueduct/client.py, sdk/aqueduct/constants/enums.py, sdk/aqueduct/integrations/__init__.py, sdk/aqueduct/integrations/connect_config.py, sdk/aqueduct/integrations/spark_integration.py, sdk/aqueduct/models/config.py, sdk/aqueduct/models/dag.py, sdk/aqueduct/tests/enum_test.py, sdk/aqueduct/utils/utils.py
=> Use Spark integration on SDK

sdk/aqueduct/constants/enums.py, src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/cards/sparkCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/sparkDialog.tsx, src/ui/common/src/index.tsx, src/ui/common/src/utils/integrations.ts
=> Adding Spark integration to UI

src/golang/cmd/server/handler/connect_integration.go, src/golang/lib/engine/authenticate.go, src/golang/lib/lib_utils/utils.go, src/golang/lib/livy/client.go, src/golang/lib/livy/client_test.go, src/golang/lib/livy/entrypoints.go, src/golang/lib/livy/types.go, src/golang/lib/models/shared/integration_config.go, src/golang/lib/models/shared/service.go, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/sparkDialog.tsx
Add Livy client that will be used by SparkJobManager to ship operators to Spark EMR.
=> [1/2] Add golang apache livy client

.github/workflows/integration-tests.yml, .github/workflows/skipped-integration-tests.yml
Adds in finally the couple of data-integration tests. Runs in about 12 minutes.
ENG-2347
=> Complete our pre-merge test suite

.github/actions/fetch-test-config/action.yml, .github/workflows/integration-tests.yml, .github/workflows/pre-merge-ci.yml, sdk/aqueduct/client.py
=> Fixes broken pre-merge tests

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/WorkflowSettings.tsx
Soft refresh workflow details page when settings updated and navigate back to Details Pane.
ENG-2170
Updated Demo:
https://www.loom.com/share/1d7ca8e73df34f62895290411e932a30
=> ENG-2170 Settings Update Toast and Navigation Updates

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
This PR prepares for the 0.2.5 release
=> 0.2.5 Release

src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/lib/workflow/operator/operator.go, src/python/aqueduct_executor/operators/airflow/dag.template
This PR fixes a couple bugs for registering airflow workflows. These came up when recording a demo. Comments are provided inline for why these bug fixes are needed and if there is any follow on work.
ENG 2600
This is also how I performed testing for these changes. Please see https://www.loom.com/share/ffe3fa8086e244e5ad06faac87d6630c
=> Fixes airflow workflow registration bugs

src/ui/common/package-lock.json, src/ui/common/package.json
This PR fixes a crash which would happen whenever users visited the workflow details page.
ENG-2610
https://www.loom.com/share/09db460df1e74b3eb012d8a632f5d0ba
=> ENG-2610: Fix crash on workflow details page

src/ui/common/src/components/workflows/artifact/metric/history.tsx
=> Remove unnecessary history header

src/golang/lib/engine/aq_engine.go, src/golang/lib/job/databricks.go
Fixes bug by creating a DatabricksJobManager for the entire workflow.
Eng-2603
=> Fix bug with DatabricksJob preview

examples/wine-ratings-prediction/Spark Wine Ratings Demo.ipynb
Adds a notebook that uses Spark + either Spark/Databricks integrations.
=> Added notebook for Spark Demo

src/dockerfiles/Makefile
Updates gpu names in Makefile to match new dockerfiles.
=> Updates gpu names in Makefile

src/golang/lib/engine/engine.go
This PR updates the default workflow timeout to 48 hours.
=> Updates default workflow timeout to 48 hours

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
This PR contains version number updates to bump to version 0.2.6
=> Release v0.2.6

src/golang/cmd/server/server/execute_handler.go
=> Change error surfacing to also return inner error messages

sdk/aqueduct/integrations/connect_config.py, src/golang/lib/dynamic/engine.go, src/golang/lib/engine/authenticate.go, src/golang/lib/lib_utils/utils.go, src/golang/lib/models/shared/integration_config.go
=> Allow registering AWS integration via credential file path and profile

sdk/aqueduct/integrations/connect_config.py, src/golang/cmd/server/handler/cloud_integration_utils.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/list_operators_for_integration.go, src/golang/lib/dynamic/engine.go, src/golang/lib/engine/authenticate.go, src/golang/lib/lib_utils/utils.go, src/golang/lib/models/shared/integration_config.go
This is done by substituting the cloud integration's ID with the dynamic k8s integration ID.
=> List workflows that use dynamic k8s integration when clicking into AWS integration

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, integration_tests/sdk/setup_integration.py, integration_tests/sdk/test-credentials-example.yml, src/python/aqueduct_executor/operators/connectors/data/relational.py
Setups up an external SQLite database based on the path in`test-credentials.yml`. Creates the parent directories too.
ENG-2637
=> Add automated periodic integration test coverage for SQLite

.github/workflows/periodic-integration-tests.yml
=> Upload more state and retry when terraform destroy fails

CHANGELOG.md
=> Changelog typo fix

CHANGELOG.md
=> Fix ondemand k8s doc link

integration_tests/backend/setup/flow_with_failure.py, integration_tests/backend/setup/flow_with_sleep.py, integration_tests/no_concurrency/sdk/requirements_test.py, integration_tests/sdk/aqueduct_tests/package_test.py, integration_tests/sdk/data_integration_tests/relational_test.py, integration_tests/sdk/data_integration_tests/s3_test.py, sdk/aqueduct/__init__.py, sdk/aqueduct/client.py, sdk/aqueduct/decorator.py, sdk/aqueduct/error.py, sdk/aqueduct/tests/decorator_test.py, sdk/aqueduct/utils/function_packaging.py
Remove gathering module prerequisites from environment using pip freeze command
This is error prone, and different user environment may have different modules, and leads to inconsistent runtime behavior.
This change raises a RequirementsFileMissingError exception if either requirement is not provided as a list parameter or requirement.txt file is missing in the current working directory of the imported python function.
ENG 2551
=> Remove gathering requirements from user environment

integration_tests/sdk/data_integration_tests/relational_test.py, integration_tests/sdk/data_integration_tests/s3_test.py, sdk/aqueduct/utils/function_packaging.py
The requirements.txt file is needed when using operators if we are not passing the list as parameter
ENG-2551
- [ x] Added one of the following CI labels:
=> Add an empty requirements.txt files

integration_tests/sdk/aqueduct_tests/param_test.py, manual_qa_tests/workflows/succeed_dag_layout_test.py, manual_qa_tests/workflows/succeed_march_madness_dag_layout_test.py, scripts/generate_docs.sh, sdk/aqueduct/decorator.py
The PR also contains some changes due to updating the Python linter, and minor update to the doc generation script.
=> Create implicit parameters with the default value being what's specified in the function signature

src/golang/lib/engine/aq_engine.go
Fixes bug with publishing against Databricks Integration where the JobManager creation during ExecuteWorkflow was missing a engine type case check.
=> Fix bug with ExecuteWorkflow and DatabricksJobs

README.md
This PR reframes the README to match our latest positioning.
=> Reframe README to match latest positioning

src/ui/common/src/components/workflows/workflowHeader.tsx
=> [ENG-2717] Fix bug where engine icon was broken in workflow header

src/ui/common/src/components/integrations/cards/mongoDbCard.tsx, src/ui/common/src/components/integrations/dialogs/mongoDbDialog.tsx
Uri --> URI
mongoDB --> MongoDB
ENG 2707
Before
After
=> ENG 2707 MongoDB text consistency in Integration Connection Card

examples/churn_prediction/Customer Churn Prediction.ipynb, examples/house-price-prediction/House Price Prediction.ipynb, examples/sentiment-analysis/Sentiment Model.ipynb, examples/tutorials/Parameters Tutorial.ipynb
Update the jupyiter notebook links in example workflows section
ENG-2721
- [ x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
=> Update the jupyiter notebook links in example workflows section

src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json, src/ui/common/src/handlers/AqueductApi.ts
This PR fixes prod build issue that's related to redux toolkit. The fix follows discussions in https://github.com/reduxjs/redux-toolkit/issues/1960 .
ENG-2737
Verified that the prod build (`python3 scripts/install_local -u`) crashed without the fix, and works with the fix
=> Fix a bug where UI builds works in dev mode but not production

src/ui/common/src/components/integrations/dialogs/databricksDialog.tsx
Added documentation links to Databricks Dialog
=> Added documentation links to Databricks Dialog

.github/workflows/pre-merge-ci.yml
=> [Test] Testing the merge queue

integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/shared/flow_helpers.py, sdk/aqueduct/artifacts/preview.py, sdk/aqueduct/backend/api_client.py, sdk/aqueduct/backend/response_helpers.py, sdk/aqueduct/backend/response_models.py, sdk/aqueduct/client.py, sdk/aqueduct/flow.py, sdk/aqueduct/flow_run.py, sdk/aqueduct/integrations/dynamic_k8s_integration.py, sdk/aqueduct/models/artifact.py, sdk/aqueduct/models/response_models.py, sdk/aqueduct/models/utils.py, sdk/aqueduct/tests/serialization_test.py, sdk/aqueduct/tests/utils.py, sdk/aqueduct/utils/utils.py
This is not only good for `flow_run.describe()`, but we also plug it into our integration test suite, so that whenever a workflow fails when it's supposed to succeed, we will call `flow_run.describe()` on the failed flow and get any workflow-level or operator-level errors and logs printed out. 
This should both save us time debugging, and also bring some parity between the UI and SDK wrt to error surfacing. The errors that are surfaced on the workflows page will also be accessible through `flow_run.describe()` now.
This is what an failure in expected workflow status now looks on the console:
This is what the following workflow now looks like when fetched from the SDK:
```
@op
def foo():
return 123
@op
def bar(input):
print("HELLO IM IN BAR")
5/0
return input
output = bar.lazy(foo.lazy()) …
```
=> Enhance flow_run.describe() to also print failed execution state

README.md
=> Add market landscape diagram to README

examples/run_notebook.py, sdk/aqueduct/flow_run.py
This is currently broken on main.
ENG-2752
=> Fix broken run_notebooks GH action

.github/workflows/periodic-integration-tests.yml, integration_tests/sdk/setup_integration.py
This PR sets up periodic integration tests to run tests against Postgres.
Setup here is a little different than I expected due to the way that Github Actions handles networking.
Followed a tutorial here and was able to get a Postgres service up and running:
https://josef.codes/using-a-real-postgres-database-in-your-github-ci-pipeline/
ENG-2639
N/A (see actions tab here 😄 )
=> ENG-2639 Postgres Periodic Integration Tests

CONTRIBUTING.md
I was just going over the CONTRIBUTING.md since I'd like to link that to our contributor. It looks good but I wonder if we can help them save some time by not having to rebuild the UI each time if they don't have to?
=> Update CONTRIBUTING.md with some advice about install_local.py

.github/workflows/lint-golang.yml, .github/workflows/lint-python.yml, scripts/data/redshift_test.py
- run_linters.py formats the `/scripts` directory, but we don't yet check that in lint-sdk.yml
- Both the golang and python linters need to be pinned to an exact version so we stop getting surprised by lint upgrades.
=> Made various fixes to our linting process

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/dockerfiles/spark/spark-py37-env.dockerfile, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Ready for release 0.2.10

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml
Saves 2x the cost. Makes our pre-merge tests 25% slower, and I haven't seen it affect the K8s compute tests performance that much.
=> Use 4 core instead of 8 core machines in GH actions

.github/workflows/mypy.yml, regression_tests/tests/gitbook/test_docs.py, src/python/aqueduct_executor/operators/connectors/data/execute.py, src/python/bin/aqueduct
This PR installs dependencies needed to run mysql clients on Mac.
For more background on the fix, please see StackOverflow post here:
https://stackoverflow.com/questions/39574813/error-loading-mysqldb-module-no-module-named-mysqldb
ENG-2759
Loom Demo:
https://www.loom.com/share/4a292575335644a98eb91f4b88ceb9d7
=> ENG-2759 Installs dependencies for mac mysql connection

.github/workflows/mypy.yml, .github/workflows/periodic-integration-tests.yml, integration_tests/sdk/aqueduct_tests/save.py, integration_tests/sdk/data_integration_tests/conftest.py, integration_tests/sdk/setup_integration.py, regression_tests/tests/gitbook/test_docs.py, sdk/aqueduct/integrations/sql_integration.py, src/python/aqueduct_executor/operators/connectors/data/execute.py, src/python/bin/aqueduct
Creating another branch to see if still issues with gh actions
=> ENG-2640: MySQL periodic integration test

.github/workflows/periodic-integration-tests.yml, src/golang/lib/job/k8s.go
=> Fix bug where race condition may occur when we create k8s secret for `AwsCredentialsSecretName`

src/Makefile
=> [do not merge] test

CHANGELOG.md, sdk/setup.py, src/dockerfiles/Makefile, src/dockerfiles/connectors/athena.dockerfile, src/dockerfiles/connectors/bigquery.dockerfile, src/dockerfiles/connectors/mysql.dockerfile, src/dockerfiles/connectors/postgres.dockerfile, src/dockerfiles/connectors/s3.dockerfile, src/dockerfiles/connectors/snowflake.dockerfile, src/dockerfiles/connectors/sqlserver.dockerfile, src/dockerfiles/function/function310.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/function/function38.dockerfile, src/dockerfiles/function/function39.dockerfile, src/dockerfiles/gpu/py310_env.yml, src/dockerfiles/gpu/py37_env.yml, src/dockerfiles/gpu/py38_env.yml, src/dockerfiles/gpu/py39_env.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/function/requirements.txt, src/dockerfiles/lambda/requirements.txt, src/dockerfiles/spark/spark-py37-env.dockerfile, src/golang/lib/constants.go, src/python/bin/aqueduct, src/python/requirements.txt, src/python/setup.py, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
=> Release 0.2.11

scripts/install_local.py, sdk/aqueduct/backend/response_helpers.py, sdk/aqueduct/integrations/lambda_integration.py, sdk/aqueduct/models/execution_state.py, sdk/aqueduct/models/integration.py, sdk/aqueduct/models/response_models.py, sdk/aqueduct/tests/serialization_test.py, sdk/aqueduct/utils/utils.py, src/golang/cmd/migrator/migrator/register.go, src/golang/cmd/migrator/versions/000026_drop_integration_validated_column/down_postgres.go, src/golang/cmd/migrator/versions/000026_drop_integration_validated_column/main.go, src/golang/cmd/migrator/versions/000026_drop_integration_validated_column/up_postgres.go, src/golang/cmd/migrator/versions/000026_drop_integration_validated_column/up_sqlite.go, src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/list_integrations.go, src/golang/cmd/server/server/test_account.go, src/golang/lib/execution_environment/conda_integration.go, src/golang/lib/execution_state/integration.go, src/golang/lib/lambda/utils.go, src/golang/lib/models/integration.go, src/golang/lib/models/schema_version.go, src/golang/lib/repos/integration.go, src/golang/lib/repos/sqlite/integration.go, src/golang/lib/repos/sqlite/storage_migration.go, src/golang/lib/repos/sqlite/utils.go, src/golang/lib/repos/tests/integration.go, src/golang/lib/repos/tests/seed.go, src/python/bin/aqueduct
@likawind as lead reviewer. @hsubbaraj-spiral as secondary to maybe help answer Qs. The meat of the changes are in `connect_integration.go`.
Conda and Lambda integrations already manage the integration lifecycle from registration, setup, to completion. This PR makes the same pattern available for all integrations. This means that when we register an integration:
1) A "exec_state" key in the pending state is always written to the initial `integration` table entry.
2) This `integration` table entry will be updated to the appropriate terminal state. For all non-conda and non-lambda integrations, this happens synchronously.
The `list_integrations` endpoint now returns the execution state instead of the validated flag. The validated column is **dropped** from the integrations table, as it is …
=> Track the execution state of every integration connection on the backend

src/dockerfiles/spark/spark-py310-env.dockerfile, src/dockerfiles/spark/spark-py37-env.dockerfile, src/dockerfiles/spark/spark-py38-env.dockerfile, src/dockerfiles/spark/spark-py39-env.dockerfile
This PR fixes dkr build on spark based on https://stackoverflow.com/questions/55386246/w-failed-to-fetch-http-deb-debian-org-debian-dists-jessie-updates-main-binary
Successfully build spark dkr imgs in 0.2.12 release
=> Fix spark dkr build

sdk/aqueduct/integrations/connect_config.py
Adds DatabricksConfig to connect_config
Eng-2862
=> Adds DatabricksConfig to connect_config

src/golang/lib/container_registry/ecr.go
=> Small improvement to ECR error surfacing

src/llm/MANIFEST.in
This is required to build the LLM PyPI package.
=> Add MANIFEST file to LLM python package

src/ui/common/src/components/integrations/dialogs/gcsDialog.tsx
=> ENG-2895 Updates link for GCS storage documentation in GCS dialog.

src/golang/lib/engine/aq_engine.go
Remove log line that seem to be generating lot of noise
ENG-2900
=> Remove additional log line

sdk/aqueduct/resources/ecr.py
=> Minor update to the ECR docstring

sdk/aqueduct/backend/api_client.py, sdk/aqueduct/resources/ecr.py
=> Make the error message of initializing Aqueduct client more informative

src/golang/lib/job/k8s.go
https://linear.app/aqueducthq/issue/ENG-2916/fix-nil-pointer-bug-for-k8s
=> Fix nil pointer bug for k8s

scripts/generate_docs.sh, scripts/release/doc.sh, sdk/aqueduct/llm_wrapper.py
=> Fixes doc generation script

src/ui/common/src/components/cards/GettingStartedTutorial.tsx
This Pr fixes a broken link on the getting started tutorial.
ENG-2960
N/A
=> ENG_2960: Fix broken documentation link for Aqueduct demo resource.

src/ui/common/src/components/workflows/workflowStatus.tsx
It now looks like this  - is this better?
tbh I don't know if I love this look - if we're worried about it looking too much like a list, maybe something more neutral could work? https://fontawesome.com/icons/bars-staggered?f=classic&s=solid
ENG-2880
=> Update the workflow "No Run" logo

src/ui/common/src/components/integrations/dialogs/snowflakeDialog.tsx
=> Fix Snowflake save missing schema bug

src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx
This PR fixes issues with form validation on the S3 add resource dialog.
ENG-2979
=> ENG-2979 S3 Dialog Validation Fixes

.github/workflows/spark-periodic-tests.yml
Changes schedule for spark periodic tests to 9PM on Thursdays.
=> Changes schedule for spark periodic tests

src/golang/lib/response/node.go, src/ui/common/src/components/pages/workflow/id/hook.ts, src/ui/common/src/handlers/responses/node.ts
This PR implements two hooks to use workflow node / results.
=> Implement node hooks

src/ui/common/src/components/AnnouncementBanner/AnnouncementBanner.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx
Fixes error message that appears when showing the version announcement banner.
ENG-2812
=> ENG-2812: Announcement Banner Error Fixes

src/ui/common/src/handlers/AqueductApi.ts
This PR fixes a missing import in UI build
Confirmed that local UI build passes. The GH action should also pass
=> Fix missing imports in UI build

sdk/aqueduct/client.py
Mainly for backward compatibility. Using them shows Deprecated warning to end user.
ENG-3007
=> Add back optional flow_id and flow_name arguments

src/ui/common/src/components/integrations/dialogs/onDemandKubernetesDialog.tsx
=> Fix on-demand k8s connection bug

src/ui/common/src/components/pages/workflows/components/ResourceItem.tsx
Should have been a part of https://github.com/aqueducthq/aqueduct/pull/1361 but I forgot to push before merging.
=> Padding Tweak

manual_qa_tests/README.md, manual_qa_tests/workflows/check_status_test.py, manual_qa_tests/workflows/succeed_complex.py
Update manual UI QA checklist to use right terminology / reflect current UI.
=> Update Manual UI QA checklist

src/terraform/eks/main.tf
This is required as certain variables are deprecated in 3.0
=> Update EKS VPC Terraform module version number

src/ui/common/src/components/AnnouncementBanner/AnnouncementBanner.tsx, src/ui/common/src/components/pages/account/AccountPage.tsx, src/ui/common/src/components/pages/resource/id/index.tsx, src/ui/common/src/components/pages/resources/index.tsx, src/ui/common/src/components/pages/workflow/id/hook.ts, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/pages/workflows/index.tsx, src/ui/common/src/components/resources/dialogs/deleteResourceDialog.tsx, src/ui/common/src/components/resources/dialogs/dialog.tsx, src/ui/common/src/components/resources/dialogs/gcsDialog.tsx, src/ui/common/src/components/resources/dialogs/onDemandKubernetesDialog.tsx, src/ui/common/src/components/resources/dialogs/s3Dialog.tsx, src/ui/common/src/components/resources/dialogs/schema.ts, src/ui/common/src/components/tables/PaginatedSearchTable.tsx, src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/handlers/AqueductApi.ts, src/ui/common/src/utils/resources.ts
This PR fixes all lint warnings in UI by following warning contents.
ENG-3062
Verified that all lint warnings are resolved, together with a full manual QA focused on changed components. This is done over a full build.
=> Fix all lint warnings in UI

manual_qa_tests/README.md
=> Update manual QA guide with gke

CHANGELOG.md
As title; this PR updates release note to include links to GKE and GAR docs
=> Update release note to include links to GKE and GAR docs

scripts/generate_docs.sh
=> Update doc generation script to account for GAR

examples/system-tests/Simple_Model_Medium_Data_K8s.ipynb
This PR adds the notebook used for system testing 2 - medium data and simple model on a k8s compute resource.
ENG 2826
=> Adds sytem test 2 notebook

src/ui/app/.eslintignore, src/ui/app/.eslintrc.js, src/ui/app/index.tsx, src/ui/app/package.json, src/ui/common/.eslintignore, src/ui/common/package.json
This PR fixes an issue where the frontend linters fail to run.
ENG-3034
https://www.loom.com/share/a0a7b4ab5eb6456baee05c2a881d5230
=> ENG-3034 Frontend Linter Fixes

.github/workflows/mypy.yml, integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/shared/flow_helpers.py, sdk/aqueduct/artifacts/base_artifact.py, sdk/aqueduct/artifacts/bool_artifact.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/artifacts/numeric_artifact.py, sdk/aqueduct/artifacts/table_artifact.py, sdk/aqueduct/backend/api_client.py, sdk/aqueduct/flow_run.py, sdk/requirements/python-3-10.txt, sdk/requirements/python-3-7.txt, sdk/requirements/python-3-8.txt, sdk/requirements/python-3-9.txt
This PR adds integration tests for disabling snapshots. To properly examine the exec states of flows, we also added exec state tracking for all artifact types.
Also included a fix for `ENG-3103` to fix datetime parsing
ENG-3000 ENG-3103
* Integration tests on this PR should succeed, implying new feature working and no regressions.
* Manual UI testing covered in previous PR #1401
* Tested on a cleaner build to verify requirements.txt are updated (install only using `pip install .` and `install_local` script, without install from a pypi package).
=> [5/n] Adds integration test for disabling snapshots

src/terraform/gke/nodepools.tf, src/terraform/gke/plugin.tf, src/terraform/gke/variables.tf, src/terraform/gke/versions.tf, src/ui/common/src/components/resources/dialogs/gcpDialog.tsx, src/ui/common/src/utils/resources.ts
1. Add new resource providers
2. Add additional oauth scope to fetch nvidia drivers
3. Add the latest nvidia COS driver plugin terraform script
ENG-3066
- [x ] I have performed a self-review of my code.
- [x ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x ] I have run the integration tests locally and they are passing.
- [x ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x ] All features on the UI continue to work correctly.
=> Enable on demand GPU scheduling support for GKE
