src/python/bin/aqueduct
This is the first step towards supporting versions. This PR allows users to retrieve the package version via `aqueduct version`. In a subsequent PR, we will code this version information to `~/.aqueduct` and add support for version update.
=> Add package version command to cli

src/python/bin/aqueduct
This PR enables our users to update OSS package versions. When they perform `pip3 install --upgrade aqueduct-ml`, if we have a newer version, then when they subsequently execute `aqueduct server` or `aqueduct ui`, we will detect that their current version is older than the package version and fetch the latest binaries from S3. Their existing database state will be untouched.
Made a dummy version 0.0.2 and verified that the version upgrading from 0.0.1 to 0.0.2 worked.
=> Implement support for version upgrade

README.md, src/python/bin/aqueduct
Now the users can use `aqueduct start [--expose=<PUBLIC_IP>]` to launch both the server and the UI. When pressing `CTRL-C`, we will terminate both processes as below:
```
Terminating Aqueduct service...
Aqueduct service successfully terminated.
```
At the beginning of running `aqueduct start`, we also show:
```
***************************************************
Your API Key: xxx
Visit this address in a web browser to see your workflows
Web UI Address: http://<IP>:3000
Use this address and to connect your Aqueduct SDK Client 
Server Address: http://<IP>:8080
***************************************************
```
=> Enable single CLI command to launch both the server and the UI

src/Makefile
The `-lean` Make option does the trick. We should use this flag to compile the binaries and upload them to S3.
=> Add compile option to remove symbol tables, debugging info, and path info from the Go binary

sdk/aqueduct/metric_artifact.py
We switch the messaging of lower and upper bounds to be correct to what they are actually doing
=> Fix check strings for lower/upper bound on metric

integration_tests/sdk/flow_test.py, scripts/install_local.py, src/golang/cmd/executor/main.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/lib/job/config.go, src/golang/lib/job/job.go, src/golang/lib/job/poll.go, src/golang/lib/job/process.go, src/python/bin/aqueduct
As we discussed, any jobs being run by the executor should be piped to a file in the `server/logs` directory. We do this by setting the output of the `logrus` library. The naming rules are currently:
- `logs/default`: all logs that were generated in the brief period of time before we are able to redirect logs to the correct file are here.
- `logs/<job name>`: all logs that are generated by the workflow job. Includes all the function/extract/etc logs.
- `logs/Workflow Job Retention`: all logs generated by the long-running workflow job retention job.
There are two bugs I found related to the returned execution status of a job in poll() being SUCCESS when it should have been FAIL. This seems like issues since we rely on poll() within our orchestration engine. …
=> Pipe executor logs to the logs directory

src/golang/cmd/executor/main.go, src/golang/lib/job/process.go
Don't compare with `os.ErrNotExist`, use `os.IsNotExist()` instead.
=> Fix bug where the logs directory does not exist so executor always fails

src/python/bin/aqueduct
After doing some research, it seems there's some weird Mac signature issue when we try to `cp` over the new binary to try to replace the old one, according to [here](https://apple.stackexchange.com/questions/258623/how-to-fix-killed-9-error-in-mac-os). The issue seems to be that when we copy over the binary, the content got updated but the Mac signature is still using the cached old signature, and due to the mismatch, Mac immediately kills the binary when starting...
=> Wipe binaries in `bin` before copying over newer versions to avoid mismatching Mac signature

.github/workflows/integration-tests.yml, .github/workflows/run-notebooks.yml
Trying to estimate how long to sleep to wait for server initialization is brittle and broke again today. We should instead just poll for the server at localhost:8080 until a connection can be established.
Taken from the top comment here: https://unix.stackexchange.com/questions/5277/how-do-i-tell-a-script-to-wait-for-a-process-to-start-accepting-requests-on-a-po
Tested and it works.
=> Fix inflexible sleep in favor of a poll for Github Action integration tests

sdk/aqueduct/dag.py, sdk/aqueduct/flow.py
Parameter operators are completely unnecessary nodes. We can just remove param operators after calculating the node positions for them. Does this look weird? I kinda like how the artifacts are all in the same column.
=> Remove parameter operator from being displayed in _show_dag()

src/golang/cmd/migrator/migrator/create.go
This PR:
- Fixes the `migrator` `create` command by correcting the base filepath to all of the schema change versions.
- Tested this out my creating a new schema change template and verified that it was generated correctly in the correct location.
=> Fixes schema migrator create cmd

src/ui/app/index.tsx, src/ui/common/package-lock.json, src/ui/common/package.json, src/ui/common/src/components/layouts/codeblock.tsx, src/ui/common/src/components/pages/AccountPage.tsx, src/ui/common/src/components/pages/workflows/index.tsx, src/ui/common/src/index.tsx
The account page is back now :)
Had to update it to fit with the new UI structure. Here it is before: https://github.com/aqueducthq/aqueduct/blob/085cdf6692dc8419377a658e059dad2c243efd53/src/ui/app/pages/account.tsx
Side note: One thing I noticed was that my browser didn't reflect my UI changes until I switched to incognito and restarted the gateway so if you run into the issue you may want to try that.
=> eng-1247 account page

integration_tests/sdk/sql_integration_test.py, src/python/aqueduct_executor/operators/connectors/tabular/relational.py
This PR is the first attempt to create syntax sugar for sql queries, the implementation is the following:
1. In `Aqueduct_executor`, for all database connectors that take in SQL syntax, we process the query when we want to extract a dataframe from the database. If there exist `"{{today}}"` in the SQL syntax, we will replace the substring with today'date. 
2. I have created a test under `sql_integration_test.py`. I search on the dataset `hotel_reviews` based on `review_date = {{today}}`. It should return an empty dataframe. However, this test is not conclusive since there are many input that can result in empty dataframe.
Would appreciate some suggestions~!
=> Eng 1086 create syntax sugar for sql queries

src/golang/cmd/migrator/migrator/register.go, src/golang/cmd/migrator/versions/000009_metadata_interface_backfill/main.go, src/golang/cmd/migrator/versions/000009_metadata_interface_backfill/queries.go, src/golang/cmd/migrator/versions/000009_metadata_interface_backfill/types.go, src/python/bin/aqueduct
We have schema changes to the artifact result when we are introducing system metrics in this PR:
https://github.com/aqueducthq/aqueduct/pull/100
this PR has the migrator to ensure that old flows dont break in the system.
=> Add migrator for system metrics schema change

sdk/aqueduct/api_client.py
If you user creates a client with an "http(s)://" prefix, we should respect their decision instead of trying to infer what protocol they want to use.
Previous behavior stays the same, its just in the above case where we no longer throw an error, as long as we can establish a connection to the backend.
=> Handle cases where the user supplies an http(s) prefix when initializing the client

src/ui/common/src/components/notifications/NotificationListItem.tsx
- clean up the messages displayed in the notification list item card
=> UI-1035-reduce text in notification

sdk/aqueduct/aqueduct_client.py
There was an extraneous print (L51) with a typo (`exec` instead of `exc`) -- funnily enough, this failed when I was generating API docs with `pydoc-markdown`. 
This PR removes the extraneous print statement.
=> Fixes error handling in get_apikey

src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/notifications/NotificationsPopover.tsx
- hide success notification from user
- https://linear.app/aqueducthq/issue/ENG-1200/disable-success-notifications
- tested using local dev mode
=> UI-finished implementation to hide success notification

src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/notifications/NotificationsPopover.tsx, src/ui/common/src/components/pages/data/index.tsx
This PR fixes data page search bar bugs where we show 'undefined: undefined' if user types something random. We also slightly improve the UX by showing all tables if the user cancels search.
Resolves: https://linear.app/aqueducthq/issue/ENG-1229/fix-bug-where-typing-blah-in-the-data-search-box-and-pressing-return
Demo:
https://www.loom.com/share/86c2f81fef85409fb50558b0d6f1398d
=> [UI] Fix data page search bar bug showing 'undefined' and not cancel properly

integration_tests/sdk/param_test.py, integration_tests/sdk/sql_integration_test.py, sdk/aqueduct/dag.py, sdk/aqueduct/integrations/sql_integration.py, sdk/aqueduct/table_artifact.py, src/python/aqueduct_executor/operators/connectors/tabular/extract.py, src/python/aqueduct_executor/operators/function_executor/execute_function.py
These are the API changes:
```
table_name_param = client.create_param("table_name", default="hotel_reviews")
sql_artifact = db.sql("select * from {table_name}")
sql_artifact.get(parameters={"table_name": "other table"})
```
The parameter name can have underscores and dashes, but cannot have spaces. If there are spaces, it won't get picked up as a tag and the query will likely fail.
ENG-1258
- [ x] If this is a new feature, I have added unit tests and integration tests.
- [ x ] I have manually run the integration tests and they are passing.
=> [SDK] Adds parameterization to SQL queries

.github/workflows/integration-tests.yml, .github/workflows/pre-merge-ci.yml
This PR adds ability to trigger integration tests via the label "run_integration_test". After changing repo settings this will block PRs from being merged unless the test passes.
https://linear.app/aqueducthq/issue/ENG-1024/block-prs-from-merging-unless-integration-tests-pass
=> Creates pre-merge integration test check

src/python/aqueduct_executor/operators/utils/utils.py
See task for bug description. I've checked that running a basic flow now no longer produces this error.
[1292
](https://linear.app/aqueducthq/issue/ENG-1292/fix-a-bug-where-we-have-artifact-serialization-error-in-workflow)
- [x ] I have performed a self-review of my code.
- [ N/A] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ N/A] If this is a new feature, I have added unit tests and integration tests.
- [ x] I have manually run the integration tests and they are passing.
- [ N/A] All features on the UI continue to work correctly.
=> Fix bug where the schema metadata was written improperly

src/golang/cmd/server/server/aqueduct_server.go, src/python/bin/aqueduct
Previously, we were using relative path (`.`) to serve UI files, after passing in `ui_directory` as `cwd` from the aqueduct CLI. This is a bit brittle and caused some confusion around why are we passing in the `ui_directory` as `cwd` when executing the server binary. This PR fixes this by using the absolute path instead, so that we no longer need to configure `ui_directory` as `cwd`.
=> Use absolute file path to serve UI files

src/ui/common/src/components/integrations/dialogs/IntegrationFileUploadField.tsx, src/ui/common/src/components/integrations/dialogs/bigqueryDialog.tsx, src/ui/common/src/components/integrations/dialogs/csvDialog.tsx
When the user uploads a file that isn't a csv, it breaks because we try to preview it as a csv. This means it breaks for the bigquery integration file upload.
After this fix, manually tested that I can successfully upload the file to the bigquery integration popup modal and create a bigquery integration.
ENG-1281
- [ N/A] If this is a new feature, I have added unit tests and integration tests.
- Not a new feature.
- [ N/A] I have manually run the integration tests and they are passing.
- I don't think we have integration tests for UI.
=> ENG-1281 Fix IntegrationFileUploadField to be usable for csv & other filetypes

.github/workflows/integration-tests.yml, .github/workflows/pre-merge-ci.yml
The slack reporting is unnecessary since integration tests are blocking PRs now. I don't have to go tell people to roll things back anymore.
The push and comment triggers should also be unnecessary now right?
- [x ] I have performed a self-review of my code.
- [ N/A] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ N/A] If this is a new feature, I have added unit tests and integration tests.
- [ N/A] I have manually run the integration tests and they are passing.
- [ N/A] All features on the UI continue to work correctly.
=> Remove unnecessary triggers and reporting from integration tests

.github/workflows/skip-pre-merge-ci.yml
Earlier, skip-integrations-test.yml didn't exist on the main branch so the workflow would fail. Now that it exists on main + skipping tests on changes that only touch .github/workflows/*, we no longer need to have these follow up PRs. (If users want to test their changes on GA, they can manually trigger the runs via the Action tab + particular branch)
1306
=> Follows up 1306 to change workflow branch to main

src/golang/cmd/server/request/parameters.go, src/ui/common/src/components/workflows/workflowHeader.tsx, src/ui/common/src/utils/operators.ts
Builds a "parameters" form into the workflow trigger dialog. These text fields have the parameter default value as the placeholder. Any value in entered in here will be packaged up and sent to `refresh_workflow` to trigger the flow with the new parameters. Text fields left empty are ignored. Text fields that have a non-jsonable string in them will be rejected with an appropriate error message.
Demo Vid:
https://www.loom.com/share/c61881ab0f3448a0890b40bccae42519
ENG-1295
- [N/A ] If this is a new feature, I have added unit tests and integration tests.
- [ x] All features on the UI continue to work correctly.
=> [UI] Add ability to trigger a flow with custom parameters

.github/pull_request_template.md, .github/workflows/pre-merge-ci.yml, .github/workflows/skip-pre-merge-ci.yml
The [path/ignore path conditions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths) used by Github Actions are very broad for our use cases. Often times users will update documentation in the same PR that they make code changes in, and this will trigger both the testing/skip-testing workflows. The best way to configure this is to leave it up to the developer to decide when to run/skip the tests. The new behavior is as follows:
- Add `run_integration_test` label: Runs integration tests
- Add `skip_integration_test` label: Skips integration tests (Should be used when changes are ONLY documentation/UI)
One of these labels must be added in order to merge the PR.
https://linear.app/aqueducthq/issue/ENG-1304/fix-issues-with-integration …
=> Improves usage of ci tests by not relying on github paths

scripts/install_local.py, src/python/aqueduct_executor/operators/utils/utils.py
If the value can be converted to a float, it is accepted.
Supports int64, float, int, string (e.g. "4" but not "4d"), ...
Input:
```
import aqueduct
from aqueduct import op, metric
import pandas as pd
import numpy as np
client = aqueduct.Client("VFEH916W2OMLQTB5YDCIRJ34N7S8PUXG", "3.142.105.48:8080")
warehouse = client.integration(name="aqueduct_demo")
customers_table = warehouse.sql(query="SELECT * FROM customers;")
for v in [64, 64., 64.0, 0x64, 0b010, 
np.int64(64), np.int32(32), np.float64(64), np.float32(32),
"64", "64.", "64.5", "64.d"]:
try:
@metric()
def met(df):
return v
metrics = met(customers_table)
out = metrics.get()
print(v, "(", type(v), ")", "-->", out, "(", type(out), ")")
except:
print(v, "(", type(v), ")", "cannot be converted")
```
Output:
```
64 ( <class 'int'> ) --> …
```
=> Fix restrictive metric typing

src/ui/Makefile, src/ui/app/.env.sagemaker, src/ui/app/index.tsx, src/ui/app/package.json, src/ui/common/src/components/cards/GettingStartedTutorial.tsx, src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/connectedIntegrations.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/notifications/NotificationListItem.tsx, src/ui/common/src/components/pages/LoginPage.tsx, src/ui/common/src/components/workflows/workflowCard.tsx, src/ui/common/src/utils/getPathPrefix.ts
SageMaker doesn't expose ports directly through it's Notebook instances but rather puts them behind `proxy/{portNumber}`. In order to make our UI work on SageMaker, we need to: 1) change our static assets to load from `/proxy/8080/dist` rather than just `/dist`; 2) change all of our API calls and links within the UI to have `/proxy/8080` prepended.
1. In order to do 1, I modified `package.json` to use the `--dist-dir` and the `--public-url` flags. `npm run build` generates out default build (now in `dist/default`), and `npm run build-sagemaker` generates a SageMaker-specific build in (in `dist/sagemaker`).
2. In order to do 2, we added `getPathPrefix` helper that looks at `window.location.pathname` and uses a regex to determine whether we're running behind `/proxy/{portNumber}` or not -- …
=> ENG 1297: Set up build to package UI for sagemaker

sdk/aqueduct/integrations/sql_integration.py
This PR seeks to add a describe() functionality for relational integrations. The existing relational integration has a describe() method that prints out the integration information. Thereafter, I add a display of list of table inside the integration. The table name displayed is limited to the number of display from df.head() because if there are large number of tables, this method is not user friendly.
https://linear.app/aqueducthq/issue/ENG-868/add-describe-method-to-each-of-the-relational-integrations
=> ENG-868-Add `describe()` method to each of the relational integrations.

scripts/install_local.py, src/golang/cmd/migrator/migrator/register.go, src/golang/cmd/migrator/versions/000004_storage_interface_backfill/queries.go, src/golang/cmd/migrator/versions/000010_add_exec_state_column/down_postgres.go, src/golang/cmd/migrator/versions/000010_add_exec_state_column/main.go, src/golang/cmd/migrator/versions/000010_add_exec_state_column/up_postgres.go, src/golang/cmd/migrator/versions/000010_add_exec_state_column/up_sqlite.go, src/golang/cmd/migrator/versions/000011_exec_state_column_backfill/main.go, src/golang/cmd/migrator/versions/000011_exec_state_column_backfill/queries.go, src/golang/cmd/migrator/versions/000011_exec_state_column_backfill/types.go, src/golang/cmd/migrator/versions/000012_drop_metadata_column/down_postgres.go, src/golang/cmd/migrator/versions/000012_drop_metadata_column/main.go, src/golang/cmd/migrator/versions/000012_drop_metadata_column/up_postgres.go, src/golang/cmd/migrator/versions/000012_drop_metadata_column/up_sqlite.go, src/golang/lib/collections/operator_result/constants.go, src/golang/lib/collections/operator_result/operator_result.go, src/python/setup.py
This PR adds schema migration for `operator_result` table by changing `metadata` to `exec_state` based on changes introduced in #159 . We added 3 new versions to add new col, backfill, and drop old col. After this change the schema will become 12.
ENG-1249
=> Schema migration for changing 'metadata' to 'exec_state'

scripts/run_linters.py
This PR fixes run linter scripts where we should do `exec_command(["cmd", "--args", "val"])` instead of `exec_command(["cmd", "--args val"])`, where in the 2nd case the entire '--args val' will be treated as one string. This may has something to do with either OS or python version.
Also fixed mypy issue to run on specific module, otherwise we would encounter multiple-module errors which might be caused by the existence of egg.
Run the linter successfully on #144 
=> Fixes run linter scripts when running commands

src/golang/cmd/server/server/aqueduct_server.go, src/golang/config/config.go, src/golang/lib/collections/shared/storage.go, src/golang/lib/storage/file.go, src/golang/lib/storage/s3.go, src/golang/lib/storage/s3_test.go, src/python/aqueduct_executor/operators/utils/storage/config.py, src/python/aqueduct_executor/operators/utils/storage/s3.py
This PR changes the Aqueduct server start behavior to use the storage config found in the config.yml file, instead of defaulting to file storage each time.
It also refactors all access to S3 for storage to use the AWS credentials provided by the user. Previously, the access was performed without explicitly specifying where to find the AWS credentials.
ENG 1311
See #193 for demo
=> Refactors S3 storage implementation to use user provided credentials

src/golang/cmd/server/server/aqueduct_server.go, src/golang/config/config.go, src/golang/lib/collections/shared/storage.go, src/golang/lib/storage/file.go, src/golang/lib/storage/s3.go, src/golang/lib/storage/s3_test.go, src/python/aqueduct_executor/operators/utils/storage/config.py, src/python/aqueduct_executor/operators/utils/storage/s3.py, src/python/bin/aqueduct
This PR adds an `aqueduct storage` command to the CLI. This is necessary to allow users to modify the storage config globally for all subsequently created workflows. This will not affect existing workflows. Users will be able to access artifacts from previous workflows even after they modify the storage config.
ENG 1310 
Part 1: https://www.loom.com/share/58b40eb6a4504aa6902ddfa32badce0d (End the video after 5:15, there is an error, so the next video picks up from this spot)
Part 2: https://www.loom.com/share/edaec344a5c34bc9966b00c01124231e
=> Adds aqueduct storage command to CLI

src/python/aqueduct_executor/operators/connectors/tabular/config.py, src/python/aqueduct_executor/operators/connectors/tabular/extract.py
This PR adds a couple of default values that are necessary for backwards compatibility for workflows that were registered before we added these fields.
=> Adds default values for Python connectors for Postgres.port and Extract.query_is_usable

sdk/aqueduct/integrations/s3_integration.py, sdk/aqueduct/operators.py, sdk/aqueduct/tests/serialization_test.py, src/python/aqueduct_executor/operators/connectors/tabular/config.py, src/python/aqueduct_executor/operators/connectors/tabular/main.py, src/python/aqueduct_executor/operators/connectors/tabular/s3.py, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx, src/ui/common/src/utils/integrations.ts
This PR enables user's S3 integration to extract multiple files in a concatenated form, so when they have multiple files they don't need to define a bunch of extract operators. The expected value for the SDK API is commented inline. The PR also adds an authentication step when the user registers an S3 integration by trying to list the files in the bucket.
https://www.loom.com/share/b692707630a44f3bbf0ebfa107e6334b
=> Support multi file inputs from S3 integration

src/ui/common/src/components/integrations/cards/airflowCard.tsx, src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/dialogs/airflowDialog.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/utils/integrations.ts
This PR:
- Adds support for connecting to Airflow via the UI.
- It uses the same process for connecting to Airflow as the data integrations. We can create separation between data integrations and backend integrations in follow on work.
ENG-1275
For demo see #141
=> Adds UI for connecting Airflow integration

integration_tests/sdk/error_handling_test.py, sdk/aqueduct/api_client.py, sdk/aqueduct/flow.py, sdk/aqueduct/flow_run.py
For every preview execution error, we return the phrase "See console logs for error message" in the error. It makes more sense to put the logs directly in the error message itself.
Examples:
ENG-1396
- [x ] I have performed a self-review of my code.
- [x ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [N/A ] If this is a new feature, I have added unit tests and integration tests.
- [ x] I have run the integration tests locally and they are passing.
- [ x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ N/A] All features on the UI continue to work correctly.
- `run_integration_test`: Runs …
=> [Quality of life] Print the error context in the preview execution exception

src/python/aqueduct_executor/operators/function_executor/get_extract_path.py, src/python/aqueduct_executor/start-function-executor.sh, temp.sh
start_function_executor.sh errors on OSX operating systems because of the "${OP_PATH::-3}" expression. 
We remove the need for this expression, and thus allow for cleanup of these expanded functions on Macs.
ENG-1375
=> Cleanup unzipped function directories properly on OSX

src/golang/lib/job/spec.go
This PR fixes an issue where workflow name / type is gone when running in executor. The root cause is that the `baseSpec` is private, and we are using json serialization for logging, which hides these fields. So the fix is simply make the object public.
ENG-1215
Verified type and name appears in log:
```
time=2022-07-21T18:22:44Z level=info msg={"type":"workflow","name":"test_correct_2","workflow_id":"08ae08e6-58a1-455c-a1b2-2ca02ca02353","github_manager":{},"parameters":{},"ExecutorConfig":{"metadata":{"type":"sqlite","sqlite":{"file":"/home/ubuntu/.aqueduct/server/db/aqueduct.db"}},"vault":{"directory":"/home/ubuntu/.aqueduct/server/vault","encryption_key":"H8FIU2QCDL0A3STRV5WZGPN9Y6BME7JX"},"job_manager":{"binary_dir":"/home/ubuntu/.aqueduct/server/bin","logs_dir":"","python_executor_pa …
```
=> Fix logging for workflow name / type in executor code.

integration_tests/sdk/checks_test.py, integration_tests/sdk/utils.py, sdk/aqueduct/responses.py, src/golang/lib/collections/shared/types.go, src/golang/lib/job/spec.go, src/golang/lib/workflow/artifact/artifact.go, src/golang/lib/workflow/operator/check.go, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/operators/function_executor/spec.py, src/python/aqueduct_executor/operators/utils/execution.py
This is the revisit of previously closed. https://github.com/aqueducthq/aqueduct/pull/195
This is built on top of the orchestration refactor.
The approach:
- Because we want to keep our python operators generic, I introduced the concept of "Blacklisted outputs" on the function spec. For all operators except blocking checks, this field will be None. For blocking checks, we want to blacklist the output "False". That is to say, if an output matches an entry in this list, we will fail the entire workflow.
- On the read side, the python operator level is too generic to provide a very user friendly tip. So instead, it provides a generic one that is then overwritten at the `checkOp.GetExecState()` level with more specific user friendly context.
ENG-1265
- [ x] I have created a descriptive PR …
=> Add ability to distinguish between warnings and error level checks on backend

src/Makefile, src/golang/lib/collections/tests/main_test.go, src/golang/lib/collections/tests/operator_test.go
This PR fixes our database integration tests. One of the operator test cases was failing because we did not update the `ID` of the expected operator.
It also splits up the `make test-database` into a couple rules, so that devs can test against specific database types. More documentation for testing can be found [here](https://www.notion.so/aqueducthq/Database-Testing-df6e7c2521cb4205a20e6de22b576c45).
ENG 1427
I tested this PR by running `make test-db-sqlite`.
=> Eng 1427 fix database integration tests

src/python/aqueduct_executor/operators/connectors/tabular/s3.py
Previously we were doing a list operation to check if the user has access to the bucket, which can be very costly if the bucket has lots of files. This low-overhead approach is borrowed from [here](https://stackoverflow.com/a/49817544) and I verified that it works.
=> Switch to a low-overhead way of authenticating S3 integration

scripts/install_local.py
Fixes UI build error in install_local.py caused by running npm in sudo
This error happens because the version that npm uses when run is different when you run in sudo mode.
See this command as an example:
```
ubuntu@ip-172-31-41-179:~/repos/aqueduct$ npm --version
8.5.0
ubuntu@ip-172-31-41-179:~/repos/aqueduct$ sudo npm --version
6.14.4
```
ENG-1430
https://linear.app/aqueducthq/issue/ENG-1430/fix-ui-build-error
See below for demo of successful output:
```
ubuntu@ip-172-31-41-179:~/repos/aqueduct$ python3 scripts/install_local.py 
Updating Golang binaries...
INFO[0000] Executing query: SELECT version,dirty,name FROM schema_version …
```
=> ENG-1430 Fix UI Build in install_local.py

src/ui/common/src/components/pages/AccountPage.tsx, src/ui/common/src/components/pages/HomePage.tsx, src/ui/common/src/components/pages/data/index.tsx, src/ui/common/src/components/pages/integration/id/index.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/components/pages/types.d.ts, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/pages/workflows/index.tsx
Refactors sidebar and layout handling to allow sidebar layout to be passed into page components.
Resolves: https://linear.app/aqueducthq/issue/ENG-1407/refactor-sidebar-and-layout-handling
=> ENG-1407 Allow UI page sidebars to be passed in as prop.

src/golang/lib/workflow/operator/check.go, src/python/aqueduct_executor/operators/utils/execution.py
Instead of doing something too complicated in `get_operator_result`, lets just alter the error message in the python operator. It should make it slightly easier for you to refactor the check operator.
Demo:
=> Fix error message for error severity check not passing

scripts/install_local.py
modify install_local scripts to automatically select files to put inside .aqueduct/ui 
In next week, will select another component to replace react-code-block to avoid all those issues. 
=> modify install_local scripts to only select necessary UI files 

src/golang/lib/backend/airflow/config.go, src/ui/common/src/components/integrations/cards/airflowCard.tsx, src/ui/common/src/components/integrations/dialogs/airflowDialog.tsx, src/ui/common/src/utils/integrations.ts
This PR adds some UI changes to require the user to specify the AWS credentials location and profile name for the S3 bucket that will be used by the Airflow server they are connecting. This is necessary for the Airflow runtime to communicate asynchronously with the Aqueduct server via S3, since that is where operator metadata and artifact content is stored.
ENG 1435
Demo: https://www.loom.com/share/2a96172a005047f3b8d1bc590fb89367
=> Allows user to specify S3 credentials for Airflow integration

scripts/install_local.py, src/golang/cmd/migrator/migrator/register.go, src/golang/cmd/migrator/versions/000013_add_workflow_dag_engine_config/down_postgres.go, src/golang/cmd/migrator/versions/000013_add_workflow_dag_engine_config/main.go, src/golang/cmd/migrator/versions/000013_add_workflow_dag_engine_config/types.go, src/golang/cmd/migrator/versions/000013_add_workflow_dag_engine_config/up_postgres.go, src/golang/cmd/migrator/versions/000013_add_workflow_dag_engine_config/up_sqlite.go, src/golang/cmd/server/request/dag.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/lib/collections/shared/engine.go, src/golang/lib/collections/tests/main_test.go, src/golang/lib/collections/tests/workflow_dag_test.go, src/golang/lib/collections/workflow_dag/constants.go, src/golang/lib/collections/workflow_dag/sqlite.go, src/golang/lib/collections/workflow_dag/standard.go, src/golang/lib/collections/workflow_dag/workflow_dag.go, src/golang/lib/workflow/utils/utils.go, src/python/bin/aqueduct
This PR adds an `engine_config` column to the `workflow_dag` table. This is necessary to store important information for mapping an Aqueduct workflow to the native concepts of the 3rd-party engine the workflow is set to run on, such as Airflow.
ENG-1243
I tested this schema change by creating a workflow (and workflow_dag) before applying the schema change. Then, I applied the schema change and confirmed that the new column was created. After this, I tested that the `WorkflowDagReader` was able to successfully read the `engine_config` column.
=> Adds workflow_dag engine_config column

src/python/aqueduct_executor/operators/function_executor/execute.py
This PR fixes the bug that we couldn't execute imported functions like the following:
```
from external import func
@aqueduct.op(file_dependencies=["external.py"])
def copy_field(df):
return func(df)
copy_field(inputs).get()
```
Specifically, we fixed the `sys.path` which we used to import user functions to make sure the dependencies also properly appears in `sys.path`. We also added a few debugging logs for the extracted operator files.
ENG-1451
Verified the code snippet above works after fix
- [na] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [na] If this is a new feature, I have added unit tests and integration tests.
- [na] (in-PR tests should be sufficient) I have run the integration tests locally and they are passing.
- [na] …
=> Fix a bug where we couldn't execute imported functions

src/ui/common/src/components/integrations/dialogs/csvDialog.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/pages/integration/id/index.tsx
The CSV upload modal had a few bugs that made it confusing to use. This PR fixes the following:
* ENG-1412: The modal was way too narrow, so you couldn't see any of the data you uploaded.
* ENG-1413: The modal didn't close after upload, so it seemed like nothing actually uploaded.
* ENG-1414: The preview showed an ID column that wasn't included in the original data.
There's still a tiny bug where I'd like to have the dialog expand to show the full 5 rows, but I couldn't fix that quickly.
See above
- `run_integration_test`: Runs integration …
=> [ENG-1412, 1413, 1414] Fixes CSV upload modal bugs

src/ui/app/package-lock.json, src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json, src/ui/common/src/components/integrations/cards/sqlServerCard.tsx, src/ui/common/src/index.tsx
This PR moves the SqlServer integration card over to @aqueducthq/common.
https://linear.app/aqueducthq/issue/ENG-1418/export-spiraldemocard-and-sqlservercard-from-aqueducthqcommon-library
=> ENG- 1418 export spiraldemocard and sqlservercard

src/python/aqueduct_executor/operators/function_executor/spec.py
The script `get_extract_path` cannot print out anything except the function extract path. Once it prints something out, the FUNCTION_EXTRACT_PATH gets all messed up and we're unable to do requirements installation or cleanup.
Will be adding test coverage for this as part of https://linear.app/aqueducthq/issue/ENG-1217/infer-requirements-without-pipreqsnb-in-sdk
=> [Bugfix] Fix bug where requirements.txt was not installing

src/ui/app/package.json, src/ui/common/package.json, src/ui/common/src/components/layouts/sidebar/AqueductSidebar.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/ReactFlowCanvas.tsx
This PR fixes two bugs around the layout of the ReactFlow canvas and the bottom sidesheet:
* The fix for ENG-1354 is around calling `fitView` at the right time. Because we were previously calling `fitView` on `componentDidMount`, it didn't actually work on the first load because the nodes and edges were loaded in _after_ the component was mounted. This PR changes the `fitView` effect so that it also is called when the node/edge positions are changed, which causes the view to be fit correctly (after a small lag) on first load.
* This PR also fixes ENG-1415 simplifies absolute positioning of the bottom side sheet so that it properly aligns with the ReactFlow viewport (see screenshot below): 
(Ignore the miscolored artifacts; that's because my local backend isn't updated.)
- [N/A] If this is …
=> [ENG-1354, 1415] Fixes bottom sidesheet and ReactFlow alignment issues

.github/workflows/integration-tests.yml
Updates integration test timeout to wait 5 minutes instead of 1 for server to start.
Hoping that this will remedy failing test here: https://github.com/aqueducthq/aqueduct/runs/7566139306?check_suite_focus=true
per @kenxu95 's suggestion.
=> Update Integration Test Timeout

sdk/aqueduct/aqueduct_client.py
When running on the same machine as the Aqueduct server, the user shouldn't need to provide the API key or address of the server explicitly -- we should be able to automatically detect it. This PR makes the `api_key` and `aqueduct_address` arguments optional on the API client. 
ENG-1459
=> [ENG-1459] Removes need to provide API key, server address when running locally

src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/utils/integrations.ts
When the user tries to connect an integration but the Aqueduct server is off, they get a very confusing error message that simply says "Failed to fetch". This PR fixes that by explicitly checking when a fetch failed to happen. It also improves the integration connection modal by making it wider, so that stack traces display more legibly.
This PR also fixes a tiny bug that I found where the list of integrations on the UI isn't refreshed after you connect a new integration. Turns out that was already logged as ENG-1450, but I only discovered that afterwards. 🙂
ENG-1362, ENG-1450
- …
=> [ENG-1362, 1450] Fixes bug where user got unhelpful error message when Aqueduct server was off

.github/workflows/integration-tests.yml, sdk/aqueduct/api_client.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/dag.py, sdk/aqueduct/flow.py, sdk/aqueduct/logger.py, sdk/aqueduct/tests/serialization_test.py, sdk/aqueduct/utils.py
Main purpose was to address https://linear.app/aqueducthq/issue/ENG-1403/remove-warnings-about-overriding-an-existing-operator. I also took the chance to clean up our logging a little bit:
- `Logger.logger.info(...)` seemed pretty redundant. I don't see why we can't use `logger().info(..)`. We're not supposed to call functions from the root logger like `logging.info(..)`.
- Instead of adding a verbose flag, we can have the user configure the client with the correct logging level, the same way Ray does it https://docs.ray.io/en/latest/ray-core/package-ref.html#ray-remote. 
I'm also fine with us exposing a `verbose` argument and mapping that to `log.INFO`, whereas it's regularly `log.WARNING`. What do you think? I'd like to also be able to set log level to be DEBUG whenever I want, and I …
=> Improve and logging in our SDK

src/python/bin/aqueduct, src/ui/common/src/components/pages/LoginPage.tsx
This PR makes 3 quality of life improvements to the Aqueduct CLI:
* ENG-1219: To make launching Aqueduct simpler, this PR does two things -- (1) on the login page of the UI, it looks for a query parameter called `apiKey` and if such a parameter exists, attempts to auto-login with it; (2) uses the `webbrowser` package to attempt to open a browser tab with the Aqueduct UI and with the API key included as a query parameter.
* ENG-1365: Adds download bars to all of the file downloads -- especially since the server binaries are large-ish, this gives the user a sense that progress is being made.
* ENG-1440: On EC2 instances, if the `--expose` flag is passed in, we attempt to autodetect the public IP address of the machine and autopopulate it into our welcome message; if none is found, we …
=> [ENG-1219, 1365, 1440] Improves usability of Aqueduct CLI

sdk/aqueduct/integrations/s3_integration.py, src/python/bin/aqueduct
Since we don't have any S3 tests now, I tested manually with a notebook and verified that the user can now input upper case or lower case strings and as long as it matches one of the enums, things work.
=> Make the format parameter type to the `s3.file` API string instead of enum

src/ui/common/package-lock.json, src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/utils/getPathPrefix.ts
Updates menuSidebar to use react-router linking. Pages no longer need to trigger a browser refresh when transitioning from one page to another and now load instantly.
Loom Demo: https://www.loom.com/share/c0312eda788f4e3d96cc36d677cd12ad
N/A
=> Use React Router Linking on MenuSidebar

src/ui/common/src/components/integrations/cards/card.tsx
This PR fixes the issue where we didn't apply the right link for cards in `data/` page.
ENG-1503
Before: https://www.loom.com/share/f9b4a7957c84445aabb8fb129de1e24d
After: https://www.loom.com/share/2b5a51b53f71432cb364de4fcd979aa0
=> Fix links in data page cards

src/ui/common/src/components/workflows/nodes/BaseNode.styles.tsx, src/ui/common/src/components/workflows/nodes/Node.tsx
fixes the unusually looking metric operator node image
Before change:
After change:
=> [UI] fix metric operator node image being super small

src/ui/common/src/reducers/nodeSelection.ts, src/ui/common/src/utils/operators.ts
fix the odd look for system metric operator node
Before:
After:
=> [UI] fix the odd look for system metric operator node

sdk/aqueduct/decorator.py
This PR fix the naming change of to_operator(), which makes the integration test currently broke.
https://linear.app/aqueducthq/issue/ENG-1318/allow-users-to-create-operators-from-existing-functions
=> Update to_operator() naming

integration_tests/sdk/operator_test.py, sdk/aqueduct/utils.py
If these are also included in the uploaded requirements.txt, installing them spews the following error message (although things still work):
```
Stderr:
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/Users/kennethxu/work/aqueduct/src/python/setup.py", line 9, in <module>
long_description = open(readme_path).read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kennethxu/work/aqueduct/../../README.md'
[end of output]
```
Filtering them out fixes this
- `skip_integration_test`: Skips integration tests (Should be used …
=> Remove aqueduct-ml/sdk from any requirements.txt

src/golang/cmd/server/handler/archive_notification.go, src/golang/cmd/server/handler/get_artifact_result.go, src/golang/cmd/server/handler/get_node_positions.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/handler/list_notifications.go, src/golang/cmd/server/main.go, src/golang/cmd/server/middleware/authentication/authentication.go, src/golang/cmd/server/request/payload.go, src/golang/cmd/server/response/response.go, src/golang/go.mod, src/golang/go.sum, src/golang/lib/database/stmt_preparers/util.go, src/golang/lib/logging/response.go, src/python/bin/aqueduct
This PR adds `verbose` option to our CLI. By default, `verbose` is set to `False`, meaning that only error logs are shown in the terminal. If the user sets `verbose` to `True`, then all logs are shown in the terminal.
Regardless of `verbose`, all logs are always stored into a log file. The log file is managed by a library that performs log rotation to prevent the logs from growing infinitely.
The above only applies to logging done via `logrus`. Our route logger doesn't have this flexibility, so all REST events are still logged in the terminal regardless of `verbose`.
Without `verbose`:
With `verbose`:
=> Add `verbose` mode so that by default only error logs are shown in the terminal

src/python/aqueduct_executor/operators/function_executor/prune_requirements.py, src/python/aqueduct_executor/start-function-executor.sh
Currently we infer requirements by running `pip freeze` locally  and install these requirements using `pip install -r`. This will make `pip install` to install the long `pip freeze` list which is very slow, introducing lots of latencies. This PR fixes this issue by manually compare the `requirement.txt` with a local `pip freeze` list, then we only install the mismatched packages.
ENG-1528
Operator preview go down from 1min+ to ~6s. Also verified latency reduction for execution
```
2022/08/09 03:47:58 "POST http://localhost:8080/api/preview HTTP/1.1" from 127.0.0.1:34690 - 200 110119B in 1.099682551s
2022/08/09 03:48:01 "POST http://localhost:8080/api/preview HTTP/1.1" from 127.0.0.1:34692 - 200 345718B in 2.196247097s
2022/08/09 03:48:08 "POST http://localhost:8080/api/preview HTTP/1.1" …
```
=> Fix latency issue introduced by long requirement.txt

src/ui/common/src/components/hooks/useAqueductConsts.ts
This PR sets a default value to use for SERVER_ADDRESS if there is no environment variable present when running parcel builds.
https://linear.app/aqueducthq/issue/ENG-1533/set-default-value-for-server-address
=> ENG-1533 Frontend: Use default value for SERVER_ADDRESS

src/ui/common/src/components/integrations/dialogs/dialog.tsx
Remove system prefixes from the integration name because it confuses users
This demo shows two integrations: Snowflake & Postgres. The integration name field has no prefix anymore and upon filling out all the required fields, the confirm button is enabled.
https://user-images.githubusercontent.com/30596854/183711139-926d0625-b098-421d-9ebb-fa21c29f42c7.mov
ENG-1252
=> Remove system name prefix from newly connected integrations

src/python/bin/aqueduct
This PR just removes the `aqueduct server` and `aqueduct ui` that we introduced in v0.0.1 and deprecated in v0.0.2. afaik, no one is on those versions anymore, so I am removing them from the CLI.
ENG-1524
=> Removes deprecated commands from CLI

integration_tests/sdk/utils.py
=> Avoid spamming the server when reads when waiting for flows to complete in tests

src/golang/lib/engine/aq_engine.go, src/golang/lib/workflow/operator/base.go, src/golang/lib/workflow/operator/check.go, src/golang/lib/workflow/operator/extract.go, src/golang/lib/workflow/operator/function.go, src/golang/lib/workflow/operator/load.go, src/golang/lib/workflow/operator/metric.go, src/golang/lib/workflow/operator/operator.go, src/golang/lib/workflow/operator/param.go, src/golang/lib/workflow/operator/system_metric.go, src/golang/lib/workflow/operator/utils.go
Moves the `JobSpec()` then `JobManger.Launch()` pattern into `Operator.Launch()`. This sets us up for the caching layer to be inserted within `Operator.Launch()`.
`JobSpec()` will need to stay around because Airflow uses it.
ENG-1497
=> Allow operators to start their own execution if necessary

src/ui/common/src/components/integrations/dialogs/IntegrationFileUploadField.tsx, src/ui/common/src/components/integrations/dialogs/bigqueryDialog.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx, src/ui/common/src/components/integrations/integrationObjectList.tsx, src/ui/common/src/utils/integrations.ts
This PR adds UI support for connecting to S3 using credential files. We support both specifying a path and read in live, and uploading the content of the file. The main changes involves adding UI components so that the users could select how to auth, and fill those new fields properly.
ENG-1436 ENG-1437 ENG-1438
Demo: https://www.loom.com/share/259db52d71074a0fad74603996fae7cb
The alert box is too close to detail card. Also fixed:
=> Eng 1438 UI support to connect to S3 using credential file.

src/golang/lib/engine/engine.go, src/golang/lib/job/process.go, src/golang/lib/workflow/operator/connector/auth/static_config.go, src/python/aqueduct_executor/operators/connectors/tabular/config.py, src/python/aqueduct_executor/operators/connectors/tabular/s3.py, src/ui/common/src/components/integrations/dialogs/IntegrationFileUploadField.tsx, src/ui/common/src/components/integrations/dialogs/bigqueryDialog.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx, src/ui/common/src/components/integrations/integrationObjectList.tsx, src/ui/common/src/utils/integrations.ts
This PR adds backend supports for using credentials file to connect S3 integrations, which should also enable SSO support. Specifically, we:
* Added a type for s3 config together with 3 types, to distinguish manual inputs, file path (read file content directly at runtime), and file uploads. Added additional config fields to specify file path, content, and aws profile to use.
* Updated python executor to use `boto3` API to read credential file together with the profile name. Per description in https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html , this exact API supports both regular access key credentials and SSO.
* Due to restrictions of boto3 API, in upload mode we would have to explicitly store uploaded credential content in a temp file. We updated working dir …
=> Eng 1438 backend support for connecting to s3 using credential file

src/ui/common/src/components/integrations/dialogs/addTableDialog.tsx, src/ui/common/src/utils/integrations.ts
Previously, when we got an error message from the backend, we were parsing it with `response.text()` rather than `response.json()`, so the error message body was wrapped in many `title: {some blob}` layers. Fixing that parsing allows us to return the actual error message from the backend and then display it in a `<pre>` block here: 
ENG-1504
=> [ENG-1504] Fixes bug where CSV upload modal errors were incorrectly displayed

src/python/aqueduct_executor/operators/utils/execution.py
The context currently only displays the trace but not the actual exception class & message which is not as helpful as it could be. Since the stack trace in Python shows both, this results in the trace looking cut-off. I believe this is the same issue encountered in https://github.com/aqueducthq/aqueduct/pull/248 being described in ENG-1445.
Before:
```
File "/Users/eunice/Desktop/aqueduct/src/python/aqueduct_executor/operators/connectors/tabular/relational.py", line 47, in delete
sql_table = metadata.tables[table]
```
After:
```
File "/Users/eunice/Desktop/aqueduct/src/python/aqueduct_executor/operators/connectors/tabular/relational.py", line 47, in delete
sql_table = metadata.tables[table]
KeyError: 'delete_table'
```
ENG-1445
- [x ] I have created a descriptive PR title. The PR title …
=> Add exception to traceback message

src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/utils/workflows.tsx
Add stack traces / error messages to the failed object deletions as suggested in https://github.com/aqueducthq/aqueduct/pull/290.
BE Component https://github.com/aqueducthq/aqueduct/pull/340
UI Component https://github.com/aqueducthq/aqueduct/pull/341
SDK Component https://github.com/aqueducthq/aqueduct/pull/342
Shows error with failed deletion:
0:17 - Deletes 5 tables and shows the error along with failed deletion. Scrolls because there are too many results on the screen.
https://user-images.githubusercontent.com/30596854/184263334-07a1d32d-e9a9-489b-9b92-caba2044f804.mov
ENG 1370
ENG 1507
- `skip_integration_test`: Skips integration tests (Should be used when …
=> Eng 1507 add stack trace to failed object deletion in workflow deletion [UI/3]

integration_tests/sdk/delete_workflow_test.py, integration_tests/sdk/utils.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/responses.py, src/ui/common/src/components/workflows/WorkflowSettings.tsx
Add stack traces / error messages to the failed object deletions as suggested in https://github.com/aqueducthq/aqueduct/pull/290.
BE Component https://github.com/aqueducthq/aqueduct/pull/340
UI Component https://github.com/aqueducthq/aqueduct/pull/341
SDK Component https://github.com/aqueducthq/aqueduct/pull/342
If we fail to delete the objects, an exception is thrown with this message (taken from the integration pytest):
```
E           Exception: Failed to delete 1 saved objects.
E           Failures
E           [aqueduct_demo] delete_table
E           >   File "/Users/eunice/Desktop/aqueduct/src/python/aqueduct_executor/operators/connectors/tabular/relational.py", line 47, in delete
E           >       sql_table = metadata.tables[table]
E           Sorry, we've run into an unexpected …
```
=> Eng 1507 add stack trace to failed object deletion in workflow deletion [SDK/3]

src/python/aqueduct_executor/operators/connectors/tabular/s3.py, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx
This PR tries to fix SSO credentials handling. The python fix is regardless of product decision we land on, that we should use `session.resource()` from an authorized session since `credentials.access_key credentials.secret_key` cannot be explicitly used.
The product decision is an open question. It seems that SSO credentials are distributed in `config` file together with a file in `sso/cache`:
I've verified that auth doesn't work if only `config` file is provided. I haven't verified if we can just use either file in `sso/cache` and do some brittle auth process based on https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso.html . Even if this approach work, the UI will look messy as we need to add additional switches to support file path / uploads for SSO which is …
=> Fix handling SSO credentials

src/ui/common/src/components/cards/GettingStartedTutorial.tsx, src/ui/common/src/components/layouts/default.tsx
As discussed on Linear, this PR makes a number of small fixes to the welcome page:
* Makes all the blocks even width. 
* Removes the light grey background adds dark blue borders to each block, combined with a light blue hover background.
* Adds Aqueduct logo to the top of the page.
* Cleans up getting started instructions to match the latest information.
* Animates wave emoji on page load and when hovering over the welcome block.
https://user-images.githubusercontent.com/867892/184013864-69cd5881-51b0-4361-ba63-4f191d42b150.mov
ENG-1328
- `skip_integration_test`: Skips integration tests …
=> [ENG-1328] Cleans up welcome page

src/ui/common/src/components/workflows/workflowHeader.tsx
Previously, the only indication we had that a workflow was running was if you looked at the version selector dropdown. This was pretty subtle for new users, so this PR brings back the `Status` component in the `WorkflowHeader` to show the status of the workflow clearly.
=> [ENG-1534] Adds status to WorkflowHeader

.github/workflows/integration-tests.yml, .github/workflows/mypy.yml, .github/workflows/periodic-integration-tests.yml, .github/workflows/run-notebooks.yml, .github/workflows/unit-tests-sdk.yml, examples/run_notebook.py, integration_tests/sdk/requirements_tests/requirements_test.py, scripts/install_local.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/utils.py, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/operators/function_executor/prune_requirements.py, src/python/aqueduct_executor/start-function-executor.sh
- The cause of the bug is that the server was unable to install the modules in requirement.txt because it is looking for local files that did not exist on that machine from in-place installs (`pip(3) install (-e) . `).
- Warn user if they have any local installs.
- Update blacklisted list to include aqueduct_sdk / aqueduct_ml (the format aqueduct_xyz would be in the case of installing with `pip3 install -e .`)
Checked with a requirements.txt that included modules in the following formats:
```
appnope==0.1.3
aqueduct-ml @ file:///Users/eunice/Desktop/aqueduct/src/python
-e git+ssh://git@github.com/aqueducthq/aqueduct.git@4990b42ed9fcc6758bc7b6fc2d7d475a5b1d7477#egg=aqueduct_sdk&subdirectory=sdk
```
Eng 1557
- [N/A] I have included a small demo of the changes. For the UI, this would be a …
=> Eng 1557 Fix bug where the required Python packages on the client machine aren't automatically installed on the server

src/ui/common/src/components/hooks/useAqueductConsts.ts
Reverts aqueducthq/aqueduct#316
Defaulting to localhost won't work when the client and the server aren't running on the same machine, so we want to keep the behavior of when no server address is specified, we will use `/`.
=> Revert "ENG-1533 Frontend: Use default value for SERVER_ADDRESS"

src/ui/common/src/components/pages/workflow/id/index.tsx
Fix bug where exported CSV files only have underscores on first occurrence of space character.
Before:
"My Multi Word Workflow" exports as "My_Multi Word Workflow.csv"
After:
"My Multi Word Workflow" exports as: "My_Multi_Word_Workflow.csv"
https://linear.app/aqueducthq/issue/ENG-1566/bug-filenames-only-have-underscores-on-first-occurrence-of-when
=> ENG-1566 Export CSV file name fix

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, integration_tests/sdk/utils.py, src/golang/lib/database/scanner.go, src/golang/lib/database/sqlite.go
This PR makes two tweaks that seem like they fix our concurrency issue. Both have to do with the sqlite configuration:
1) Uses write-ahead logging, so that writers and readers don't grab the same database locks.
2) Adds a busy-timeout of 3 seconds, meaning that we will wait up to 3 seconds for a lock before giving up. This should eliminate `database is locked` errors. If they come back, we should consider bumping this timeout.
This saves a couple minutes each run. Interestingly enough, it seems like concurrency at 5 with python 3.9 and 3.10 is significantly slower :/ Otherwise we would be halving our runtime.
I've run the tests 20 times with concurrency 5 on github actions, and all except 1 pass, which is much better than before. I will continue to see if I can repro that issue, but in …
=> Introduce concurrency back into integration tests 

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml
Some new issues popped up with the `test_delete_workflow_saved_*` tests. Will revert concurrency in pre-merge integration tests until I can figure out why.
=> Revert integration test concurrency back to 1

src/golang/cmd/server/main.go
https://aqueducthq.slack.com/archives/C01KF131001/p1660603243468799
It's actually kinda useful, might take some getting used to tho. At least its gated behind `verbose`.
=> Log server filepaths and line numbers in verbose mode

src/python/aqueduct_executor/operators/utils/storage/s3.py
Adds check for AWS env vars in aqueduct_executor. We will need these env vars when using the K8s integration.
https://linear.app/aqueducthq/issue/ENG-1567/add-env-variable-check-in-aqueduct-executor
=> Adds check for AWS env vars in aqueduct_executor

integration_tests/sdk/utils.py, src/golang/lib/database/scanner.go, src/golang/lib/database/sqlite.go, src/golang/lib/database/standard.go
It turns out the culprit to these "Unable to create workflow" transient errors boils down to the fact that we had concurrent write transactions that started with DEFERRED locking. With DEFERRED locking, the transaction only grabs locks when it has to, so when you have two concurrent transactions that both first grab read locks, and then upgrade to write locks, this upgrade fails with a SQLITE_BUSY error, and completely bypasses our `_busy_timeout` value.
The solution in the PR is to start everything as a write transaction, so any conflicting writes will wait for a `_busy_timeout` time before giving up. As long as `_busy_timeout` is set high enough, and our transactions are fast enough, this particular issue should no longer be a problem.
ENG-1468
- `run_integration_test`: Runs integration …
=> Fix sqlite transactional concurrency issue around SQLITE_BUSY and SQLITE_LOCKED

.github/workflows/integration-tests.yml, integration_tests/sdk/utils.py, src/golang/lib/database/scanner.go, src/golang/lib/database/sqlite.go, src/golang/lib/database/standard.go
Reenabling concurrency in all our testing after https://github.com/aqueducthq/aqueduct/pull/369 merges.
ENG-1468
=> Add concurrency back to our pre-merge integration tests

src/golang/lib/storage/s3.go, src/golang/lib/storage/s3_test.go, src/python/aqueduct_executor/operators/utils/storage/s3.py
This PR fixes a bug with how the S3 path is parsed in both the `Go` and `Python` execution. Since we allow users to provide a nested S3 path in the form of `s3://bucket/with/subdir`, we need to be able to deal with paths that look like the former and as well as something as simple as `s3://bucket`. There was currently a problem with parsing `s3://bucket`, where an extra `/` was being added to the key before any lookups were being performed.
ENG 1554
=> Fixes S3 path parsing bug

src/python/aqueduct_executor/operators/utils/storage/s3.py, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx, src/ui/common/src/utils/integrations.ts
This PR allows a user to set the S3 integration they are adding to be the new Aqueduct storage layer. This is only allowed for S3 at the moment. This is to make it easier for users to avoid having to provide the same AWS credentials in multiple places.
DEMO: https://www.loom.com/share/d3ec5d47a8994b71a68c04fed81fa6f5
ENG 1552
=> Allows users to set S3 as storage layer when connecting integration

src/ui/common/src/utils/integrations.ts
=> Make k8s inactive on UI

sdk/aqueduct/__init__.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/config.py, sdk/aqueduct/dag.py, sdk/aqueduct/enums.py, sdk/aqueduct/flow.py, sdk/aqueduct/integrations/k8s_integration.py, sdk/aqueduct/utils.py
Adds option to publish a k8s workflow in SDK 
```
from aqueduct import FlowConfig
k8s_integration = client.integration("k8s_integration")
no_input_flow_k8s = client.publish_flow(
name = "No input k8s", 
artifacts = [output],
config = FlowConfig(engine=k8s_integration),
)
```
Eng-1555
=> Implements option to publish a k8s workflow in SDK

.github/workflows/run-notebooks.yml, integration_tests/notebook/imported_function.ipynb, integration_tests/notebook/util.py, integration_tests/notebook/util_dependency.ipynb, sdk/aqueduct/tests/decorator_test.py, sdk/aqueduct/utils.py
This PR adds an integration test case for an operator with a file dependency named `util.py`. 
It also removes `aqueduct_utils.py` from the SDK reserved files list, since it is not used internally anymore.
ENG 1103
=> Adds notebook integration test for util.py file dependency

src/golang/lib/engine/utils.go, src/golang/lib/job/k8s.go, src/golang/lib/job/spec.go
This PR adds support for a k8s engine to access GCS credentials. We pass in the credentials as an environment variable. We wait until the job is launched to set this env var, because storage configs can be modified by users now.
ENG 1600
=> Adds support for k8s engines to access gcs credentials

src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/gcsDialog.tsx
This PR links documentation for connecting to Google Cloud Storage. It also sets the GCS integration to be the metadata store by default, since that is the only use case for now. 
ENG 1605
=> Adds documentation link for connecting Google Cloud Storage integration

src/golang/lib/job/constants.go
This PR fixes the docker images to version 0.0.12.
=> Fixes docker images to version 0.0.12 for k8s

scripts/run_linters.py
This PR fixes the linter script for the UI. It was failing previously during `npm install` without the `--force` option.
=> Fixes linting script for UI

src/ui/common/src/components/notifications/NotificationsPopover.tsx
This PR removes the team pane from notifications, since the community edition does not have a concept of teams.
ENG 1574
=> Removes team pane from notifications

src/ui/common/src/components/notifications/NotificationsPopover.tsx
This PR consolidates the notification panes into a single box since we no longer have a distinction between org notifications and user notifications.
ENG 1610
Demo: https://www.loom.com/share/849d3456fce0434d813dcda9b716c757
=> Consolidates the notifications panes into a single box

src/golang/cmd/server/handler/get_artifact_result.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/server/handlers.go
This PR refactors the get operator results and get artifact results routes to use the workflow dag result status when the operator or artifact result object does not exist. 
This issue also fixes the UI bug [here](https://linear.app/aqueducthq/issue/ENG-1611/fix-ui-bug-where-ui-crashes-if-user-clicks-into-an-artifact-or), since now the operator and artifact results will assume the status of the overall workflow dag result if no records are found in the database.
ENG 1611
DEMO: https://www.loom.com/share/16ae1226c0604fbca7429bc9fe2f728c
=> Returns workflow dag result status for unavailable operator and artifact results

src/golang/cmd/server/handler/get_artifact_result.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/workflow/dag/workflow_dag.go, src/golang/lib/workflow/utils/utils.go
This PR refactors the `Engine.ExecuteWorkflow` implementation to capture as many errors as possible when persisting the DAG status to the WorkflowDagResult table.
Essentially, the more code we have BEFORE we initialize a new row in the WorkflowDagResult table, the more errors we will be unable to capture and update the WorkflowDagResult row accordingly. In order to do this, we want to minimize the code inside of `ExecuteWorkflow` BEFORE the WorkflowDagResult row is created, because as soon as this record is created, we can add a `deferred` function that captures the state of the DAG run and updates the WorkflowDagResult record accordingly.
This PR gets rid of the `PersistResults` method from the `WorkflowDag` interface, because this logic is now handled directly by the `ExecuteWorkflow` …
=> Refactors execute workflow to improve persisting DAG status

src/ui/common/src/components/integrations/dialogs/deleteIntegrationDialog.tsx, src/ui/common/src/components/integrations/options.tsx
If the user cannot delete a workflow, bring up a popup with an explanation rather than disable the button.
https://user-images.githubusercontent.com/30596854/187237386-ca5ebb5f-66c3-46f2-94a0-c7bedad4ef7f.mov
ENG-1607
=> ENG-1607 add integration unable to delete popup

.github/workflows/periodic-integration-tests.yml, integration_tests/sdk/local_test.py, integration_tests/sdk/param_test.py, regression_tests/tests/workflow_comparer.py
See title. The tests were failing consistently. Let's get alerted next time this happens. I believe this is only  an issue with the periodic tests because they use the `--complex_models` flag.
=> Fix periodic integration tests and add slack reporting on failure

src/golang/lib/collections/shared/storage.go, src/python/aqueduct_executor/operators/utils/storage/config.py, src/python/aqueduct_executor/operators/utils/storage/s3.py
This PR adds the AWS keys as fields for S3 StorageConfig. This is necessary for the AWS Lambda engine work, since we'll be passing in S3 credentials as part of the StorageConfig instead of passing them in as environment variables as we do in the k8s engine case.
NOTE: There will have to be a follow on PR once the Lambda jobManager has been implemented that actually sets the new AWS key fields before the StorageConfig is serialized as part of the JobSpec.
ENG 1621
=> Adds AWS keys to S3 storage config

.github/workflows/periodic-integration-tests.yml
Looks like one of the recent tests timed out. Lets set it to the same timeout as our pre-merge integration tests.
=> Bump the timeout for periodic integration tests

sdk/aqueduct/responses.py
Update the BE response class to add `created_at` as a field to the workflow objects list so we can signify to the user which update mode is the active one (since the active workflow is currently the latest workflow).
ENG-1509
BE: https://github.com/aqueducthq/aqueduct/pull/410
SDK: https://github.com/aqueducthq/aqueduct/pull/411
UI: https://github.com/aqueducthq/aqueduct/pull/412
=> [SDK/3] ENG-1509 Add flag to Update Mode indicating which is currently used

sdk/aqueduct/artifacts/numeric_artifact.py, sdk/aqueduct/artifacts/table_artifact.py, sdk/aqueduct/decorator.py, sdk/aqueduct/tests/decorator_test.py, sdk/aqueduct/utils.py, src/golang/cmd/server/handler/export_function.go, src/golang/cmd/server/request/export.go, src/golang/cmd/server/routes/headers.go, src/ui/common/src/utils/operators.ts
This PR refactors how we capture and return exported functions to the user.
The code is captured when a workflow is created by adding a special read-only file called `source.py`. This file isn't used as part of any operator execution, but it is just there as a user-friendly copy of the code that has been serialized into `model.pkl`.
ENG 1190
UPDATE:
The files now look like
Demo: https://www.loom.com/share/a553c71f4d9b4216a7c2b22db30073ad
=> Makes exported function code more user-friendly to read

sdk/aqueduct/responses.py, src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/utils/workflows.tsx
Signify to the user which update mode is the active one (since the active workflow is currently the latest workflow).
ENG-1509
BE: https://github.com/aqueducthq/aqueduct/pull/410
SDK: https://github.com/aqueducthq/aqueduct/pull/411
UI: https://github.com/aqueducthq/aqueduct/pull/412
=> [UI/3] ENG-1509 Add flag to Update Mode indicating which is currently used

src/golang/lib/collections/operator/function/version.go, src/golang/lib/collections/operator/function/version_test.go, src/golang/lib/job/process.go
This PR extracts the Python version from a serialized function. This is necessary for Lambda support so the correct Lambda function can be invoked.
ENG 1619
=> Extracts Python version from serialized function

integration_tests/sdk/list_workflow_objects_test.py, integration_tests/sdk/load_test.py, sdk/aqueduct/artifacts/base_artifact.py, sdk/aqueduct/dag.py
This looks a lot better. Different artifacts that write to the same integration will have the same loader name, and that's ok.
Previously, it was:
=> Give sane names to load operators

src/python/aqueduct_executor/operators/utils/storage/s3.py
We want to check if the spec contains the AWS credentials first. In the lambda case they populate the AWS credentials with the lambda executor role's credentials, which may not have permissions to write to S3.
=> Reorder AWS credentials check for S3 storage

src/golang/cmd/migrator/migrator/create.go, src/golang/cmd/server/handler/export_function.go, src/golang/config/config.go, src/golang/lib/collections/operator/function/version.go, src/golang/lib/storage/gcs.go, src/golang/lib/vault/file.go, src/golang/lib/workflow/operator/connector/auth/oauth_config.go
This PR fixes errors from running go linter related to using the deprecated io/ioutil package. Noticed these when running lint on my M1 mac.
Console output here:
```
(aqueduct-env) ➜  aqueduct git:(main) ✗ python3 scripts/run_linters.py --golang
Linting Go code...
lib/workflow/operator/connector/auth/oauth_config.go:7:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
"io/ioutil"
^
Traceback (most recent call last):
File "/Users/andre/Documents/Code/aqueduct/scripts/run_linters.py", line 117, in <module>
lint_golang(cwd)
File …
```
=> ENG-1644 Fix go lint errors related to using deprecated io/ioutil package.

src/ui/common/src/reducers/nodeSelection.ts, src/ui/common/src/utils/artifacts.ts
Running the following code and immediately looking at the UI:
```
@op
def basic_op(df):
import time
time.sleep(10)
return df
sql = db.sql("SELECT * from hotel_reviews")
output = basic_op.lazy(sql)
```
The lazily executed one is no longer weird like in the current version
ENG-1631
=> [UI] Create mapping from untyped artifact to generic

sdk/aqueduct/enums.py, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/lib/collections/shared/types.go, src/golang/lib/collections/tests/workflow_test.go, src/golang/lib/collections/workflow/noop.go, src/golang/lib/collections/workflow/postgres.go, src/golang/lib/collections/workflow/sqlite.go, src/golang/lib/collections/workflow/workflow.go, src/ui/common/src/components/workflows/workflowCard.tsx, src/ui/common/src/components/workflows/workflowStatus.tsx, src/ui/common/src/utils/shared.ts
This PR adds frontend and backend changes to show users workflows without any runs. This is important as it at least gives the user some confidence that Aqueduct registered their workflow.
ENG 1485
DEMO: https://www.loom.com/share/bc3d00dfda7e43fe9609c07eaba4f632
=> Shows users workflows without any runs

integration_tests/sdk/flow_test.py, integration_tests/sdk/param_test.py, sdk/aqueduct/api_client.py, sdk/aqueduct/artifacts/bool_artifact.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/artifacts/numeric_artifact.py, sdk/aqueduct/artifacts/param_artifact.py, sdk/aqueduct/artifacts/table_artifact.py, sdk/aqueduct/artifacts/utils.py, sdk/aqueduct/decorator.py, sdk/aqueduct/error.py, sdk/aqueduct/flow.py, sdk/aqueduct/flow_run.py
Loads the artifact contents into `flow_run.artifact(..)`, so that any .get() on a published artifact will not need to make any preview request. This preserves the old snapshotted data of the previous run.
Added some guardrails:
- If you attempt to materialize a published artifact who's operator has failed, you'll get an `ArtifactNeverComputedException` exception. You are still able to describe the artifact in most cases though.
- If you attempt to materialize a published artifact with parameters, you'll get a NotImplementedError. We may want to support this in the future.
ENG-1638
=> Fix bug where artifact from published flow uses latest data

src/ui/common/src/reducers/workflow.ts
We were just missing a simple guard to check if there were any saved objects. 🙂
ENG-1579
=> ENG-1579: Fix bug where browser console throws error when there is no load operator

src/ui/common/src/components/integrations/integrationObjectList.tsx, src/ui/common/src/components/integrations/integrationObjectPreview.tsx, src/ui/common/src/components/integrations/operatorsOnIntegration.tsx, src/ui/common/src/components/pages/integration/id/index.tsx, src/ui/common/src/styles/theme/theme.tsx
Previously, we had a slightly opaque way of showing previews of the data tables on the integration details page behind a select menu. It was not clear to users what that menu was for or what would happen if you selected something. 
This PR slightly redesigns that interface to instead show an accordion, in which clicking on each item shows you a preview of the data. You can see a side-by-side comparison in the demo video below.
[Demo video](https://www.loom.com/share/b914d0f0507a457fbabb657b4ef13ccf)
ENG-1399
- `skip_integration_test`: Skips integration tests (Should be used when changes are …
=> ENG-1399: Redesigns integration details page to explicitly show DB tables

src/ui/app/index.tsx
This PR disables strict mode on the UI to get rid of some console errors that were appearing related to findDOMNode, a deprecated function that is used by react-virtualized.
https://www.loom.com/share/88cccf7503644fc1834e90455576e21c
https://linear.app/aqueducthq/issue/ENG-1653/remove-strict-mode-on-react-to-get-rid-of-finddomnode-console-error
=> ENG-1653 Disable strict mode on frontend

src/ui/common/src/components/integrations/dialogs/airflowDialog.tsx
This PR fixes a bug where the frontend was not sending the Airflow host as part of a connect integration request when the protocol (e.g. HTTP, HTTPS) is not provided by the user.
ENG 1682
TEST: Tested this by successfully connecting an Airflow integration.
=> Fixes Airflow connect integration request

integration_tests/sdk/no_return_test.py, integration_tests/sdk/type_enforcement_test.py, sdk/aqueduct/api_client.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/flow_run.py, sdk/aqueduct/responses.py
Previously, if an artifact's content is `None`, when we retrieve it from `flow_run.artifact()` and call `get()`, it'll mistakenly complain the artifact wasn't computed successfully. This PR fixes this by distinguishing the two cases via an extra execution status argument passed into `GenericArtifact`.
=> Fix bug where artifact with None value doesn't work with flow_run.artifact() api

src/python/aqueduct_executor/operators/airflow/dag.template, src/python/aqueduct_executor/operators/airflow/execute.py
This PR fixes the Airflow schedule set for workflows that are only invoked manually. Airflow requires the schedule to be `None` (without any quotes) if the schedule should be none. Otherwise, the schedule should be a cron string.
ENG 1486
Confirmed that the Airflow DAG file has the correct schedule generated:
```
with DAG(
dag_id='testingaflow2',
default_args={
'retries': 0,
},
start_date=datetime(2022, 1, 1, 1),
schedule_interval=None,
catchup=False,
tags=['aqueduct'],
) as dag:
```
=> Fixes Airflow schedule string for manual workflows

src/golang/lib/collections/integration/constants.go, src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/cards/kubernetesDetailCard.tsx, src/ui/common/src/components/integrations/cards/lambdaDetailCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/integrationObjectList.tsx
This PR is to update integration detail page for both k8s and lambda. With both k8s and lambda don't have data display feature, we will remove it in the detail integration page. Instead, we add more integration configuration information on the page.
**After:**
This PR also fix a issue in branch eng-1516 where we need to have a "break" for each switch case.
ENG-1642
https://linear.app/aqueducthq/issue/ENG-1642/update-integration-detail-ui-for-kubernetes-and-lambda
=> Update integration detail UI for Kubernetes and Lambda

integration_tests/sdk/param_test.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/decorator.py, sdk/aqueduct/parameter_utils.py
When non-artifact types are passed to decorated functions, we attempt to implicitly create a parameter with name being the function argument's name and default value being the user-specified value. We print out a warning when this happens. If there is already an operator with the same name in the dag, we throw an error.
=> Implicitly create parameter when passing non artifact to decorated functions

src/ui/common/src/components/workflows/StatusBar.tsx
This PR adds padding and margin right to workflow status bar list items so that they aren't cut off by right scroll bar.
https://linear.app/aqueducthq/issue/ENG-1691/add-padding-to-right-side-of-workflow-status-bar-list-items
=> ENG-1691 Add Padding Right to Workflow Status Bar List Items

sdk/aqueduct/artifacts/base_artifact.py
Change "Load" terminology to "Save to" on UI.
Before:
After:
https://linear.app/aqueducthq/issue/ENG-1442/rename-load-to-save-in-ui-and-sdk
=> Changes operator name from load -> save to

src/python/aqueduct_executor/operators/airflow/dag.template
This PR changes the Airflow DAG template to use the PythonVirtualenv operator instead of the Python operator. This makes sure that the user does not need to install `aqueduct-ml` and other pkg dependencies on their Airflow server directly.
ENG 1484
- Confirmed that the new Airflow DAG template successfully ran
=> Changes Airflow DAG template to use Python virtual env

src/dockerfiles/Makefile, src/dockerfiles/lambda/app.py, src/dockerfiles/lambda/connectors/athena.dockerfile, src/dockerfiles/lambda/connectors/bigquery.dockerfile, src/dockerfiles/lambda/connectors/data.py, src/dockerfiles/lambda/connectors/postgres.dockerfile, src/dockerfiles/lambda/connectors/s3.dockerfile, src/dockerfiles/lambda/connectors/snowflake.dockerfile, src/dockerfiles/lambda/function/function.dockerfile, src/dockerfiles/lambda/function/function.py, src/dockerfiles/lambda/lambda-test.dockerfile, src/dockerfiles/lambda/param/param.dockerfile, src/dockerfiles/lambda/param/param.py, src/dockerfiles/lambda/requirements.txt, src/dockerfiles/lambda/system-metric/system-metric.dockerfile, src/dockerfiles/lambda/system-metric/system_metric.py, src/golang/cmd/server/handler/connect_integration.go, src/golang/lib/job/lambda.go, src/golang/lib/lambda/constants.go, src/golang/lib/lambda/utils.go, src/python/aqueduct_executor/operators/function_executor/extract_function.py, src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/cards/lambdaCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/lambdaDialog.tsx, src/ui/common/src/components/integrations/integrationObjectList.tsx, src/ui/common/src/utils/integrations.ts
Builds the docker images that lambda uses to run Aqueduct operators. There are some changes included to aqueduct_executor to enable lambda to work as well.
=> Lambda Workflows [builds lambda containers for operators] [4/5]

src/golang/cmd/server/server/cron.go
This PR fixes an issue that we couldn't trigger a missed workflow on server start. The issue is introduced as the handler init is out-of-date.
We should follow up for testing in ENG-1689
Workflow trigger failed with nil pointer error on this fix, succeed with this fix.
=> Fix refresh on server start 

src/golang/lib/airflow/client.go
This PR fixes a bug where if there were more runs than the default Airflow API limit, they would never be synced with Aqueduct. This PR ensures that all DAG runs get synced from Airflow into Aqueduct.
It doesn't do anything to improve the performance of syncing since that would be more involved and can be implemented for a later release.
ENG 1531
=> Fixes Airflow syncing bug with API response limit

src/dockerfiles/function/start-function-executor.sh, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/start-function-executor.sh
This PR ensures that the extracted function file is deleted for all engine types regardless of the execution status.
Previously, the file would not be deleted for Airflow execution if there was some failure.
ENG 1496
- Tested manually that the fn file was deleted for an Airflow workflow and an Aqueduct workflow
=> Deletes extracted function file for all engines and execution status

sdk/aqueduct/artifacts/bool_artifact.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/artifacts/numeric_artifact.py
We add a missing describe for the generic artifact and fix some assumptions about the describe in previous numeric and boolean artifacts where they can be an output of an `@op` decorator as well as metrics/checks.
=> Enable different artifact type to produce meaningful outputs when calling describe()

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/StatusBar.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx, src/ui/common/src/utils/operators.ts
This PR takes the workflow status bar that was on the right side of the workflow details screen and turns it into a popover which is now located in the workflow header.
ENG-1599
https://www.loom.com/share/b0407dcc1195480f834204b41705c35a
=> Eng 1599 workflow status bar popover

src/dockerfiles/Makefile, src/dockerfiles/function/py310_environment.yml, src/dockerfiles/function/py37_environment.yml, src/dockerfiles/function/py38_environment.yml, src/dockerfiles/function/py39_environment.yml, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/requirements.txt, src/golang/lib/job/constants.go, src/golang/lib/job/k8s.go, src/golang/lib/lambda/constants.go, src/golang/lib/lambda/utils.go
1. Use constants for k8s/lambda image versions.
2. Restructure Makefile to use less commands
3. Use VERSION var to build images (should be modified in file during release but can also be set during invocation of Makefile a la `make build-lambda-images VERSION=0.0.15`)  
[Eng-1709](https://linear.app/aqueducthq/issue/ENG-1709/refactor-makefile-to-use-version-number-variable)
=> Simplifies release versions for docker images

src/ui/common/src/components/integrations/dialogs/airflowDialog.tsx
This PR fixes a bug where the default s3 credentials profile was not being sent as part of a connect integration request for Airflow.
=> Sets default s3 credentials profile for Airflow integration

sdk/aqueduct/serialization.py, src/golang/lib/engine/aq_engine.go, src/golang/lib/job/spec.go, src/golang/lib/workflow/operator/param.go, src/python/aqueduct_executor/operators/param_executor/execute.py, src/python/aqueduct_executor/operators/param_executor/spec.py, src/python/aqueduct_executor/operators/utils/utils.py
During dag construction, we write the parameter value to a path and pass that path in through the spec. The parameter operator now expects that the output path has already been populated, and relegates itself to simply writing metadata and enforcing types.
This solution does not rely on any DB changes, but it does mean that for every run of a flow, we will write the parameter values to storage before calling orchestration.
@saurav-c to validate that this will work with airflow.
ENG-1565
=> Fix bug where the parameter value is too large to be passed to the python operators

src/python/aqueduct_executor/operators/connectors/data/execute.py, src/python/aqueduct_executor/operators/utils/execution.py
Task: https://linear.app/aqueducthq/issue/ENG-1480/fix-bug-where-we-spuriously-call-an-error-unexpected
Fixed:
Authenticate is a little bit weird since for some integrations, it conflates with connector initialization, so I pulled it to the top and redirected all initialization and authentication errors to the same helpful error message.
ENG-1480
=> Fix bug with bad credentials errors message when connecting to Postgres

src/ui/common/src/components/integrations/operatorsOnIntegration.tsx
Fix width on workflows accordion on Integration Details Page
https://www.loom.com/share/41383a939fd4462aad81131c0d873cdb
https://linear.app/aqueducthq/issue/ENG-1725/0015-fix-workflows-accordion-on-integration-details-page-is-too-wide
=> width fix for operator accordion on integration details page.

src/ui/common/src/components/workflows/workflowHeader.tsx
This PR fixes an issue where the settings gear stopped showing on the workflow details page.
ENG-1722
https://linear.app/aqueducthq/issue/ENG-1722/0015-fix-settings-icon-not-appearing-in-workflow-details-page
https://www.loom.com/share/4e6ad7567e7c42e28a65661a9cd98655
=> ENG-1722 Fix for Settings gear not showing on workflow details page

src/golang/lib/job/constants.go, src/golang/lib/job/k8s.go
The K8sJobManager now gets the python version server side and launches the correct docker image as a job.
https://linear.app/aqueducthq/issue/ENG-1728/select-docker-image-based-on-python-version-in-k8sjobmanager
=> Launches versioned docker image for function operator

sdk/aqueduct/api_client.py, sdk/aqueduct/responses.py, sdk/aqueduct/utils.py, src/python/aqueduct_executor/operators/airflow/spec.py
Moved all the high-level print logic into api_client.py, and added a helper method to help with indentation.
Looks like this now:
If either stdout or stderr are not provided, they will be excluded from the printing. If neither exist, the op logs section won't be printed at all.
ENG-1690
=> [SDK] Print operator logs in a consistent fashion

src/ui/common/src/components/workflows/ReactFlowCanvas.tsx, src/ui/common/src/components/workflows/nodes/BoolArtifactNode.tsx, src/ui/common/src/components/workflows/nodes/CheckOperatorNode.tsx, src/ui/common/src/components/workflows/nodes/MetricOperatorNode.tsx, src/ui/common/src/components/workflows/nodes/Node.tsx, src/ui/common/src/utils/reactflow.ts
This PR consolidates metric and check artifact/operator pairs into one node.
Users are now able to see the results of a metric or check from right within the metric or check's operator node.
https://www.loom.com/share/5ede8201f2804fc18c342875dd83ead5
ENG-1013 (https://linear.app/aqueducthq/issue/ENG-1013/designimplement-metric-artifact-dag-node)
ENG-1494 (https://linear.app/aqueducthq/issue/ENG-1494/designimplement-check-artifact-dag-node)
=> ENG-1013 and ENG-1494 NEW metric and check nodes

integration_tests/sdk/preview_test.py, src/python/aqueduct_executor/operators/airflow/spec.py, src/python/aqueduct_executor/operators/connectors/data/execute.py, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/operators/param_executor/execute.py, src/python/aqueduct_executor/operators/system_metric_executor/execute.py, src/python/aqueduct_executor/operators/utils/exceptions.py, src/python/aqueduct_executor/operators/utils/execution.py, src/python/aqueduct_executor/operators/utils/utils.py
We cannot support non-string column names for dataframes due to json-serialization (and also parquet if we chose to migrate), so if we detect such cases during serialization, we throw an error.
When you try to do something like this, you'll get:
In order to implement this nicely, we introduce the concept of an `ExecFailureException`, which can be translated to a failed `ExecutionState` at the top level. This allows us to not have to pass an exec_state around all the time to catch user errors. In this case, we had to throw an exception within the serialization helpers. It would have been somewhat to have to pass an exec_state all the way down.
In order to keep the two types of ExecutionState paths separate, we support the following pattern now, in addition to our `@user_fn_redirected` …
=> Eng 1359 fix a bug where tables with integer

src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/workflows/artifact/content.tsx, src/ui/common/src/components/workflows/artifact/csvExporter.tsx, src/ui/common/src/components/workflows/artifact/metric/history.tsx, src/ui/common/src/components/workflows/artifact/metricsAndChecksOverview.tsx, src/ui/common/src/components/workflows/artifact/summaryList.tsx, src/ui/common/src/reducers/artifactResultContents.ts, src/ui/common/src/reducers/artifactResults.ts
This PR cleans up artifact and metrics page. By managing large components individually, we reduced `index` file of each page from ~300+ lines to ~150 lines. Some components are also reusable. For example, `artifact/summaryList` can be reused for inputs / outputs for operator details page as well.
ENG-1747
Verified these refactored pages works properly.
=> Clean up metrics artf detail pages

integration_tests/sdk/param_test.py, integration_tests/sdk/type_enforcement_test.py, sdk/aqueduct/api_client.py, sdk/aqueduct/artifacts/utils.py, sdk/aqueduct/serialization.py, src/python/aqueduct_executor/operators/param_executor/execute.py, src/python/aqueduct_executor/operators/utils/utils.py
Tuples and lists are serialized into the same json string representation. To prevent confusion, we'll need to include the `artifact_type` in the deserialization process, so that we can cast tuple types appropriately before returning.
This allows us to continue viewing these objects on the UI without too much work.
Adds `deserialize()` as the method everyone should call to deserialize bytes into their python objects.
ENG-1748
=> Fix bug where tuples were being mishandled

sdk/aqueduct/api_client.py, src/golang/cmd/server/handler/get_artifact_result.go, src/golang/cmd/server/handler/get_artifact_versions.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/handler/preview_table.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/routes/routes.go, src/ui/common/src/reducers/dataPreview.ts, src/ui/common/src/reducers/integration.ts, src/ui/common/src/reducers/workflow.ts
This PR fix API route for "GetArtifactVersionsRoute", "GetArtifactResultRoute", "GetOperatorResultRoute", and "RegisterAirflowRoute". After route has been changed, there are subsequent change in UI and SDK to cope with the changes. 
https://linear.app/aqueducthq/issue/ENG-1221/fix-our-api-route-to-conform-to-the-standard
Here is the route result when previewing a published workflow
=> Fix our API route to conform to the standard

sdk/requirements/python-3-10.txt, sdk/requirements/python-3-7.txt, sdk/requirements/python-3-8.txt, sdk/requirements/python-3-9.txt, src/dockerfiles/connectors/base.dockerfile, src/dockerfiles/function/function37.dockerfile, src/dockerfiles/lambda/function/requirements-37.txt, src/dockerfiles/lambda/requirements.txt, src/python/requirements.txt
We found that older version of these packages won't work. For our Dockerfiles we can just set them to a specific version that we know will work, and for our Pypi package we set a lower bound via `>=`.
=> Bump minimum version of pydantic and typing_extentions package

src/python/bin/aqueduct
This PR fixes a bug where the Airflow DAG template wasn't downloaded as part of the `aqueduct-ml` pkg installation.
@cw75 Will add add this file as part of the packaged code in the next release. (Instructions can be found in the OSS release runbook on Notion.)
ENG 1757
=> Downloads Airflow DAG template as part of pkg install

src/python/aqueduct_executor/operators/airflow/dag.template
This PR adds `scikit-learn` to all operators running on Airflow. This is required by our Churn demo example, so let's just add it by default.
ENG 1759
=> Adds scikit-learn to all operators running on Airflow

integration_tests/sdk/multiple_output_test.py, integration_tests/sdk/operator_test.py, integration_tests/sdk/utils.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/artifacts/utils.py, sdk/aqueduct/decorator.py, sdk/aqueduct/github.py, sdk/aqueduct/parameter_utils.py, src/golang/lib/workflow/dag/workflow_dag.go, src/golang/lib/workflow/operator/function.go, src/golang/lib/workflow/operator/operator.go, src/golang/lib/workflow/utils/exec_output_paths.go, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/operators/utils/utils.py
The user can not specify whether they want an @op to return multiple output artifacts, by using `@op(num_outputs)`.
@cw75 as lead reviewer.
ENG-455
https://www.loom.com/share/1277c3c87b5a4394bea08728d8e9455f
[EDIT] the bug shown in the video is fixed by this: https://github.com/aqueducthq/aqueduct/pull/515
=> Allow user functions to have multiple output artifacts

src/ui/common/src/components/integrations/dialogs/IntegrationFileUploadField.tsx, src/ui/common/src/components/integrations/dialogs/csvDialog.tsx
Show the full data table so we don't need to scroll through to see all the rows.
ENG 1466 
https://user-images.githubusercontent.com/30596854/192826902-d526b4b7-8506-4435-b14d-2557c69aead5.mov
=> Eng 1466 fix bug where csv upload modal doesnt show the full rows without scrolling

src/ui/common/src/components/tables/PaginatedTable.tsx
This PR makes our PaginatedTable component's size more adaptable.
Sets a max height of 400px here for the table.
ENG-1752
https://www.loom.com/share/66525aa459c443dd8f7e52bdc60d1210
=> Eng 1752 Make Paginated Table Size More Adaptable

sdk/aqueduct/decorator.py, src/golang/lib/workflow/artifact/artifact.go, src/golang/lib/workflow/operator/base.go, src/golang/lib/workflow/operator/param.go, src/python/aqueduct_executor/operators/param_executor/execute.py, src/ui/common/src/components/workflows/StatusBar.tsx
@likawind as lead reviewer. @cw75 tagged to keep in the loop, since we previously discussed writing to the parameter output path in the golang orchestrator instead of the python operator.
@vsreekanti and @agiron123 for any product-related issues/questions about the coloring of nodes.
It used to be that, if an artifact is failed, we'd mark it as cancelled. However, this shouldn't necessarily be the case for checks and parameters. Parameters that fail type checking should be marked failed, as should checks that return false.
The solution proposed here is to decide whether an artifact is cancelled based on whether it has been "computed". Whether an artifact is "computed" simply means whether the artifact's content has been written to storage. This can happen even if the operator fails (once …
=> Fixes issue where Parameter and Check operators were marked as "Cancelled" incorrectly

src/ui/app/index.tsx, src/ui/common/src/components/LogViewer/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/artifact/check/history.tsx, src/ui/common/src/index.tsx, src/ui/common/src/reducers/artifactResultContents.ts, src/ui/common/src/stores/store.ts
This PR implements the check details page. I took some liberties on the mocks, but I suspect my mocks were quite out of date.
See mock here:
https://www.figma.com/file/Qz2IiYJ4NAaDHojOf2YoTm/UI-V2-Screens?node-id=874%3A29070
Things I didn't do from the mock:
-Add color tints to the results table. Certainly something we can do, but I think we have some bigger questions to answer.
-Show associated metrics in the related outputs section. (I'm not sure if this is even possible at the moment) Instead, I think we should just show a list of artifacts associated with this Check.
-Render artifact's location. Went with rendering the check's serialized result instead.
Things we should perhaps add that were missing from the mock:
-It would be nice to know what the input to this check was.
-Perhaps we …
=> ENG-919 Check Details Page

src/golang/cmd/server/handler/edit_workflow.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/engine/engine.go, src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/utils/workflows.tsx
This PR adds a section in 'workflow settings' dialog to allow user to change retention policy. We slightly modified backend to be able to accept updated retention policy in API calls.
I noticed there are a few places to improve this dialog, which is out of scope of this PR:
https://linear.app/aqueducthq/issue/ENG-1781/improve-workflow-settings-dialog
ENG-1606
Somehow the audio is off. A few notes to pay attention to:
* we show the current value of retention policy when the user first open the dialog.
* If the value is empty we inform the user that all versions will be preserved.
https://www.loom.com/share/8fd37869934042e1b7938c672e5a6629
- `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY …
=> ENG-1606 enable users to change retention policy via UI

src/ui/common/src/components/cards/GettingStartedTutorial.tsx, src/ui/common/src/components/pages/HomePage.tsx
This PR fixes an issue where the aqueduct logo appeared cut off on the home page.
ENG-1645
Screenshot:
=> ENG-1645 Fix for aqueduct logo appearing cut off on the home page.

src/ui/common/src/components/layouts/menuSidebar.tsx
This PR adds a link to the documentation page in the bottom of the menu sidebar.
ENG-1457
Screenshot:
=> ENG-1457 Adds Documentation link to menu sidebar

src/ui/common/src/components/workflows/ReactFlowCanvas.tsx
This PR fixes a bug which caused the app to crash when the user switches workflow versions using the version dropdown in the workflow header.
ENG-1760
https://www.loom.com/share/78f11760e7b34b2bbe205d67523d2707
=> Eng 1760 workflow version switching bug

src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/workflows/artifact/content.tsx
This PR fixed the bug where we show a 'success' alert when we failed to fetch from REST endpoints in artf / metrics / check details page.
ENG-1782
Before:
After (this is done by hacking the API to return a test error message):
=> Eng 1782 improve error handlings in artifact / metrics / check details page

src/ui/common/src/components/text/LogBlock.tsx
This PR adds overflow-y:scroll to the LogBlock component's Alert box to allow users to scroll and view contents of longer error messages.
ENG-1787
=> ENG-1787 Enable scroll for long stdout or stderr messages

src/golang/cmd/executor/executor/workflow.go, src/golang/lib/engine/lock.go, src/golang/lib/workflow/utils/lock.go
This PR requires the workflow executor to acquire a read lock at the beginning of each workflow run execution. This allows us to pause new workflow runs if there are certain system maintenance jobs that need to be performed, such as metadata store migration (this work will be in a later PR).
The PR uses a `filelock` to perform synchronization across processes, since each `executor` is its running in its own process. Once we turn these processes into goroutines, we can trade the `filelock` for a generic `mutex`.
ENG 1779
=> Requires workflow executor to check for paused workflow execution

src/ui/common/src/components/tables/OperatorExecStateTable.tsx, src/ui/common/src/components/tables/PaginatedTable.tsx
Fix type error on PaginatedTable causing app to not be able to build.
Fix here is to use toString() to turn Dates to strings when rendering.
Relevant Stack overflow: https://stackoverflow.com/questions/71926536/type-string-date-is-not-assignable-to-type-reactnode-typescript
Error message that was fixed:
```
✓ Creating entry file 1.6 secs
(typescript) Error: /Users/andre/Documents/Code/aqueduct/src/ui/common/src/components/tables/PaginatedTable.tsx(99,27): semantic error TS2322: Type 'string | number | boolean | Date' is not assignable to type 'ReactNode'.
Type 'Date' is not assignable to type 'ReactNode'.
Type 'Date' is not assignable to type 'number'.
Error: /Users/andre/Documents/Code/aqueduct/src/ui/common/src/components/tables/PaginatedTable.tsx(99,27): semantic error TS2322: Type …
```
=> Fix Table Type Errors

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/components/workflows/storageSelector.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx, src/ui/common/src/utils/storage.ts
This PR does 3 things:
1. It improves the layout of the workflow header by moving the success pill above the workflow title and movig the run workflow button next to the settings gear.
2. It moves the metadata storage indicator into the settings modal.
3. It uses the size of the workflow page to make the header itself responsive.
ENG-1763, ENG-1770
https://www.loom.com/share/db899c5f6e554bc7b5744f358308c628
Here's a screenshot of the page with the drawer open on my 13" MBP screen: 
=> [UI redesign] Simplifies workflow header and improves responsiveness

integration_tests/sdk/utils.py
There's no reason to wait 5 seconds between polls, this penalizes tests that should run a lot quicker.
This 2x's the speed of the integration test on my 8-core Mac (1:40 vs 3:20 to run the full speed). It does not appear to help our performance on github actions however, but I believe that is because these machines are underpowered with 2-cores. When we get the beefier github runners, I'd expect this to help a lot more.
=> [Testing Performance] Decrease polling interval of integration testing suite

src/ui/common/src/components/workflows/StatusBar.tsx, src/ui/common/src/components/workflows/nodes/nodeTypes.tsx
Updates formatting of workflow status bar items. 
This PR removes the word "Artifact" which was prepended to each artifact.
Also adds the type of node (operator or artifact) at the bottom of the list item.
https://linear.app/aqueducthq/issue/ENG-1771/[workflow-page]-format-messages-in-status-widget-consistently
Screenshot:
=> ENG-1771 status bar message formatting

src/python/aqueduct_executor/operators/connectors/data/sqlite.py, src/resources/demo_db/sqlite/v0.1/create_tables.py
Due to SQLITE's variable number limit, we need to chunk the data insertion operation so that the number of variables is less than 32766. Verified that this fixes the issue on the wine workflow.
=> Chunk SQL insert for sqlite3 integration

src/ui/common/src/components/integrations/dialogs/kubernetesDialog.tsx
Quick Fix to standardize the kubeconfig path 
https://linear.app/aqueducthq/issue/ENG-1718/fix-bug-where-kubeconfig-placeholder-is-missing-leading-slash
=> Fix bug where kubeconfig placeholder is missing leading slash

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/StatusBar.tsx
This PR fixes the bug where we show wrong version for op / artf results esp. when a new workflow is created. The main change is to correct a condition so that we fetch op / artf results when a new dag result is selected.
ENG-1639
https://www.loom.com/share/62075c3cda5c462f8d259ab170615fa6
=> Eng 1639 correctly switch op / artf results when switching between versions

src/ui/common/src/components/workflows/StatusBar.tsx
This PR adjusts the max width and height of the Workflow Status Bar's list component to look better on smaller screen sizes.
These numbers were found simply by playing around with units of 8 to see what looks good on my 14 inch Macbook Pro. I tried to find values that looked good without media queries here for both opened and closed side bar.
ENG-1756
https://www.loom.com/share/027085ea8eaf45208b8a11374f1f0573
=> Eng 1756 status popover improvements

sdk/aqueduct/utils.py
When SDK is not running in a file-based environment (e.g. notebook or script), `inspect.getsource` will error complaining we couldn't find source file. This PR adds a simple fix by not attempting to add source file in such cases. Instead, we just let user know we failed fetch the file.
Context: https://aqueducthq.slack.com/archives/C01KF131001/p1665104258513939 . We can successfully run aqueduct in python interpreter after this fix. Verified existing notebook still works.
I think the only consequence is that the user won't be able to view source from UI for these workflows. But I think it's fine for now, assuming this use case is rare.
Integration tests should be sufficient.
- `skip_integration_test`: Skips integration tests (Should be used …
=> Fix a bug where we errors when the script is running in python interpreter

src/ui/common/src/components/pages/integrations/index.tsx
This PR adjusts the spacing on the section headers of the integrations page to make them more consistent.
ENG-1708
https://www.loom.com/share/969aeeccaacd4feab93f806f4290dfc9
=> ENG-1708 Makes spacing for sections on integrations page more consistent.

src/ui/common/src/components/layouts/NavBar.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx
-This PR fixes crashes caused by artifacts or operators being undefined in the breadcrumb component.
-Updates aqueduct logo to use light aqueduct logo without words and with a transparent background. 
-Also fixes an issue where the red background for the notifications bell would show when there are no notifications. 
ENG-1488
=> Eng 1488 bug fixes

src/aqueduct-helm/Chart.yaml, src/aqueduct-helm/templates/clusterrole.yaml, src/aqueduct-helm/templates/clusterrolebinding.yaml, src/aqueduct-helm/templates/deployment.yaml, src/aqueduct-helm/templates/role.yaml, src/aqueduct-helm/templates/service.yaml, src/aqueduct-helm/values.yaml
There are two main fixes:
1. Since our executor attempts to create jobs in the `aqueduct` namespace, in the helm chart we need to define role and rolebinding in the `aqueduct` namespace.
2. In our Golang code we have logic to create namespace `aqueduct` if not exist. Since namespace is a cluster resource, we need to use clusterrole and clusterrolebinding for this.
=> Fix a number of bugs in the helm chart

src/aqueduct-helm/Chart.yaml, src/aqueduct-helm/templates/clusterrole.yaml, src/aqueduct-helm/templates/clusterrolebinding.yaml, src/aqueduct-helm/templates/deployment.yaml, src/aqueduct-helm/templates/role.yaml, src/aqueduct-helm/templates/service.yaml, src/aqueduct-helm/values.yaml, src/golang/cmd/server/handler/get_server_environment.go, src/golang/cmd/server/routes/routes.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/collections/integration/config.go, src/golang/lib/engine/authenticate.go, src/golang/lib/engine/utils.go, src/golang/lib/job/config.go, src/golang/lib/job/k8s.go, src/golang/lib/k8s/clients.go, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/kubernetesDialog.tsx, src/ui/common/src/utils/integrations.ts
When the Aqueduct server is already running in a k8s cluster, when connecting to a k8s integration we want to give users the option to use the same cluster to launch their operators. We implement this by setting an environment variable in the helm chart template and adding an endpoint to the server that returns the value of this env var to the UI. Based on its value, the UI decides whether to show the check box to run the compute from within the same cluster.
There are a few more fixes on the backend side that I'll patch in a subsequent PR, but this PR completes the UI portion.
https://www.loom.com/share/f68f10ae548e44199e1b43975bcb1fe8
- `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY …
=> Update k8s integration UI when the server runs in an existing cluster

src/ui/common/src/components/Search/index.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/pages/workflows/index.tsx, src/ui/common/src/handlers/responses/dag.ts
This PR fixes two bugs:
1. ENG-1817: No longer show "undefined" after the user presses enter after entering a search query on the workflow page search bar
2. ENG-1809: Only show the search bar on workflow list page if there are workflows to search.
ENG-1817
ENG-1809
https://www.loom.com/share/a881f074bae44cbda5f30b26612b2dc4
=> Eng 1817 fix enter bug ENG-1809 Only show search bar if there are workflows

src/ui/common/src/components/layouts/menuSidebar.tsx
This PR renames the documentation link on the navigation bar to "Docs", which now properly renders without going over the width of the navbar.
ENG-1808
Screenshot:
=> ENG-1808 docs link fix

src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/workflows/StatusBar.tsx, src/ui/common/src/handlers/responses/dag.ts
This PR fixes bug where 'artifact' and 'operator' labels were shown in workflow status bar when there were no errors or warnings or info events.
ENG-1814
https://www.loom.com/share/7a5ffc9e8316480780e4f8010aa6db5b
=> ENG-1814 Workflow Status Bar label fixes

src/ui/common/src/components/layouts/NavBar.tsx
This PR brings back the click listener that was attached to the avatar component. I forgot to move this over when replacing with the settings gear 🤦 .
This PR also removes the unused avatar component.
ENG-1823
NA: clicking settings gear now shows menu with Account option as it did before.
=> ENG-1823: Clicking settings gear does nothing

src/ui/common/src/components/layouts/NavBar.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx
This PR fixes a bug where the preview doesn't load in workflow sidesheet mode. The fix ensures the request to fetch data is properly dispatched.
ENG-1825
Now the preview loads in sidesheet:
=> Eng 1825 fix a bug where preview is showing spinner in sidesheet

src/ui/common/src/components/layouts/NavBar.tsx, src/ui/common/src/components/layouts/menu-sidebar-styles.module.css, src/ui/common/src/components/pages/HomePage.tsx
This PR fixes two minor issues:
* adjusted color for black navbar icon
* added a spacing in homepage bottom.
* 
ENG-1829
ENG-1826
Current PR uses blue icon color, the same as menu:
Gray version (this also shows the margin at the bottom of the page):
=> Fix navbar icon color and main page spacing

src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/tables/PaginatedTable.tsx, src/ui/common/src/utils/sidesheets.tsx
This PR fixes an issue where the details sidesheets were too wide for their containers causing there to be some weird scroll for just a few pixels.
https://linear.app/aqueducthq/issue/ENG-1815/fix-bug-where-details-pages-are-too-wide-for-viewport
https://www.loom.com/share/071eb6672918455c8ca48c31bb76dade
=> ENG-1815 Details Sidesheets Spacing Fixes

src/ui/common/src/components/layouts/default.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx
Fix spacing.
- Add spacing to the top of the sidesheet
- Fix width so error does not go off screen.
eng-1828
**Before: Little/no space at top of sidesheet**
**After: More space at top of sidesheet**
**Before: Error goes off screen**
**After: Error ends on-screen**
=> eng-1828 add spacing above the failed-to-load error

sdk/aqueduct/artifacts/bool_artifact.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/artifacts/numeric_artifact.py, sdk/aqueduct/artifacts/table_artifact.py, sdk/aqueduct/decorator.py, sdk/aqueduct/utils.py
Once this merges, we can once again upgrade our numpy to whatever version and run `run_linters.py` without fear.
Turns out all we had to do to fix this was to make `Union[int, float, np.number]` its own type. Don't ask me why that works...
The other errors were stomped out why asserting that data was of the correct type before returning.
ENG-1754
=> Fix mypy errors that resulted from numpy version > 1.19

src/ui/common/src/components/LogViewer/index.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/workflows/StatusBar.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx, src/ui/common/src/handlers/getWorkflowDagResult.ts
This PR fixes a bunch of small bugs in the way errors are surfaced in the UI redesign. 
For ENG-1833, this PR increases the maximum width of viewport of the status bar -- it doesn't just do `fit-content` because that makes it weirdly wide, but now a typical stack trace much easier to lead.
For ENG-1834, this PR shows the full stack trace under the log viewer component; if the user is at this point, they probably want to see the full set of details, so we don't condense the height at all -- instead, we set the height to `fit-content` of the stack trace. 
ENG-1833, ENG-1834
The expanded width of the workflow status bar when there's a stack trace. Note that there's still a minor bit of scroll -- I picked this width because it's still legible with the drawer open on a 13" MBP screen.
When …
=> [ENG-1833, 1834] Fix error surfacing in UI redesign

src/ui/common/src/components/CodeBlock/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/utils/operators.ts
This PR fixes two things: 
-Fixes crash which happened when loading operator details page from it's link
-Fixes issue where extract operators did not show SQL query in file viewer. These queries are now rendered using the code block component since there are no files associated with the extract operator.
ENG-1827
https://www.loom.com/share/29ce87e2d2b94a439f62c728cb0b6218
=> ENG-1827: Fix for SQL queries not showing on extract operators. Fix for app crashing when loading extract operator from link

sdk/aqueduct/responses.py, src/golang/cmd/server/handler/list_workflows.go, src/golang/lib/collections/tests/workflow_test.go, src/golang/lib/collections/workflow/postgres.go, src/golang/lib/collections/workflow/sqlite.go, src/golang/lib/collections/workflow/workflow.go, src/ui/common/src/components/workflows/workflowCard.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx, src/ui/common/src/utils/workflows.tsx
This PR adds display to what engine the workflow is running on in two locations, the workflow browsing page and the workflow detail page. 
https://linear.app/aqueducthq/issue/ENG-1812/show-which-engine-the-workflow-is-running-on-on-the-uis-workflow-page
=> Show which engine the workflow is running on on the UI's workflow page

src/golang/lib/vault/crypto.go
This PR fixes a vault encryption bug where the arguments to `gcm.Seal` were modified.
I confirmed this works by connecting a Snowflake integration and issuing a preview request, which goes thru the vault to access the credentials.
=> Fixes vault encryption bug

src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/reducers/workflow.ts
This PR fixes the following bugs:
* extra nodes don't get collapsed when clicking around UI. This is caused by the collapsing state depends on artfResults store, which sometimes is not available when we are trying to collapse. This PR changes the collapsing logic by not assuming artfResults exist, but we rather refill those results to collapsed nodes once they become available.
* artifact status appears to be wrong when refreshing workflow. We verified refreshing workflow does bring the state to latest.
* page crashes when trying to refresh artf / op detail pages. This is caused by these pages relying on wrong reducer. We fixed by using the new reducer.
ENG-1864
https://www.loom.com/share/f439a019169f4617b4dcfdb845d42e62
Verified everything works in two browsers (chrome and safari).
- …
=> Eng 1864 Fix UI bugs on showing nodes and render breadcrumb links

sdk/aqueduct/enums.py, sdk/aqueduct/serialization.py, sdk/aqueduct/utils.py, src/python/aqueduct_executor/migrators/parameter_val_type_inference_000019/serialize.py, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/operators/param_executor/execute.py, src/python/aqueduct_executor/operators/utils/enums.py, src/python/aqueduct_executor/operators/utils/utils.py
Adds type support for any non-pickleable classes that inherit from tf.keras.Model. `tf.keras.Model` objects themselves are actually picklable, and so are already supported by our typing system.
In the example notebook torn pulled from https://www.tensorflow.org/recommenders, we can actually get it working with the existing system if `train_model` returns the user and movie models directly, instead of the `MoveLensModel`, which is a `tfrs.Model` (which inherits from `tf.keras.Model`).
If `train_model()` returns a `MovieLensModel`, we get the following error:
```
ValueError: Model <__main__.train_model.<locals>.MovieLensModel object at 0x7f1f20436100> cannot be saved either because the input shape is not available or because the forward pass of the model is not defined.To define a forward …
```
=> Add tfrs.Model type support

examples/README.md
This is unnecessary because we now print out the workflow url on every `publish_flow()`. The script is smart enough to find the UUID in this url and check that it has completed at least one run.
=> Remove unnecessary requirements from `run_notebooks` readme

src/golang/cmd/server/server/aqueduct_server.go
This Pr allows for pausing and restarting the server. This is done by separating out the server field initialization from the server constructor. This allows us to ensure that the necessary fields are reinitialized after restart, such as the server vault. The important thing is that the `chi.Router` is not reinitialized as this needs to be the same in order for the HTTP server to continue running.
ENG 1882
=> [2/7] Implements server pause and restart

src/golang/cmd/server/middleware/maintenance/maintenance.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/cmd/server/server/execute_handler.go
This PR adds a couple of different things to the server struct:
1. An `atomic` bool is added as a flag to indicate when the server should block all new requests. An example of this use case is when performing storage migration.
2. It is not sufficient to just block new requests, sometimes the system maintenance job can only be performed when we are certain that there are no more active requests. One approach is shown in this PR by having a mutex that should be acquired and released by every single request. Each request will acquire a read lock, so requests will not block other requests, but when a system maintenance job needs to performed it can simply acquire an exclusive lock and be confident that there are no more requests active in the server, as otherwise the lock acquisition would …
=> [1/7] Allows for blocking requests during system maintenance

src/golang/cmd/server/server/aqueduct_server.go, src/golang/cmd/server/server/vault.go, src/golang/lib/storage/file.go
This PR syncs the vault with storage by moving the vault into the current storage layer. This operation will only happen once at server start time if it has not happened in the past.
This is necessary because currently the vault is found in the local filesystem at `aqueduct_path/vault`, whereas storage can be either in a different directory locally or it could be set to cloud storage, i.e. S3 or GCS.
=> [7/7] Syncs vault with storage at server start

src/ui/common/src/components/Search/index.tsx
This PR fixes a bug where the search bar on data page did not show suggestions.
ENG-1881
Screenshot:
=> ENG-1881 Fix bug where data page search suggestions did not appear.

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/server/handlers.go, src/golang/cmd/server/server/vault.go, src/golang/lib/vault/s3.go, src/golang/lib/workflow/utils/migrate.go
This PR puts together the final backend pieces of performing storage and vault migration.
The migration is invoked as an asynchronous goroutine once all other steps for connecting an integration have succeeded. These steps include validating the credentials of the integration.
The goroutine will do the following:
1. Stop all new requests to the server and respond with a server unavailable error code.
2. Wait for all active requests to complete.
3. Wait for all active workflow runs to complete.
4. Perform storage migration.
5. Perform vault migration.
6. Delete all storage and vault content from the old store and vault.
7. Update the storage config to the new config.
8. Unblock workflow runs.
9. Unblock server requests.
There are also a handful of various bug fixes. More details inline or …
=> Invokes storage migration once storage integration is connected

src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx
This PR adds a snackbar alert once a storage integration is connected to indicate that a migration is in progress.
ENG 1788
https://www.loom.com/share/f2694548e8ed4d6e93c16efdaa08f529
=> Shows alert for in progress storage migration

integration_tests/no_concurrency/sdk/latency_sensitive_test.py, integration_tests/no_concurrency/sdk/requirements_test.py, integration_tests/no_concurrency/sdk/utils.py, integration_tests/sdk/preview_test.py
This test appears to fail transiently in GH actions. The theory is that the GH machines are quite underpowered and can leave certain flows hanging for some time under concurrency. As a first step, lets move this latency-sensitive test to the single-process suite.
Linked to in https://www.notion.so/aqueducthq/Transient-Automated-Test-Failures-76639acc78ec45d9a0a0df66f9a3799d
ENG-1583
=> Move preview caching test to `no_concurrency` suite

integration_tests/sdk/flow_test.py, sdk/aqueduct/decorator.py
While looking at the task for adding **kwargs support, I noticed that we didn't consider all the possibilities for *args support.
This PR allows us to support user functions that are defined with variable-length parameters:
```
def foo(*args):
...
```
This involves disallowing implicit parameters in such cases. For now, it's easier to make this an unsupported case, since we don't really know what name to assign such parameters. If they want to use parameters for such functions, they should create them explicitly.
Here is the error message:
NOTE: supporting **kwargs is actually a bit more involved than originally intended, as we have to do some stuff on both the sdk and backend side.
- `skip_integration_test`: Skips integration tests (Should …
=> Add positional, variable-length support for all functions

src/ui/common/src/components/layouts/NavBar.tsx
Adds more space between the notifications and settings button.
ENG 1854
=> Increases margin between notifications and setting button in header

src/ui/common/package-lock.json, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/workflows/StatusBar.tsx, src/ui/common/src/components/workflows/nodes/ParameterOperatorNode.tsx, src/ui/common/src/components/workflows/nodes/nodeTypes.tsx, src/ui/common/src/index.tsx
This PR gives parameters label in status bar output. Adds icon and node type to use for rendering parameters should we choose to render them in the future.
ENG-1860
Updated loom demo:
https://www.loom.com/share/f6d8e0e722084134bd80641fe324591d
=> ENG-1860: Parameter Status Bar Label and add Parameter Icon

src/ui/common/package-lock.json, src/ui/common/src/components/pages/workflow/id/index.tsx
This PR fixes a bug where there is an overflow in the "View operator details" button when the contents of the button next to it are too long.
To remedy this issue, I added a max width to the .zip file button and set it's text overflow to be ellipsis.
ENG-1899
Screenshot:
=> ENG-1899 Fix bug where the text in the "view operator details" box overflows

src/ui/common/src/components/workflows/workflowHeader.tsx
I don't know how this line got lost, it was in the original PR. This should fix the parameter triggering bug when a string is inputted.
=> Fix parameter triggering from the UI

integration_tests/sdk/flow_test.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/config.py, sdk/aqueduct/globals.py, sdk/aqueduct/utils.py
This PR does two things:
1) Adds the `engine` key to `aq.global_config()`. Once this merges, the client can define a global engine backend to run against. `publish_flow()` will respect this global config if none is set.
```
aq.global_config({"engine": "my_lambda_integration"})
client.publish_flow(...)
client.publish_flow(engine="my_k8s_integration")
```
@Fanjia-Yan, you can use this global config in your preview change.
2) Adds the `engine` and `k_latest_runs` arguments directly to `publish_flow()`. We will keep the old `FlowConfig()` way around for backwards compatability, but with a deprecation message if it is used.
```
client.publish_flow(..., engine="my_compute_integration", k_latest_runs=10)
```
You cannot set these fields redundantly, you'll get the following:
Testing:
- This is …
=> [SDK] Simplify supplying the engine integration

sdk/aqueduct/utils.py
I verified that the proposed requirement detection rules are already enforced. This PR mainly tidies up some comments.
The only functionality change I made is to add client's cloudpickle version to the function's requirements file. This is useful when we aren't using `pip freeze`, because when the user manually specifies the requirements, they are unlikely to include the cloudpickle entry, but for us, we need to ensure that the server installs the same version of cloudpickle as the client, so adding this entry will prevent potential serialization bugs due to cloudpickle version mismatch.
=> Verified that the requirement detection hierarchy is already enforced

src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx
This PR fixes a bug where the add integrations dialog does not close after successfully connecting.
ENG-1968
https://www.loom.com/share/72d09ed3ca1840b581598078bf20da45
=> ENG-1968: Close Add Integration Dialog After Successfully Connecting

.github/workflows/run-notebooks.yml
We were installing a wrong pip package for sklearn, which caused the module import to fail. The PR also includes all example notebooks into the action triggering condition.
=> Fix run_notebook action

src/ui/common/src/components/integrations/dialogs/kubernetesDialog.tsx
Fixes issue where a request is sent to fetch environment each time a key is pressed in the Kubernetes Add Integration Dialog
ENG-1972
=> Fix extraneous request issue for kubernetes dialog.

src/ui/common/src/components/layouts/menuSidebar.tsx
Fixes issue where dividers take up more than the width of the menu sidebar.
ENG-1936
Screenshot: 
=> ENG-1936: Dividers Too Wide

src/ui/common/package-lock.json, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/operator/id/index.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx
Fixes bug where operator sidesheet names showed as operator node
ENG-1974
Screenshot:
=> ENG-1974 Properly Show Operator Name in SideSheet

integration_tests/sdk/conftest.py
Adds the `--data` flag, which is the same as the `--engine` flag but specifies that we will only extract and load to/from a certain data integration. 
Moves away from parameterizing the test suite across all integrations for now. After this lands, the user will have full control over what data integration and engine they want to run their tests against.
=> Allow data integration to be configured from command line in the integration tests

integration_tests/sdk/checks_test.py, integration_tests/sdk/conftest.py, integration_tests/sdk/constants.py, integration_tests/sdk/delete_workflow_test.py, integration_tests/sdk/flow_test.py, integration_tests/sdk/load_test.py, integration_tests/sdk/metrics_test.py, integration_tests/sdk/multiple_output_test.py, integration_tests/sdk/no_return_test.py, integration_tests/sdk/param_test.py, integration_tests/sdk/sql_integration_test.py, integration_tests/sdk/type_enforcement_test.py, integration_tests/sdk/utils.py, sdk/aqueduct/aqueduct_client.py
@hsubbaraj-spiral  as primary reviewer. @Fanjia-Yan this should help you test out your changes in a more automated fashion.
Adds an `engine` fixture to our SDK integration test suite. This value can be requested by any test:
```
def test_something(client, engine):
...
client.publish_flow(..., engine=engine)
```
This `engine` value can be configured through the command line, and corresponds to the name of the compute integration we want to run the test suite against!
For example, if our server has connected to a K8s integration called "my_k8s_integration", I could run the test suite with:
```
API_KEY=Q96DTSL0MNRCVO3YF2IJX1WAKPEH8U45 SERVER_ADDRESS=localhost:8080 pytest . -rP -vv --engine "my_k8s_integration" -n 8
```
And it will run all relevant tests agains the K8s compute backend.
If …
=> Add ability for tests to run against multiple backing engines

src/golang/lib/job/process.go, src/golang/lib/job/spec.go, src/golang/lib/workflow/operator/base.go, src/golang/lib/workflow/operator/operator.go
This PR adds ExecEnv to the FunctionSpec and enables the job manager to run operators with non-nil ExecEnv field with their Conda environments. It also refines some code commenting.
=> Enable function operators to run with Conda environments

src/dockerfiles/function/start-function-executor.sh, src/python/aqueduct_executor/start-function-executor.sh
Couple questions here:
1) Why didn't this fail before? This was changed 6 days. Is it because we didn't update the dockerhub image for 3.8? @cw75 
2) Why are these two dockerfiles separate at all?
=> Fix start-function-executor mismatch bug between aqueduct_executor and dockerfiles

src/ui/common/src/components/integrations/dialogs/kubernetesDialog.tsx
This PR fixes a lint warning in the kubernetes dialog related to not using exhaustive dependencies.
NA
=> Fixes react-hooks/exhaustive-deps warning in kubernetesDialog.

src/python/bin/aqueduct, src/ui/common/src/utils/integrations.ts
We will re-enable the Conda integration option once we finish the backend implementation.
The Conda install option needs to be removed anyway. This should have been done in the previous PR but we forgot to remove it.
=> Disable Conda from UI and remove Conda install option

src/ui/common/src/components/workflows/version_selector.tsx
This PR fixes a lint error in the version_selector component:
```
/Users/andre/Documents/Code/aqueduct/src/ui/common/src/components/workflows/version_selector.tsx
║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 86       │ 17       │ warning  │ Assignments to the 'menuItems' variable from           │ react-hooks/         ║
║          │          │          │ inside React Hook useEffect will be lost after         │ exhaustive-deps      ║
║          │          │          │ each render. To preserve the value over time,          │                      ║
║          │          │          │ store it in a useRef Hook …
```
=> Fixes lint warning on version_selector component

integration_tests/sdk/resources_test.py, src/golang/lib/job/k8s.go
This fixes all the `pending` indefinitely issues. However, it requires an extra kubectl query on every Poll(). @hsubbaraj-spiral does this also fix the "wrong-gpu-name" error you were describing?
Overallocated CPU error:
Overallocated Memory error:
ENG-2002
=> Fix bugs where overallocating memory or CPU causes workflow to hang indefinitely

src/dockerfiles/lambda/function/function.py
Lambda execution is broken because it's still using `prune_requirements`. This updates it to use `install_requirements()`.
=> Fix broken Lambda execution

.github/workflows/run-notebooks.yml
After some digging, I think I get what’s going on. So we run notebooks on ubuntu-latest but now there is a migration that changes ubuntu-latest  version from 20.04 to 22.04. https://github.com/actions/runner-images/issues/6399. However, there is no python version of 3.8.10 of linux 22.04 which causes the failure.
One way we can make this work is to either hard coded the ubuntu version or we can change the python version that has linux 22.04 version.
=> Fix Run Notebook Fail Resulted From Python Setup

integration_tests/sdk/conftest.py, integration_tests/sdk/preview_test.py, integration_tests/sdk/resources_test.py, sdk/aqueduct/artifacts/utils.py, sdk/aqueduct/dag.py, sdk/aqueduct/operators.py, src/golang/lib/job/k8s.go, src/golang/lib/job/lambda.go, src/golang/lib/job/lambda_test.go, src/golang/lib/workflow/operator/base.go
@hsubbaraj-spiral as lead reviewer.
Configuring memory for a lambda-backed operator adds about a minute of latency to the operator, since it takes about 25-30 seconds for the update to be properly registered, and we have to make two updates, one to set to the new memory, one to reset to the previous one at the end of the operator. Also, the operator has to run synchronously in such cases now.
This PR doesn't provide full memory config isolation. It is possible that operators scheduled beforehand will race with our custom memory config request to the Lambda function. I made a task (https://linear.app/aqueducthq/issue/ENG-2030/decide-what-level-of-memory-configuration-isolation-to-provide-for) to decide whether we want full isolation. The reason I didn't do it here is that it seemed like a …
=> Adds ability to configure memory for Lambda-backed operators

.github/workflows/periodic-integration-tests.yml, integration_tests/sdk/checks_test.py, integration_tests/sdk/conftest.py, integration_tests/sdk/delete_workflow_test.py, integration_tests/sdk/flow_test.py, integration_tests/sdk/load_test.py, integration_tests/sdk/metrics_test.py, integration_tests/sdk/multiple_output_test.py, integration_tests/sdk/no_return_test.py, integration_tests/sdk/param_test.py, integration_tests/sdk/resources_test.py, integration_tests/sdk/sql_integration_test.py, integration_tests/sdk/type_enforcement_test.py, integration_tests/sdk/utils.py, sdk/aqueduct/aqueduct_client.py, sdk/aqueduct/flow.py, src/golang/lib/engine/authenticate.go
1) Introduces a `flow_name` fixture that allows the test suite to handle all the cleanup. The developer doesn't have to do any delete_flow() manipulation anymore. This fixture must be used as a function.
2) Replaces `run_flow_test()` with a better, updated version of the helper, `publish_flow_test()`. Also introduces a trigger counterpart `trigger_flow_test()`.
3) Adds the `name()` method to the Flow object.
4) Adds a `--keep-flows` flag to the command line, which will NOT delete flows that were created during the test. This helps preserve state when you're debugging an individual test, for example.
5) Adds an empty requirements file to `integration_tests/sdk`. This might help a little bit with perf on GH actions, but it should definitely help a lot when running against a backing engine …
=> Builds many improvements into SDK integration test suite

src/ui/app/index.tsx, src/ui/common/package-lock.json, src/ui/common/src/components/layouts/NavBar.tsx, src/ui/common/src/components/layouts/default.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/pages/workflows/index.tsx, src/ui/common/src/reducers/workflow.ts
This PR fixes a bug where user is unable to switch workflows after clicking back from workflow details page.
ENG-2047
https://www.loom.com/share/92f1f04d1e9b48fabfc435a86c5184ba
=> ENG-2047 Bugfix: User unable to switch workflows after hitting back button in browser

src/golang/cmd/server/handler/get_workflow.go, src/golang/cmd/server/handler/list_workflows.go, src/ui/common/src/reducers/workflow.ts, src/ui/common/src/utils/workflows.tsx
This PR removes the `auth0IDs` from the `ListWorkflow` route response. Since the auth0ID is no longer used by the frontend there is no need for us to return this. This also helps reduce the DB project refactor by 1 method 😎 
=> Removes auth0ID from ListWorkflow response

src/golang/cmd/server/handler/connect_integration.go, src/golang/lib/execution_environment/integration.go, src/ui/common/src/components/integrations/dialogs/condaDialog.tsx
This PR modifies the behavior that we silently install `conda build` on user's behalf. Instead, we return an error on connection time informing the user that the required dependency is missing.
ENG-2016
When the user doesn't have `conda-build` installed:
Verified connection is successful if conda build is already installed.
=> Eng 2016 Return an error if user doesnt have conda-build installed

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/collections/execution_environment/execution_environment.go, src/golang/lib/collections/execution_environment/noop.go, src/golang/lib/collections/execution_environment/standard.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/execution_environment/execution_environment.go, src/golang/lib/execution_environment/integration.go, src/ui/common/src/components/integrations/cards/condaCard.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/conda/condaConnectionStatus.tsx, src/ui/common/src/components/integrations/dialogs/condaDialog.tsx
At the end of workflow registration, we compute unused exec env IDs and garbage collect them. We also delete db records of successfully GCed Conda environments.
=> Garbage collect unused exec envs after workflow registration

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/preview.go, src/golang/lib/execution_environment/execution_environment.go, src/golang/lib/execution_environment/integration.go
This PR moves conda base env creation to an async go routine. We also made changes to update the integration object properly.
Specifically, we use `config` field to track a serialized `ExecState` object so that the user / backend is informed about the exec state.
We also modified 'preview' such that it will block execution if the env creation is still in progress.
Note: UI change only set up basics to handle exec state. We will make improvements so that it renders more details about the exec state.
ENG-2011
https://www.loom.com/share/1dc0308ebeb3416d92cc229f45eaf2c3
=> Eng 2011 Asynchronosly create conda env after integration connection

src/ui/common/src/components/LogViewer/index.tsx
There was a tiny bug in the log viewer where objects weren't actually rendered because we weren't treating them as objects.
ENG-2015
Logs are actually displayed now: 
=> [ENG-2015] Fixes bug where logs weren't displayed on operator details

src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/down_postgres.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/up_postgres.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/up_sqlite.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/lib/collections/execution_environment/execution_environment.go, src/golang/lib/collections/execution_environment/noop.go, src/golang/lib/collections/execution_environment/standard.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/execution_environment/execution_environment.go
The main one is that previously, our execution_environment table's hash column is marked as "unique", but this doesn't work well with the added gc column, because once an env is gced, a new env should be allowed to be created with the same hash. So we modify the table to drop the "unique" constraint. Since the previous release doesn't expose conda to the user, we can safely delete the entire table and recreate a new one without this constraint.
=> Fix a number of bugs in the conda integration

scripts/install_local.py, src/golang/cmd/migrator/migrator/register.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/down_postgres.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/main.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/up_postgres.go, src/golang/cmd/migrator/versions/000021_add_gc_column_to_env_table/up_sqlite.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/delete_workflow.go, src/golang/cmd/server/handler/list_operators_for_integration.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/collections/execution_environment/constants.go, src/golang/lib/collections/execution_environment/execution_environment.go, src/golang/lib/collections/execution_environment/noop.go, src/golang/lib/collections/execution_environment/standard.go, src/golang/lib/collections/operator/operator.go, src/golang/lib/collections/operator/postgres.go, src/golang/lib/collections/operator/sqlite.go, src/golang/lib/collections/operator/standard.go, src/golang/lib/collections/tests/operator_test.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/execution_environment/execution_environment.go, src/python/bin/aqueduct, src/ui/common/src/components/LogViewer/index.tsx
This PR adds a GC column to the execution environment table, and modifies existing logic to update this column correctly.
The PR also adds an async GC routine after the user deletes an workflow, as after that there could be exec envs that are no longer used.
=> Adds GC column to the env table

src/python/bin/aqueduct
This PR updates the main python script to update base conda environments when updaating aqueduct versions.
ENG-2067
Run local install and manually downgrade `version` file. Validated that we are attempting to install.
Also validated we are not attempting to install if there's no version mismatch.
=> Eng 2067 Update conda base environments when updating aqueduct

sdk/aqueduct/decorator.py
This PR Fix error message when @check or @metric is called with no inputs. When the metric and function is called with no input, the SDK side will error out.
https://linear.app/aqueducthq/issue/ENG-1767/fix-error-message-when-check-or-metric-is-called-with-no-inputs
=> Fix error message when check or metric is called with no inputs

src/golang/cmd/executor/executor/database.go, src/golang/cmd/server/handler/archive_notification.go, src/golang/cmd/server/handler/list_notifications.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/handler/register_airflow_workflow.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/models/views/dag_result.go, src/golang/lib/repos/dag_result.go, src/golang/lib/repos/sqlite/dag_result.go, src/golang/lib/repos/tests/dag_result.go, src/golang/lib/workflow/utils/database.go
This PR replaces the notification DB readers and writer usage with the repo.
It also adds a new API to the DAGResultRepo for getting the workflow metadata associated with a DAGResult. This is necessary for the ListNotifications handler. There is a test case added for this new method. 
It also does a fix to a different test case.
ENG 2053
=> [7/N] Replaces notification DB reader/writer with repo

src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/discover.go, src/golang/cmd/server/handler/get_artifact_versions.go, src/golang/cmd/server/handler/list_operators_for_integration.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/cmd/server/server/cron.go, src/golang/cmd/server/server/database.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/models/views/artifact_result.go, src/golang/lib/models/views/id.go, src/golang/lib/models/views/operator.go, src/golang/lib/models/views/operator_result.go, src/golang/lib/models/views/workflow.go, src/golang/lib/repos/artifact.go, src/golang/lib/repos/artifact_result.go, src/golang/lib/repos/dag.go, src/golang/lib/repos/operator.go, src/golang/lib/repos/operator_result.go, src/golang/lib/repos/sqlite/artifact.go, src/golang/lib/repos/sqlite/artifact_result.go, src/golang/lib/repos/sqlite/dag.go, src/golang/lib/repos/sqlite/operator.go, src/golang/lib/repos/sqlite/operator_result.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/workflow.go
This PR takes all of the adhoc "custom" queries and turns them into the relevant `Views` and `Repos`. The motivation was to make these queries as clean as possible in terms of fitting into a Repo that made logical sense, rather than having a collection of adhoc queries. 
TODO: Writing the database integration tests.
ENG 1903
=> [15/N] Replaces custom queries with repos

src/ui/common/src/components/workflows/ReactFlowCanvas.tsx
This PR updates the logic behind when fitView() is called on the workflow details page and makes it so that the DAG view no longer jumps around when users select a node to view.
ENG-1878
https://www.loom.com/share/bd357e19051e477e9720233eba2a8428
=> Fixes bug where canvas position is reset after clicking into a node.

integration_tests/sdk/conftest.py, integration_tests/sdk/delete_workflow_test.py, integration_tests/sdk/flow_test.py, integration_tests/sdk/lazy_execution_test.py, integration_tests/sdk/load_test.py, integration_tests/sdk/sql_integration_test.py, integration_tests/sdk/utils.py, integration_tests/sdk/validator.py, sdk/aqueduct/integrations/save.py
This is the testing follow-up of: https://github.com/aqueducthq/aqueduct/pull/769
Because of the Save API change, we should now abstract away our `save()` helper. This PR does the following:
- Adds a `save()` helper that should be used by the test cases (instead of directly using the SDK's Save API).
- Add a flag `--deprecated`, which allows us to continue to provide coverage to code paths that are deprecated, but need to be temporary support. See `save()` for how this switch works.
- Adds a `Validator` class instance (see `validator.py`), which can be included in tests that need it. This Validator can be used to check certain things about the flow after `publish_flow_test()` is called. The reason I made this a class is 1) it's easier to include as a fixture and 2) its easier to organize …
=> Update the integration tests to support the new Save API

scripts/install_local.py, src/golang/cmd/migrator/migrator/register.go, src/golang/cmd/migrator/versions/000022_backfill_python_type/main.go, src/golang/cmd/migrator/versions/000022_backfill_python_type/utils.go, src/golang/lib/models/schema.go, src/python/aqueduct_executor/migrators/backfill_python_type_000022/execute.py, src/python/aqueduct_executor/migrators/backfill_python_type_000022/main.py, src/python/aqueduct_executor/migrators/backfill_python_type_000022/serialize.py, src/python/aqueduct_executor/migrators/backfill_python_type_000022/spec.py, src/python/bin/aqueduct
This PR performs a data migration that backfills the python type of previously created artifact results. I manually ran a regression test and verified that the python types were successfully backfilled.
=> Backfill python type of previously created artifact results

src/ui/common/src/components/integrations/dialogs/dialog.tsx
This PR shows users an error message when trying to create an integration with a name that is not unique.
ENG-1967
https://www.loom.com/share/4f283af74fe641aca97d8dde04b16851
=> Eng 1967 unique integration names

integration_tests/sdk/package_test.py, sdk/aqueduct/__init__.py
This PR fixes the issue that we could import `CheckSeverity` and `LoadUpdateMode` directly from `aqueduct` package. We also added an integration test to ensure all APIs linked to `aqueduct` is accessible.
ENG-2097
The added test failed before fix, passed after fix.
=> Fix SDK imports for CheckSeverity and LoadUpdateMode

src/ui/common/src/components/workflows/WorkflowSettings.tsx
As title.
Before:
After:
https://linear.app/aqueducthq/issue/ENG-1927/fix-bug-where-delete-confirmation-dialog-is-massive
=> Fix bug where delete confirmation dialog is massive

src/ui/common/src/components/pages/workflows/components/CheckItem.tsx, src/ui/common/src/components/pages/workflows/index.tsx
Fixes two bugs with new workflows page:
1. Fix crash when no workflows are present. 
3. Fixes issue where warning checks aren't rendered as warning icons in workflows and data tables.
https://www.loom.com/share/aee6e427ff304f81b397c1040ea1cdcd
=> Bugfixes: Workflows Page and Data Page

src/python/bin/aqueduct
=> Fix aqueduct bin script to only run conda update if the user has conda installed

src/ui/common/src/utils/engine.ts, src/ui/common/src/utils/operators.ts, src/ui/common/src/utils/workflows.tsx
This isn't used anywhere in the UI, but just adding it as important context once we start showing the engine type on the UI :) These fields are populated correctly once this PR merges.
ENG-2039
=> [UI] Add engine_config field to operator spec

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/edit_integration.go, src/golang/cmd/server/handler/handler.go, src/golang/cmd/server/handler/test_integration.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/lib/collections/shared/types.go, src/golang/lib/collections/utils/utils.go, src/golang/lib/cronjob/cronjob.go, src/golang/lib/database/database.go, src/golang/lib/execution_environment/dependency.go, src/golang/lib/job/spec.go, src/golang/lib/vault/vault.go, src/golang/lib/workflow/operator/connector/github/manager.go, src/golang/lib/workflow/operator/connector/github/unimplemented.go, src/golang/lib/workflow/operator/connector/github/utils.go, src/golang/lib/workflow/operator/operator.go
Did one simple pass over places that we define errors inline that can be very easily fixed. This does not cover all the places in which we do this - the remaining bad error patterns will require a bit more refactoring, potentially similar to how JobError does it now. This does cleanup the codebase a little bit though.
=> Cleanup some low-hanging bad error patterns in the golang codebase

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/edit_integration.go, src/golang/cmd/server/handler/handler.go, src/golang/cmd/server/handler/test_integration.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/lib/collections/shared/types.go, src/golang/lib/collections/utils/utils.go, src/golang/lib/cronjob/cronjob.go, src/golang/lib/database/database.go, src/golang/lib/execution_environment/dependency.go, src/golang/lib/job/errors.go, src/golang/lib/job/job.go, src/golang/lib/job/k8s.go, src/golang/lib/job/lambda.go, src/golang/lib/job/poll.go, src/golang/lib/job/process.go, src/golang/lib/job/spec.go, src/golang/lib/vault/vault.go, src/golang/lib/workflow/operator/base.go, src/golang/lib/workflow/operator/connector/github/manager.go, src/golang/lib/workflow/operator/connector/github/unimplemented.go, src/golang/lib/workflow/operator/connector/github/utils.go, src/golang/lib/workflow/operator/operator.go
Finishes what I started a few weeks ago when dealing with job manager errors coming from K8s and Lambda that were user-facing.
Additionally, we want to move away from the 
```
ErrPollJobTimeout = errors.New("Reached timeout waiting for the job to finish.")
```
pattern, since the stack trace that error captures is completely useless for our debugging (since stack trace capture happens at error creation time). By wrapping these errors on the fly in a JobError, we make it possible to both 1) record useful stack trace information when returning errors from the job manager and 2) perform any conditional checks on the specific type of error with `JobError.Code()`.
ENG-2009
- `skip_integration_test`: Skips integration tests (Should be used when …
=> Refactor job manager interface to always return a JobError

src/ui/common/src/components/pages/workflows/components/MetricItem.tsx, src/ui/common/src/components/workflows/nodes/MetricOperatorNode.tsx
This PR reduces the number of significant figures for metrics on data list page and workflows list page.
ENG-2124
Screenshot:
=> ENG-2124: Reduce sigfigs on the metrics preview in data list page and workflows list page

src/ui/common/src/components/tables/PaginatedTable.tsx, src/ui/common/src/components/workflows/artifact/content.tsx, src/ui/common/src/handlers/getArtifactResultContent.ts, src/ui/common/src/reducers/integration.ts, src/ui/common/src/reducers/workflow.ts, src/ui/common/src/utils/data.ts
This PR introduce necessary UI change to render `bson_table` serialization type in UI, as introduced in #820 .
ENG 2104
Verified with a mongo workflow with extract, function, and load operator. We checked the table renders in following pages: table preview in integration page, artifact content preview, and artifact versions in data page.
table preview (does not reproduce original problem):
artifact preview:
data page (technically this is not affected by this change):
=> Eng 2104 [2/2][ui] Fix a bug where mongo collection preview crashes

src/ui/common/src/components/pages/integration/id/index.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/utils/integrations.ts
Remove data section for compute integrations because compute integrations don't store data.
Updated categories in integrations page so they are not hardcoded strings.
ENG 2061
=> ENG 2061 Remove data section for compute integrations

integration_tests/sdk/checks_test.py, integration_tests/sdk/conftest.py, integration_tests/sdk/delete_workflow_test.py, integration_tests/sdk/error_handling_test.py, integration_tests/sdk/flow_test.py, integration_tests/sdk/lazy_execution_test.py, integration_tests/sdk/load_test.py, integration_tests/sdk/local_test.py, integration_tests/sdk/metrics_test.py, integration_tests/sdk/mixed_compute_test.py, integration_tests/sdk/naming_test.py, integration_tests/sdk/no_input_test.py, integration_tests/sdk/operator_hierarchy_test.py, integration_tests/sdk/operator_test.py, integration_tests/sdk/param_test.py, integration_tests/sdk/preview_test.py, integration_tests/sdk/sql_integration_test.py, integration_tests/sdk/table_artifact_test.py
First step in unlocking cross-data-integration tests is to get rid of the relational db assumptions that we've encoded in the naming of things, eg. calling everything `db`.
Additionally, I took this opportunity to convert the `data_integration` fixture into an actual integration object, instead of a string. This saves one line of `data_integration = client.integration(data_integration_name)` in each test case.
=> [1/2] Make `data_integration` terminology consistent in the SDK integration tests

src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx
Resets state of workflow settings dialog back to initial state on dialog close when user does not save changes
ENG-1857
https://www.loom.com/share/de75aeec569345e7a756520e4fbf2ece
=> ENG-1857 Resets workflow settings dialog changes on close if changes are not saved.

src/ui/common/src/components/pages/workflows/components/MetricItem.tsx, src/ui/common/src/handlers/responses/dag.ts
Update text.
Fix bug where ops list fails loudly when it has undefined elements.
ENG-2123
https://www.loom.com/share/51054c3ebc514b11abe4f239decada01
Bug: 
https://user-images.githubusercontent.com/30596854/208993509-8177a7a0-e083-4ffd-80e9-aad7f3387031.mov
Fixed:
https://user-images.githubusercontent.com/30596854/208993818-1bc54732-8980-4b50-96e7-fa73d9e7774b.mov
Feature:
https://user-images.githubusercontent.com/30596854/208993510-4707184b-7099-41e8-84e2-ae5eb8d160e0.mov
=> Eng 2123 tweak text to expand-collapse checks

src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx
Make the detail sheets full width.
Encountered errors retrieving contents due to storage issues (Object does not exist in storage.) but that is an unrelated issue.
ENG-2132,  ENG-2135, ENG-2134, ENG-2133
Before:
Check
Metric
Artifact
After:
=> Fullwidth artifact, check, metric pages

src/ui/common/src/components/layouts/NavBar.tsx
This PR removes the Account popover in the navigation bar that appeared when users clicked the settings gear.
Users can now navigate to the Account page simply by clicking the settings gear.
ENG-2130
https://www.loom.com/share/de15a7714f1c4570ab48236b16f18844
=> ENG-2130 Remove Settings Account Popover

src/ui/common/src/components/workflows/WorkflowSettings.tsx
Only fixes the bug. Does not add the saved objects to the workflow settings dialog.
=> Fix UI bug where workflow saved objects were not being displayed when the workflow was deleted.

src/ui/common/src/utils/integrations.ts
This PR replaces the light logo being used in the engine column with the dark logo.
ENG-2121
Screenshot:
=> ENG-2121: Use dark logo for Aqueduct engine.

src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/workflows/artifact/check/history.tsx, src/ui/common/src/components/workflows/artifact/metric/history.tsx
This PR makes the width of the history list consistent for Check and Metric history list items. Please see loom demo for more details.
ENG-2136
https://www.loom.com/share/9053ee3e1f4f41f180bb7654b2394d3f
=> ENG-2136 Make History List Item Width Consistent

integration_tests/backend/test_reads.py, integration_tests/sdk/checks_test.py, integration_tests/sdk/conftest.py, integration_tests/sdk/constants.py, integration_tests/sdk/data_objects.py, integration_tests/sdk/delete_workflow_test.py, integration_tests/sdk/error_handling_test.py, integration_tests/sdk/flow_test.py, integration_tests/sdk/lazy_execution_test.py, integration_tests/sdk/load_test.py, integration_tests/sdk/local_test.py, integration_tests/sdk/metrics_test.py, integration_tests/sdk/mixed_compute_test.py, integration_tests/sdk/naming_test.py, integration_tests/sdk/no_input_test.py, integration_tests/sdk/operator_hierarchy_test.py, integration_tests/sdk/operator_test.py, integration_tests/sdk/param_test.py, integration_tests/sdk/preview_test.py, integration_tests/sdk/relational.py, integration_tests/sdk/sql_integration_test.py, integration_tests/sdk/table_artifact_test.py, integration_tests/sdk/utils.py, integration_tests/sdk/validator.py, sdk/aqueduct/constants/enums.py, sdk/aqueduct/error.py, sdk/aqueduct/models/operators.py
This PR makes all the changes necessary to run the full suite of SDK integration tests against the S3 data integration: eg. `pytest ... --data data_s3` passes for an S3 integration named "data_s3".
NOTE: an important assumption is that the S3 integration already has the following tables populated (from the demo db).
These dataframes are all serialized in parquet format. Diversity of data format is not what this test suite is responsible for.
There will eventually be a script that populates S3 automatically for you from the demo db if you don't have them there yet. Note that the table name in sqlite matches the filepath of the object in S3 exactly.
Notable changes:
- Introduce an `extract()` helper in our integration tests that returns a TableArtifact from any supported integration (that …
=> [2/3] Run SDK Integration Tests against S3 [Testing Changes]

src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/reducers/workflow.ts, src/ui/common/src/utils/operators.ts, src/ui/common/src/utils/workflows.tsx
The backend bug fixes in https://github.com/aqueducthq/aqueduct/pull/833 caused two backend routes used by the UI to change, specifically `delete_workflow.go` and `list_workflow_objects`. This PR updates the UI to be compatible with the new backend, and ensures that we can now display objects in S3 and delete them.
ENG-2110
https://www.loom.com/share/4e581cde84d34856b05f23e42923c4d4
=> [3/3] Run SDK Integration Tests against S3 [UI Fix]

src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/pages/integrations/index.tsx
The issue with using Grid which keeps the column count constant and resized the elements within the columns. However, our elements (integration icons) are constant size so it looks strange. I switched to using a flexbox. Now the grid of integrations will be one row if the screen is wide enough.
ENG-2137
I show how the page performs on different screen sizes by zooming in and zooming out of the page. As you can see, as the screen grows larger (zooming out) there are more columns in the grid until there is just one row.
https://user-images.githubusercontent.com/30596854/210420400-258035a1-0bd3-4cea-81a7-0f06bf97cb46.mov
- …
=> Eng 2137 make integrations page full width

src/ui/common/src/components/layouts/menuSidebar.tsx
This PR adds a small text showing the server's current version number in the bottom of the menu sidebar.
ENG-2176
Screenshot:
=> ENG-2176 Show version number on bottom of navigation bar.

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, .github/workflows/run-notebooks.yml, src/golang/cmd/server/main.go, src/golang/cmd/server/middleware/usage/constants.go, src/golang/cmd/server/middleware/usage/models.go, src/golang/cmd/server/middleware/usage/usage.go, src/golang/cmd/server/server/aqueduct_server.go, src/golang/go.mod, src/golang/go.sum, src/python/bin/aqueduct
This PR enables basic usage stats collection and reporting. Currently, for each request, we collect 1) a privacy-preserving ID of the user's host machine, 2) the name of the route being hit (any uuid in the route is being stripped away), and 3) the latency of the request. We can add more stats as necessary. This usage data is then sent to a Loki server, which is a log aggregation system that I've been playing around with.
Usage data collection is enabled by default, and can be disabled by running `aqueduct start` with `--disable-usage-report`.
=> Implement basic usage stats collection and reporting

src/ui/common/src/components/pages/artifact/id/index.tsx
This PR hides artifact previews when the artifact is cancelled.
ENG-1880
https://www.loom.com/share/a78d9b2a5a71457090a417439cbb619a
=> ENG-1880 Hide preview when artifact is cancelled.

src/ui/common/src/components/pages/data/index.tsx, src/ui/common/src/components/pages/workflows/index.tsx, src/ui/common/src/components/tables/PaginatedSearchTable.tsx
This PR saves the selected number of rows for the workflows page table and the data page table. When users refresh the page, they will see that the number of rows selected persists.
ENG-2158
https://www.loom.com/share/74cdeaf29ee6431e912b77c0c304d801
=> ENG-2158 Persist number of rows between page refreshes on workflows page and data page tables.

integration_tests/sdk/README.md, integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/data_integration_tests/conftest.py, integration_tests/sdk/data_integration_tests/relational_test.py, integration_tests/sdk/data_integration_tests/save.py, integration_tests/sdk/shared/demo_db.py, integration_tests/sdk/shared/utils.py, sdk/aqueduct/backend/response_models.py, sdk/aqueduct/flow.py, sdk/aqueduct/integrations/sql_integration.py
Initializes the SDK data integration test suite and adds test coverage for relational databases, tested and allowed for SQLite and Snowflake.
The point of SDK Data Integration Tests is to test the SDK Integration API with *completeness*. Our Aqueduct Tests can be too generic to cover all the edge cases for our Integration API, which is different for each integration type.
The Data Integration Tests are organized such that each test file is responsible for testing a particular integration type. See `integration_tests/sdk/data_integration_tests/conftest.py` for how this is enforced. Both Aqueduct and Data Integration Tests shared the fixtures and configurations in `integration_tests/sdk/conftest.py`.
ENG-2113
- `skip_integration_test`: Skips …
=> [2/3] Add Data Integration Test Suite coverage for SQLite and Snowflake

scripts/install_local.py, src/golang/cmd/server/main.go, src/python/bin/aqueduct
When running server with `--env` , we will cache the env into a file, and the user doesn't need to specify the env again in the future. If the user wants to update the env, they will run the server with `--env` again and the cache will be updated. If the cached entry doesn't exist, the `prod` env will be used.
=> Cache server env for usage stats collection

src/ui/common/src/components/workflows/StatusBar.tsx
This PR hides status items of type 'Parameter' in the Workflow Status Bar.
ENG-1961
https://www.loom.com/share/b2b96345e81c42edbc0a26b31f6f9d6d
=> ENG-1961 Hide Parameters in Workflow Status Bar

src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/components/workflows/triggerSourceSelector.tsx, src/ui/common/src/utils/workflows.tsx
This PR adds UI support for showing the source workflow in the settings page if the workflow is set to be triggered after a source. Note that this PR is just 1/2 of the UI changes needed for the feature. There is a separate task here that is tracking changes for allowing users to change the workflow schedule to use cascading updates from the UI. This PR is separated just for reviewing purposes.
ENG 2180
https://www.loom.com/share/4813a0d6239c4dfda62a337f843fa847
=> Adds UI support for showing the source workflow in the settings

src/golang/cmd/server/handler/register_workflow.go, src/golang/lib/workflow/validate.go
This PR adds validation to workflow schedules as part of registering a workflow. It prevents using a workflow running on Airflow as the source, since we cannot execute new workflow runs at the end of execution for a non self-orchestrated engine, such as Airflow.
ENG 2200
=> [3/3] Prevents setting an airflow workflow as source for a cascading trigger

src/golang/cmd/executor/executor/workflow.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/lib/workflow/validate.go
This PR adds support for triggering target workflows at the end of each workflow run. This is necessary to support cascading updates.
ENG 82
=> [2/3] Implements triggering target workflows at end of run execution

integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/shared/utils.py, sdk/aqueduct/client.py, sdk/aqueduct/constants/enums.py, sdk/aqueduct/models/dag.py, sdk/aqueduct/utils/utils.py
This PR adds support for scheduling a workflow to run based on a cascading update. The `publish_flow` API is changed to now allow users to set a `source_flow_id`. If this field is set then the cron schedule is ignored.
ENG 2179
=> Adds SDK support for scheduling a workflow to run after a source

integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/shared/utils.py, sdk/aqueduct/client.py, sdk/aqueduct/constants/enums.py, sdk/aqueduct/models/dag.py, sdk/aqueduct/utils/utils.py, src/golang/cmd/executor/executor/workflow.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/lib/collections/workflow/types.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/tests/workflow.go, src/golang/lib/repos/workflow.go, src/golang/lib/workflow/validate.go
This PR adds the `SourceID` field to the `Workflow.Schedule` column. This is necessary to support cascading updates. It also adds a method in the `Workflow` repo to get all target workflows for a given workflow. This is used to perform cascading updates at the end of workflow execution.
=> [1/3] Adds SourceID field to Workflow.Schedule column

integration_tests/sdk/aqueduct_tests/delete_workflow_test.py, src/golang/lib/engine/aq_engine.go
This PR adds support for changing the schedule trigger of a target workflow to `MANUAL` when its source workflow is deleted.
ENG 2197
=> Changes target workflow trigger to manual when source workflow is deleted

src/golang/cmd/server/middleware/usage/usage.go
When we panic, it kills the whole server, which is not what we want. Now we just log the error and return, so the server keeps running.
=> Don't panic when error sending stats to Loki

integration_tests/sdk/aqueduct_tests/delete_workflow_test.py, src/golang/cmd/server/handler/register_workflow.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/graph/directed.go, src/golang/lib/graph/node.go, src/golang/lib/repos/sqlite/workflow.go, src/golang/lib/repos/tests/workflow.go, src/golang/lib/repos/workflow.go, src/golang/lib/workflow/validate.go
This PR prevents cycles in cascading workflows.
ENG 2198
Testing: I manually tested to ensure that an error is returned on the SDK when a user forms a cycle. I am currently adding integration test cases for this (and also add unit tests for the graph cycle detection code).
=> Prevents cycles in cascading workflows

src/ui/common/src/components/pages/workflows/components/CheckItem.tsx, src/ui/common/src/components/pages/workflows/components/MetricItem.tsx
Updated table row to have a set height but this resulted in a bug that causes the text to overflow when maximizing the checks or metrics list. This bug is resolved by setting the MIN height to that height instead.
N/A
Before:
After:
=> Bugfix: Fix table row height

.github/workflows/periodic-integration-tests.yml
Periodic tests have been failing with the [following error](https://github.com/aqueducthq/aqueduct/actions/runs/3884579549/jobs/6627331601#step:4:6):
```
Run rm requirements.txt
rm: cannot remove 'requirements.txt': No such file or directory
Error: Process completed with exit code 1.
```
This removes the step causing the error. Results of this test can be found here: https://github.com/aqueducthq/aqueduct/actions/runs/3895323545/jobs/6650495413
=> Removes erroring step from periodic integration test

src/ui/common/src/components/pages/metric/id/index.tsx
Changed the metric details page to get the workflow name from the same place as check, operator, and artifact details page.
ENG 2173
Bug
https://user-images.githubusercontent.com/30596854/212381175-6971d8f7-de08-401d-afc9-bac9d44de444.mov
Bugfix
https://user-images.githubusercontent.com/30596854/212381156-6ced0457-827f-40a3-b8e5-aa748fde4d82.mov
=> ENG 2173 Metric Details Page does not show Workflow Name in Header

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, integration_tests/sdk/README.md
Updates our github actions and testing README with new commands that rly on the test configuration file instead of environmental variables.
Tested by running the integration test GH action manually against https://github.com/aqueducthq/aqueduct/pull/883
ENG-2138
=> [2/2] Update Github Actions and README to reflect test run changes

scripts/release/doc.sh, scripts/release/update_helm.sh
This PR adds release scripts to automate help and doc updates. These scripts does not depend on where they run (since working dir is modified internally) so that it's easier to integrate into larger scripts in the future.
Reference to old steps https://www.notion.so/aqueducthq/Runbook-Cutting-an-OSS-Release-b72400b7584845f0b0b4ff84bab4aedc . See deprecated contents for helm and doc updates
Usage (also reflected in new release checklist: https://www.notion.so/aqueducthq/Template-Release-Version-Checklist-9d694d4857634ce5918b0a0971c17e79):
```
sh update_helm.sh <VERSION NUMBER>
sh doc.sh
```
ENG-2217 ENG-2218
Corresponding parts for v0.1.9 release are done using these two scripts
- `skip_integration_test`: Skips integration tests (Should be …
=> Add release scripts for helm updates and doc updates

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, .gitignore, integration_tests/sdk/README.md, integration_tests/sdk/conftest.py, integration_tests/sdk/setup_integration.py, integration_tests/sdk/shared/utils.py, integration_tests/sdk/test-config-example.yml, sdk/aqueduct/integrations/connect_config.py
There are some significant test behavior changes that arise from this PR:
We finally introduce the concept of a test configuration file, located at `integration_tests/sdk/test-config.yml`. I've supplied an example format for people to copy over in `test-config-example.yml`. I imagine we'll have the full one stored in an S3 bucket somewhere.
This test configuration file will contain the server address and apikey - we'll no longer need to use environmental variables. The configuration file also contains entries for the different data integrations we will run the tests against. Every test case will run against every data integration defined in this file, unless the `--data` command line flag is supplied! 
Follow-up: Update our github actions and documentation to reflect these new changes. …
=> [1/2] Update SDK Integration Tests to run automagicky against various data integrations

.github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, integration_tests/sdk/README.md, integration_tests/sdk/run_tests.py, manual_qa_tests/workflows/succeed_parameters.py
Similar to how `run_linters.py` made our lives easier, `run_tests.py` does the same thing for our SDK Integration Tests in the test directory.
=> Add convenience integration test running script

src/ui/common/src/components/layouts/default.tsx, src/ui/common/src/utils/notifications.ts
This was happening because we forgot to put an empty dependency array to `useEffect`, so it keeps calling the route every time the UI re-renders. By putting the empty dependency array, it only calls the route when the component mounts.
=> Fix bug where the UI keeps hitting the notification route

integration_tests/backend/test_reads.py, integration_tests/sdk/README.md, integration_tests/sdk/aqueduct_tests/conftest.py, integration_tests/sdk/aqueduct_tests/naming_test.py, integration_tests/sdk/data_integration_tests/conftest.py, integration_tests/sdk/data_integration_tests/relational_data_validator.py, integration_tests/sdk/setup_integration.py, integration_tests/sdk/shared/validation.py, integration_tests/sdk/shared/validator.py, sdk/aqueduct/integrations/mongodb_integration.py, sdk/aqueduct/integrations/s3_integration.py, sdk/aqueduct/integrations/sql_integration.py, sdk/aqueduct/models/integration.py
It's pretty annoying to have to do `integration._metadata.name`, `integration._metadata.service` for the name and types of integrations. This PR just makes basic fetches for these, the same way we do on the BaseArtifact class.
=> [SDK] Add some convenience get helpers to our SDK Integration Class

src/ui/common/src/components/cards/GettingStartedTutorial.tsx, src/ui/common/src/components/layouts/menuSidebar.styles.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx
=> Show option names on the sidesheet and remove the Aqueduct logo on the Home page

src/ui/common/src/components/layouts/default.tsx, src/ui/common/src/components/pages/metric/id/index.tsx, src/ui/common/src/components/workflows/StatusBar.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx
Fixes bug where the workflow details page keeps rendering over and over again, causing a MaximumUpdateDepth error message to appear in the browser console.
ENG-2290
https://www.loom.com/share/790bedef491e4179b56c41d1d0d5b0c1
=> ENG-2290: Fix bug where workflow details page renders over and over.

integration_tests/sdk/conftest.py, integration_tests/sdk/shared/utils.py
See title. Pretty easy fix.
Tested by running against Snowflake and checking that no new tables were left behind.
=> Delete external data during test teardown in SDK Integration Tests

src/golang/lib/job/k8s.go, src/golang/lib/k8s/jobs.go
This was because there's a small time gap between launching a job and spinning up a pod. We capture this case and return a pending status, so that the next time we poll, the pod will be created. I tested manually and it worked, so hopefully it will fix the issue @kenxu95 you ran into as well.
=> Fix a bug where operator execution fails when running on k8s

src/golang/cmd/server/handler/get_operator_result.go
=> Fix bug where get operator result go routine fails to check for error

src/ui/common/src/components/workflows/StatusBar.tsx
This PR resolves an issue where unnecessary backticks and dollar signs appeared in the WorkflowStatusBar's WarningListItem.
This issue happened due to treating the title as a string and not a react component (we use a component here to support more advanced title styling).
ENG-2134
=> ENG-2134 Remove Unnecessary Backticks in WorkflowStatusBar Warning list item

src/python/aqueduct_executor/operators/connectors/data/relational.py
This PR fixes a bug where saving artifacts to relational DBs (specifically Postgres and Redshift) was failing for columns with large strings. The fix is to manually determine the appropriate VARCHAR size instead of letting Pandas default it to `255` bytes for all columns.
ENG 2319
Confirmed that all data_integration tests pass for SQLite, Snowflake, S3.
=> Fixes bug where saving to relational DBs failed for large string cols

src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/cards/slackCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/slackDialog.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/index.tsx, src/ui/common/src/utils/integrations.ts
This PR adds all required UI work to allow user connecting to slack integration. it's very similar to  #897 and reuses the notification level selector.
Tested the following features are working properly:
* connect
* test-connect
* edit
* delete
ENG-2191
Integration list page:
Connect dialog:
Integration detail page:
=> [2/2][UI] Eng 2191 Allow user to connect to slack integration

src/golang/cmd/server/handler/connect_integration.go, src/golang/go.mod, src/golang/go.sum, src/golang/lib/collections/integration/constants.go, src/golang/lib/lib_utils/utils.go, src/golang/lib/models/shared/integration_config.go, src/golang/lib/notification/slack.go, src/golang/lib/workflow/operator/connector/auth/static_config.go, src/ui/common/src/components/integrations/cards/card.tsx, src/ui/common/src/components/integrations/cards/detailCard.tsx, src/ui/common/src/components/integrations/cards/slackCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/slackDialog.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/index.tsx, src/ui/common/src/utils/integrations.ts
This PR adds backend changes for slack integration. It's very similar to #898 , and covers the necessary auth check when connecting to slack.
A follow up task is https://linear.app/aqueducthq/issue/ENG-2315/[m3]-detect-if-slack-token-has-channel-access-on-auth-time , that we will add checks to ensure the token has permission to all specified channels. We decide to do this later as we will explore slack go APIs more heavily in the next milestone.
ENG-2191
See #910 
=> [1/2][Backend] Eng 2191 add slack integration to backend

.github/workflows/integration-tests.yml
Previous fix #927 has problem with schema updates since it uses 'current' upload script with production binaries. Therefore we have to revert the change.
This PR adds additional fix for the SQLAlchemy dependency issue by pin the version in github action. We need to rethink how to streamline these version updates in future.
=> Fix integration tests with sqlalchemy hack

sdk/aqueduct/backend/api_client.py, sdk/aqueduct/integrations/sql_integration.py
This PR fixes a bug in the SDK when listing tables in big query. We were previously using an explicit SQL query to look up tables in Big Query, but this query does not work without providing additional information about the Google Cloud project ID. Instead of surfacing this information to the SDK client and having to construct a query, it is better to use our `integration/[]/objects` endpoint, since this achieves the same functionality without having to maintain hardcoded SQL queries. 
We should do the same for the other integrations as well. This task is documented [here](https://linear.app/aqueducthq/issue/ENG-2358/refactor-sdk-list-tables-implementation-to-use-the).
ENG 2340
I verified that the `list_tables` API works for a Big Query integration via a test notebook. Full testing of big …
=> Fixes bug for listing big query tables

src/golang/cmd/server/handler/refresh_workflow.go, src/golang/cmd/server/server/cron.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/engine/aq_engine.go, src/golang/lib/workflow/validate.go
This PR adds support for cascading update-based schedules for workflows that run on Airflow. We still do not support using an Airflow workflow as the source workflow. It can only be a target workflow.
ENG 2202
TODO: Need to manually verify this on an Airflow cluster
=> Adds cascading updates support for workflows running on Airflow

src/ui/common/src/components/pages/workflows/components/MetricItem.tsx
-This PR fixes a bug where failing metrics show as NaN in metric preview list.
-Also fixes another issue where the metric previews were showing as status indicators.
ENG-2308
Here we see a failed metric that is being rendered as it's actual status, which is 'canceled'
=> ENG-2308 Metric Preview Fixes

sdk/aqueduct/models/dag.py, sdk/aqueduct/utils/utils.py
Set restriction on usage of Databricks integration.
1. Can only be used to preview by setting aq.global_config({'engine':<databricks_integration>})
2. Can't be mixed with other compute integrations.
Running 
```
#With no global default set
@op(engine='d4')
def bad_op(df):
5 / 0
return df
output = bad_op()
```
results in 
```
InvalidUserActionException: In order to use 
Databricks while previewing operators, please set 
aqueduct.global_config({'engine': '<databricks_integration>'})
```
as expected.
=> Set restriction on sdk for using Databricks Integration

src/ui/common/src/components/pages/data/index.tsx
This PR adds a loading spinner to the data list page and improves null checking while waiting for data to be fetched.
ENG-2264
https://www.loom.com/share/8f402aea4e5547d588309e9ea1be4395
=> ENG-2264 Data List Page Loading Fixes

.github/actions/setup-server/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/integration-tests.yml, .github/workflows/periodic-integration-tests.yml, integration_tests/sdk/conftest.py, integration_tests/sdk/test-config-example.yml
This PR does the following:
- Updates our pre-merge integration tests to pick a python version at random, instead of iterating over them all. This mechanism will be useful in the future for our other tests.
- Refactors common server setup and upload artifact functionality into their appropriate composite actions, which makes the main yml file much cleaner.
- For the upload artifact composite action, you must specify a prefix, which allows for deduplication so that the same artifact (eg. server logs) can be uploaded at the end of a github workflow that has multiple parallel jobs.
- Also requests a beefier machine - with 8 cores we can finish these tests in 10 minutes.
ENG-2350
- `skip_integration_test`: Skips integration tests (Should be …
=> [2/2] [GH Actions] Update Pre-merge Integration Tests to use credential and config files

integration_tests/no_concurrency/sdk/requirements_test.py, integration_tests/sdk/setup_integration.py, manual_qa_tests/deploy_example.py, sdk/aqueduct/backend/api_client.py, sdk/aqueduct/client.py, sdk/aqueduct/integrations/connect_config.py, sdk/aqueduct/integrations/salesforce_integration.py, sdk/aqueduct/integrations/sql_integration.py, sdk/aqueduct/models/config.py, src/python/aqueduct_executor/operators/connectors/data/extract.py, src/python/aqueduct_executor/operators/connectors/data/spark/s3.py, src/python/aqueduct_executor/operators/connectors/data/spark/snowflake.py, src/python/aqueduct_executor/operators/function_executor/install_requirements.py, src/python/aqueduct_executor/operators/spark/utils.py, src/python/aqueduct_executor/operators/utils/storage/s3.py, src/python/aqueduct_executor/operators/utils/utils.py
Previously we only allowed users to connect to BigQuery from the SDK if they provided a string of the svc account credentials. This is not user-friendly so we should allow them the option of specifying a file, since typically these credentials are downloaded in a JSON file.
This was also a pre-req for our integration tests, since it is easier to specify a credentials file instead of copying a long JSON string in the test-credentials file.
ENG 2386
See the following notebook commands:
=> Allows user to provide filepath to BigQuery credentials when connecting via SDK

integration_tests/sdk/aqueduct_tests/error_handling_test.py, src/python/aqueduct_executor/operators/function_executor/execute.py, src/python/aqueduct_executor/operators/spark/execute_function.py
This PR fixes a bug in how we handle the following types of errors:
1. There is an error in the user code, i.e. an exception is thrown.
2. The number of outputs do not match what was expected.
Previously, we were prioritizing Error #2 over #1 and escalating that to the user. The correct use case is to catch Error #1 first and if so provide the user with the appropriate stack trace.
This PR also adds a new integration test case for this specific behavior.
ENG 2333
=> Fixes bug in handling user error with mismatch in output count

integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/conftest.py, integration_tests/sdk/shared/flow_helpers.py, integration_tests/sdk/shared/globals.py, integration_tests/sdk/shared/utils.py, sdk/aqueduct/client.py, sdk/aqueduct/tests/flow_test.py, sdk/aqueduct/utils/utils.py
This PR allows users to identify flows using the name instead of just an ID.
ENG 1738
- Added unit tests and integration test cases
=> Allows use of flow name instead of id in SDK

src/ui/common/src/components/pages/data/index.tsx
This PR fixes a bug where metrics rendered as a status indicator instead of a value when shown on the data page.
ENG-2406
=> ENG-2406 Fix for metrics not showing properly on the data page.

src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx, src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/ReactFlowCanvas.tsx, src/ui/common/src/components/workflows/WorkflowSettings.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx
This PR adds two tabs to the workflow details page: Details and Settings.
The details tab shows the same DAG contents as before and the settings tab shows the contents of the settings modal inside of a tab view.
ENG-2171
https://www.loom.com/share/40b94a61520a420896c28fc013a45032
=> ENG-2171 Add Tabs to Workflow Details Page

src/golang/lib/storage/file.go, src/golang/lib/storage/gcs.go, src/golang/lib/storage/s3.go, src/golang/lib/storage/storage.go, src/golang/lib/workflow/utils/storage.go
There're two reasons for the slowdown:
1. The APIs we were using to read and write from S3 on the Golang side were inefficient, and I replaced both with a much more efficient version.
2. When checking if a key exists, we were invoking GET on the key of the artifact's payload, which is both unnecessary and has high overhead because the payload can be big. So I added another API called `Exists` to the storage interface that just checks if the key is there or not, which is much faster.
=> Fix performance issue when using S3 as metadata storage

src/ui/common/src/components/integrations/cards/snowflakeCard.tsx, src/ui/common/src/components/integrations/dialogs/snowflakeDialog.tsx, src/ui/common/src/utils/integrations.ts
This PR fixes a bug where the UI did not allow users to specify a non-default schema. We already have backend support for custom schemas. This change is also backwards compatible, as previous integrations added from the UI will continue to use the default (`public`) schema.
ENG 2419
https://www.loom.com/share/29d975604d9248b2bde216c6b068abe9
=> Allows user to specify optional Snowflake schema in UI

src/python/aqueduct_executor/operators/utils/storage/file.py, src/python/aqueduct_executor/operators/utils/storage/gcs.py, src/python/aqueduct_executor/operators/utils/storage/s3.py, src/python/aqueduct_executor/operators/utils/storage/storage.py, src/python/aqueduct_executor/operators/utils/utils.py
We had a defensive storage.get() call to see if the key exists in storage. Replaced these checks with storage.exists() that takes advantage of faster APIs
Eng-2429
=> Adds a storage.exists() check to replace extra storage.get()

integration_tests/sdk/test-config-example.yml, integration_tests/sdk/test-credentials-example.yml, scripts/mysql_test_setup.sh, scripts/mysql_test_teardown.sh
This PR adds MySQL to our data integration testing suite.
Currently unable to run this on my M1 Macbook, but I suspect that this has something to do with arm specific binaries. Going to try out on ec2 instance and see if this works
ENG-2285
=> ENG-2285 MySQL Integration Testing Setup

src/golang/lib/job/k8s.go, src/golang/lib/job/poll.go, src/golang/lib/storage/s3.go
This PR fixes 2 bugs:
1. S3's “file not exist”’s error wasn’t properly converted to our enum.
2. When scheduling pods, if there’s insufficient resource, we immediately fail. But we shouldn’t because this might be temporary. So we are removing this error checking, and instead returns a pending status. Once the job hits the poll timeout, we will error at that point.
=> Fix bug in S3 GET error handling and k8s pod status handling

src/ui/common/src/components/LogViewer/index.tsx
Add the colors back to the logs :)
ENG 2405
=> ENG 2405 Fix bug where log and stack traces divs don't have backgrounds

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/ReactFlowCanvas.tsx
This PR fixes an issue where the DAG did not take up the full width and height of the details tab on the workflow details page.
ENG-24523
https://www.loom.com/share/35efcf76eb604aad971e52c636d547f5
=> ENG-2453 Dag Width and Height Fixes

src/ui/common/src/components/pages/artifact/id/components/Preview.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx
Correct artifact messaging.
Unable to reproduce other observations: https://linear.app/aqueducthq/issue/ENG-2332#comment-a9e27957
ENG 2332 
Update messaging if input is pending for metric & operator artifacts:
Messaging remains correct in failure case: 
=> ENG 2332 Differentiate warning between pending and upstream failure

src/ui/common/src/components/pages/workflow/id/index.tsx
This PR fixes the small flash that would happen when users refresh the workflow details page.
Apparently ReactFlow and our TabPanel component do not get along so well. Simply adding a conditional check on which tab is active to show Settings or Details did the trick here.
ENG-2457
https://www.loom.com/share/c556e48d888b4a879326f4eea3c15762
=> ENG-2457: Fixes DAG flashing on workflow details page

integration_tests/sdk/aqueduct_tests/param_test.py, sdk/aqueduct/client.py, sdk/aqueduct/utils/type_inference.py
Adds the ability to list and delete parameters in the current working context. See the `test_param_management` test case to see how this would be used.
ENG-2343
=> [2/2] Improve parameter management from Aqueduct client

src/ui/common/src/components/pages/operator/id/index.tsx
Use same padding top on operator page as artifact page for secondary headers.
ENG-2475
https://www.loom.com/share/8edba2152b654e02aabee7ee5f5a6b16
=> ENG-2475: Bug: Better align operator and artifact 'outputs' and 'generated by' headers

src/python/bin/aqueduct
Fixed `aqueduct install mariadb` for Mac M1. Should also work for M2.
ENG 2400
Installation works correctly now.
Before:
Runs: `brew install mysql` (Confirmed by printing the cmd variable)
```
>> aqueduct install mariadb
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
Traceback (most recent call last):
File "/opt/anaconda3/envs/aqdev/bin/aqueduct", line 759, in <module>
install(args.system[0])  # argparse makes this an array so only pass in value [0].
File "/opt/anaconda3/envs/aqdev/bin/aqueduct", line 545, in install
install_mysql()
File "/opt/anaconda3/envs/aqdev/bin/aqueduct", line 491, in install_mysql
execute_command(cmd)
File …
```
=> ENG 2400 Fix aqueduct install mariadb for Mac M1

integration_tests/sdk/aqueduct_tests/param_test.py, sdk/aqueduct/artifacts/create.py, sdk/aqueduct/client.py, sdk/aqueduct/decorator.py
This bug came about because we processed each implicit parameter one at a time, performing validation and then creating the parameter. However, the act of creating the parameter would alter the validation step for the remaining implicit parameters, causing the assertion error described in the task.
The solution is to perform the validation for all implicit parameters at once, and only afterwards to alter the state of the dag.
ENG-2481
https://github.com/aqueducthq/aqueduct/issues/1003
=> Fix bug where rerunning a function with multiple implicit parameters fails

README.md
Removes the old save API on the README that's since been deprecated.
=> Removes deprecated save API from README

manual_qa_tests/README.md, manual_qa_tests/initialize.py, manual_qa_tests/notification.py, sdk/aqueduct/constants/enums.py, sdk/aqueduct/integrations/connect_config.py
This PR adds simple SDK supports to connect to notification integrations. We also add manual QA test over slack channel which can be future taken by release process.
ENG-2272
Confirmed with QA testing in my own slack channel:
```
python3 manual_qa_tests/initialize.py --slack-token <TOKEN> --slack-channel general
```
=> Support notifications in manual QA testing script

src/ui/common/src/utils/docs.ts, src/ui/common/src/utils/integrations.ts
This PR updates notification doc link in UI as we decided to put docs in a different place than original plan.
ENG-2504
Verified the link actually jump to real content
=> Fix notifications doc link in UI

integration_tests/sdk/data_integration_tests/s3_data_validator.py, integration_tests/sdk/data_integration_tests/s3_test.py, src/python/aqueduct_executor/operators/connectors/data/s3_serialization.py
For the inner serialization of a custom pickled dictionary, we use a default format value.
=> Fix bug when serializing a list of tables to S3

src/ui/common/package-lock.json, src/ui/common/package.json, src/ui/common/src/components/pages/AccountPage.tsx, src/ui/common/src/components/pages/check/id/index.tsx, src/ui/common/src/components/workflows/nodes/CheckOperatorNode.tsx, src/ui/common/src/components/workflows/storageSelector.tsx
Bugfix: UI blanks when clicking on a check node in older versions of Safari. UI crashes when viewing workflow settings when user chooses Storage Metadata other than file storage.
The cause of this bug was that the structuredClone function is not supported by older browsers.
ENG-2508
Latest Demo: https://www.loom.com/share/d940355f303d458481b5e01b9557f0a7
https://www.loom.com/share/35d87bc69d8148b1b8f6e2df4ba31020
=> ENG-2508: Safari Bug Fixes

src/Makefile
This is necessary for the release process to copy the migrator binary just as we do for server and executor instead of moving it.
=> Copies migrator binary instead of moving it

src/golang/cmd/server/handler/connect_integration.go, src/golang/lib/workflow/utils/migrate.go
This PR fixes a bug where the migration logic was trying to look for artifact results that had failed and therefore did not exists in storage and then subsequently caused the entire process to be marked as failed. We now have a check to only throw an error during artifact result migration if the status was actually successful.
This PR also adds a bunch of useful debug logs that will be important when debugging in the future.
ENG 2411
=> Fixes bug in the storage migration process with migrating failed artifact results

integration_tests/sdk/aqueduct_tests/naming_test.py, integration_tests/sdk/aqueduct_tests/operator_test.py, sdk/aqueduct/decorator.py
This PR allows users to reuse an operator in a workflow, as long as the input artifacts provided to the operator are different from previous instances of the operator. If a user attempts to add a new operator that collides with an existing operator and it has the exact same input artifacts in the same order, we simply overwrite the original operator.
ENG 2462
=> Allows users to reuse operator in a workflow

scripts/install_local.py, src/golang/cmd/migrator/migrator/register.go, src/golang/cmd/migrator/versions/000024_migrate_exec_env_to_conda_engine/down_postgres.go, src/golang/cmd/migrator/versions/000024_migrate_exec_env_to_conda_engine/main.go, src/golang/cmd/migrator/versions/000024_migrate_exec_env_to_conda_engine/up_postgres.go, src/golang/cmd/migrator/versions/000024_migrate_exec_env_to_conda_engine/up_sqlite.go, src/golang/lib/models/schema_version.go, src/python/bin/aqueduct
This PR adds proper data migration for conda refactor. We added conda engine config for all operators with exec_env_id in older version, since in older version, having this ID implies the op is / was running using conda engine.
ENG-2467
Performed regression test:
* Create wf using older version
* update binary and perform migration
* Run wf using new version
* Verified UI, etc. works properly.
=> [5/5] Properly migrate data for conda refactor

src/python/aqueduct_executor/operators/connectors/data/connector.py, src/python/aqueduct_executor/operators/connectors/data/relational.py, src/python/aqueduct_executor/operators/connectors/data/snowflake.py
This PR fixes a bug that was restricting Snowflake VARCHAR columns to be no larger than 2^16 bytes. Since Snowflake supports columns of size 16MB, we have removed this.
ENG 2538
- Ran a sample workflow against Snowflake where the table had a column with values of size 16MB
- Ran data integration tests against Snowflake for regression testing
=> Allows for Snowflake VARCHAR to be of the max size

.github/workflows/integration-tests.yml, sdk/aqueduct/integrations/connect_config.py, sdk/aqueduct/integrations/sql_integration.py, src/python/aqueduct_executor/operators/connectors/data/config.py, src/python/aqueduct_executor/operators/connectors/data/snowflake.py, src/python/aqueduct_executor/operators/connectors/data/spark/snowflake.py, src/ui/common/src/components/integrations/cards/snowflakeCard.tsx, src/ui/common/src/components/integrations/dialogs/dialog.tsx, src/ui/common/src/components/integrations/dialogs/snowflakeDialog.tsx, src/ui/common/src/utils/integrations.ts
This PR allows users to specify a role when using a Snowflake role. Currently all operations for Snowflake would just assume the default role of the user.
ENG 2490
https://www.loom.com/share/49cdc9aefc9f4800b35b21ffec36d073
=> Allows users to optionally specify snowflake role

src/golang/cmd/server/handler/connect_integration.go
The error message points the user to the installation documentation.
=> Error when AWS integration dependencies aren't installed

sdk/aqueduct/client.py, src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/pages/integrations/index.tsx, src/ui/common/src/utils/integrations.ts
We will re-enable when the project ships. The PR also greys out the disabled service's text field.
@vsreekanti let me know if the integration page looks fine.
=> Disable AWS integration registration from UI and SDK

.github/workflows/mypy.yml
This PR fixes mypy version issue in gh actions that's blocking all PR merges
=> Fix mypy failure in GH actions

.github/actions/setup-server/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/periodic-integration-tests.yml, integration_tests/sdk/aqueduct_tests/resources_test.py, integration_tests/sdk/compute/k8s/main.tf, integration_tests/sdk/compute/k8s/outputs.tf, integration_tests/sdk/compute/k8s/terraform.tf, integration_tests/sdk/compute/k8s/variables.tf, integration_tests/sdk/conftest.py, integration_tests/sdk/run_tests.py, integration_tests/sdk/setup_integration.py, integration_tests/sdk/test-credentials-example.yml, sdk/aqueduct/backend/api_client.py, sdk/aqueduct/integrations/connect_config.py, src/golang/lib/job/config.go, src/golang/lib/lib_utils/utils.go
You can now add a K8s integration to the "compute" section of `test-config.yml`.
Testing: I was able to run flow_test.py against K8s in about 30 minutes (including spinnup and teardown). I need to verify that this works against the full suite. I think I also saw some transient errors that need to be sorted out. 
[UPDATE] Got a full run working: https://github.com/aqueducthq/aqueduct/actions/runs/4326011758/jobs/7552902876
ENG-2346
=> Add K8s integration tests to our periodic integration tests

.github/actions/fetch-test-config/action.yml, integration_tests/sdk/README.md, integration_tests/sdk/setup_integration.py
It's pretty annoying to have to update the apikey in test-credentials.yml anytime you clear the server. We make this field optional. If it's there, we will respect it, but otherwise we will attempt to infer the apikey with `aqueduct apikey`.
ENG-2565
=> Do not require an explicit apikey field in test-credentials.yml

.github/actions/fetch-test-config/action.yml, .github/workflows/periodic-integration-tests.yml, scripts/convert_nb_to_md.py, scripts/get_current_oncall.py, scripts/install_local.py, scripts/run_linters.py
In `aqueduct-assets`, we now expect an `oncall.yml` file that designates our future oncall rotation. When tests in GH actions fail, the appropriate oncall will then be notified. This is done by interpreting this `oncall.yml` file using the new `get_current_oncall.py` script.
This PR also adds the `scripts/` directory to the linter, so there's a bit more spam. 
For reviewers, you only need to look at the new `get_current_oncall.py` and `periodic-integration-tests.yml`
ENG-2564
=> Have our GH actions slack integration always tag the appropriate oncall

integration_tests/sdk/aqueduct_tests/integration_test.py, sdk/aqueduct/backend/response_helpers.py, sdk/aqueduct/constants/enums.py, src/golang/lib/engine/utils.go, src/golang/lib/job/errors.go, src/golang/lib/job/k8s.go, src/golang/lib/job/process.go, src/golang/lib/workflow/operator/base.go
The original bug was when running with k8s, an extract operator that attempts to read from the local sqlite database will silently fail. The root cause is when error occurs in operator.Launch(), we weren't setting the operator's exec state accordingly.
This PR also fixes a few other smaller issues and comment typos.
@kenxu95 let's sync up tmr on writing a k8s integration test for this.
=> Fix bug where error occurred during job manager launch is not caught as operator error

src/golang/cmd/server/handler/configure_storage.go, src/golang/cmd/server/routes/routes.go, src/golang/cmd/server/server/execute_handler.go, src/golang/cmd/server/server/handlers.go, src/golang/lib/workflow/utils/migrate.go
This PR implements a new route `api/config/storage/{integrationID}` which can be used to change the storage layer to an existing integration. Right now there is only support for changing back to the local storage layer using this route.
There is future work to add support for specifying any existing integration (that is compatible for storage, such as S3 or GCS) and setting that as the new storage layer. This is tracked by: https://linear.app/aqueducthq/issue/ENG-2574/add-backend-support-for-changing-the-storage-layer-to-an-existing
ENG 2175
Tested via a Postman route
=> Adds backend support for changing storage layer back to local

integration_tests/sdk/aqueduct_tests/integration_test.py, integration_tests/sdk/conftest.py
=> Fix a test case that's expected to run only when using sqlite as data integration

integration_tests/sdk/aqueduct_tests/lazy_execution_test.py, integration_tests/sdk/aqueduct_tests/preview_test.py, integration_tests/sdk/aqueduct_tests/table_artifact_test.py, integration_tests/sdk/conftest.py, sdk/aqueduct/decorator.py
Fixed by moving the global_config check into the execution path, instead of the decorator instantiation path.
=> Fix bug where calling an operator fixes it's execution mode

src/golang/cmd/migrator/versions/000016_add_artifact_type_column_to_artifact/utils.go, src/golang/cmd/server/handler/get_artifact_result.go, src/golang/cmd/server/handler/get_artifact_versions.go, src/golang/cmd/server/handler/get_workflow_dag_result.go, src/golang/cmd/server/handler/list_workflows.go, src/golang/lib/errors/errors.go, src/golang/lib/errors/errors_test.go, src/golang/lib/storage/file.go, src/golang/lib/storage/gcs.go, src/golang/lib/storage/s3.go, src/golang/lib/storage/storage.go
This PR lays out the ground work for removing all of the `var Err... = errors.New(...)` code pattern in our codebase, as this was preventing us from capturing the right stack trace as part of the `DropboxError`.
This PR defines our own `errors` lib so that we don't need to import several different `errors` packages in the same file. >80% of this library is just calling the dropbox errors library. The only part that is custom is checking for error equality. This has to be custom because we will always have a mix of dropbox errors and standard errors in our codebase. Consider something like `io.ErrNoFile`, which is defined in the standard `io` package. If we want to perform equality correctly for all errors we need to deal with cases where we could be dealing with either a standard error or …
=> Refactors storage error to include stack trace

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/edit_integration.go, src/golang/cmd/server/handler/get_artifact_result.go, src/golang/cmd/server/handler/get_operator_result.go, src/golang/cmd/server/handler/register_workflow.go, src/golang/cmd/server/handler/test_integration.go, src/golang/cmd/server/middleware/authentication/authentication.go, src/golang/cmd/server/server/test_account.go, src/golang/lib/database/database.go, src/golang/lib/database/scanner.go, src/golang/lib/execution_environment/execution_environment.go, src/golang/lib/repos/sqlite/artifact.go, src/golang/lib/repos/sqlite/artifact_result.go, src/golang/lib/repos/sqlite/dag.go, src/golang/lib/repos/sqlite/dag_edge.go, src/golang/lib/repos/sqlite/dag_result.go, src/golang/lib/repos/sqlite/execution_environment.go, src/golang/lib/repos/sqlite/integration.go, src/golang/lib/repos/sqlite/notification.go, src/golang/lib/repos/sqlite/operator.go, src/golang/lib/repos/sqlite/operator_result.go, src/golang/lib/repos/sqlite/schema_version.go, src/golang/lib/repos/sqlite/user.go, src/golang/lib/repos/sqlite/workflow.go
There was another `var error = ...` code pattern that is very high priority to refactor, because it was an error seen frequently. So this PR refactors errors defined in `lib/database` so that we capture the stack trace correctly. This builds on the work done by #1076 
ENG 2600
=> Refactors lib/database to follow new errors convention

src/golang/cmd/server/handler/connect_integration.go, src/ui/common/src/components/integrations/dialogs/athenaDialog.tsx, src/ui/common/src/components/integrations/dialogs/awsDialog.tsx, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx
Hard to write test because the we don't know the path to the credential file on the GitHub action environment, but I tested manually and it works.
Maybe we can still write a test that's only to be run during manual testing? Is there a way to skip this test for all GitHub action runs? @kenxu95 
=> Get our credentials paths working with ~

src/ui/common/src/components/integrations/addIntegrations.tsx
This PR improves the rendering of metadata migration alerts by properly assign width and margin to this component.
ENG-2410
Before:
After:
=> ENG 2410 improve metadata migration notice looking

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx
In the latest release, we regressed the alignment of this button. This PR fixes that.
ENG-2631
*Current version (v0.2.6)*
*Fixed, as of this PR*:
=> [ENG-2631] Fixes bug that caused navigation buttons to be misaligned

src/golang/cmd/server/handler/connect_integration.go, src/golang/cmd/server/handler/delete_workflow.go, src/golang/cmd/server/handler/discover.go, src/golang/cmd/server/handler/list_integration_objects.go, src/golang/cmd/server/handler/preview_table.go, src/golang/lib/airflow/schedule.go
Previously, we had called :
```
defer func() {
// Delete storage files created for list objects job metadata
go workflow_utils.CleanupStorageFiles(ctx, args.StorageConfig, []string{jobMetadataPath, jobResultPath})
}()
```
We shouldn't be using the passed in context (since it will get canceled). This PR switches to using context.Background().
[Eng-2570
](https://linear.app/aqueducthq/issue/ENG-2570/fix-bug-where-the-server-errors-with-context-cancelled-when-previewing)## Loom demo (if any)
Fixed output after previewing a base table on the UI
```
INFO[0023]/home/ubuntu/aqueduct/src/golang/lib/job/process.go:382 github.com/aqueducthq/aqueduct/lib/job.(*ProcessJobManager).Poll() Job extract-operator-bdb37a05-9c88-4d8d-873c-27307b338d86 Stdout:
Running Connector for extract job: …
```
=> Use context.Background() for deferred functions

sdk/aqueduct/integrations/connect_config.py, src/golang/lib/dynamic/engine.go, src/golang/lib/engine/authenticate.go, src/golang/lib/lib_utils/utils.go, src/golang/lib/models/shared/integration_config.go
Previously, when we set the `stream` flag to true, we are only streaming the error message to the server log but not returning the error to the user. This PR make it so that the error log is also captured and returned to the user (instead of just saying "Error waiting for command to complete" which is not useful).
=> Surface error message to the user when setting the `stream` flag to true

sdk/aqueduct/integrations/connect_config.py, src/golang/cmd/server/handler/cloud_integration_utils.go, src/golang/cmd/server/handler/delete_integration.go, src/golang/cmd/server/handler/list_operators_for_integration.go, src/golang/lib/dynamic/engine.go, src/golang/lib/engine/authenticate.go, src/golang/lib/lib_utils/utils.go, src/golang/lib/models/shared/integration_config.go
This PR does the following:
1. Disallow users to delete the implicitly created k8s integration.
2. Allow deleting the cloud integration only when there is no workflow using the dynamic k8s integration.
3. GC the EKS cluster if it's running, and delete the cloud integration directory that contains Terraform files.
4. Also delete the implicitly created dynamic k8s integration when deleting the cloud integration.
=> Make sure deletion of cloud integration is working

manual_qa_tests/workflows/succeed_parameters.py
This PR adds a case to the manual ui tests to check that a parameter with an empty string is able to render properly in a workflow.
As is, the parameter is now rendering on the UI, so I was not able to reproduce this bug. However I did update the test case so that we can be sure to check for this in the future.
ENG-2339
https://www.loom.com/share/4f11dbb49dc74269b5010200b778ac6f
=> ENG-2339 Empty String Parameter Rendering Fix

src/ui/common/src/components/pages/workflow/id/index.tsx
This PR fixes a bug where the internal state management of the workflow details page wasn't correctly being kept in sync with the Redux store. As a result, the next/previous navigation buttons were broken. 
This PR also fixes a bug where a workflow without an error wouldn't render properly because we didn't have undefined guards (introduced in #1107, I think?). 
ENG-2645
=> [ENG-2645] Fixes bug where next run button was broken on the UI

manual_qa_tests/initialize.py, manual_qa_tests/workflows/check_status_test.py, manual_qa_tests/workflows/succeed_parameters.py, src/ui/common/src/components/pages/workflows/components/CheckItem.tsx
This PR fixes an issue where failed checks with level of warning showed as error icons on workflow metadata page. Also includes a manual QA integration tests to check that this functionality is working in the future.
ENG-2577
https://www.loom.com/share/d4aab8cdf1c24ceab6e821304638bf94
=> ENG-2577 Fix bug where warning state is not properly reflected on metadata list views

src/golang/.golangci.yml, src/golang/lib/engine/aq_engine.go, src/golang/lib/engine/utils.go, src/golang/lib/errors/errors.go, src/golang/lib/errors/errors_test.go, src/golang/lib/execution_environment/execution_environment.go
https://github.com/aqueducthq/aqueduct/pull/1107 introduced a bug where all errors, includes those that happen within an operator's context, were surfaced as workflow-level, which meant that every failing workflow got a banner.
This PR does the following:
1) Fixes the immediate error, so that workflow-level errors only occur when the workflow doesn't have an op failure exception.
2) In the process of fixing the above bug, I noticed that our error comparison method was only comparing the top-level errors. I think for our error comparisons, we should be completely unwrapping our candidate error and matching it against the target error. It doesn't make sense to compare just agains the outermost layer since it's much harder to control how much an error is wrapped as it works it way out of our …
=> Fix bug where all errors were surfaced as workflow-level errors

src/golang/cmd/server/handler/get_node_positions.go, src/ui/common/src/reducers/workflow.ts, src/ui/common/src/utils/reactflow.ts
This PR removes elk and brings back the old positioning algorithm.
Edge crossings should be much less likely, however they might seem a little long when there is a collapsed DAG node.
ENG-2620
Screehshots:
=> ENG-2620 DAG Line Crossing Fix

src/ui/common/src/components/pages/workflows/index.tsx
This PR show a workflow's status badge in workflow list page as warning status if there is a warning level check that fails in the workflow.
ENG-2577
See warning_bad_check workflow below:
=> ENG-2577 follow up

.github/workflows/periodic-integration-tests.yml
Fixed a bug in the usage of the nick-fields/retry. 
Validated that the full terraform folder allows us to destroy the resources locally. However, the folder is 404MB which is quite large, so I also changed it to only run on failures.
=> Update automated terraform destroy

src/ui/common/src/components/workflows/artifact/metric/history.tsx
This PR uses date values in the Metrics history graph when plotting values on the x axis.
The end result here is that the values will be spread out according to how close in time they are.
Pretty short PR here :) had to give myself a crash course in plotly first before grokking what's going on.
ENG-2622
Screenshot with a metric from the future :)
On the left side, you'll notice a clump of values which is a result of me kicking off several workflows within minutes of eachother.
On the right, I added a value one day in the future.
=> ENG-2622 Show metrics history graph temporally on the x axis.

src/golang/lib/engine/aq_engine.go, src/golang/lib/job/process.go, src/golang/lib/workflow/utils/database.go
Currently, node statuses are not updated to cancel when the workflow fails in the Golang level.
When updating the workflow run status, this fix checks to see if the workflow run is in the complete state (succeeded/canceled/failed) and marks all pending or running nodes as canceled.
ENG 2441
Before - workflow done but nodes marked pending
After - all nodes marked as cancelled after workflow run gets a final status (succeeded or failed)
=> Eng 2441 Update node statuses to cancel when workflow run is finished

integration_tests/sdk/aqueduct_tests/delete_workflow_test.py, integration_tests/sdk/data_integration_tests/relational_test.py, integration_tests/sdk/setup_integration.py, integration_tests/sdk/shared/relational.py
This PR fixes all of the references to SQL table names so it works for BigQuery as well, since BigQuery requires table names to be of the format `dataset.table`.
**REVIEWERS: Look at just `integration_tests/sdk`**. I can't fix this rebase until #1134 is rebased off of main.
ENG 2387
=> Adds support for bigquery integration tests

integration_tests/sdk/aqueduct_tests/table_artifact_test.py, sdk/aqueduct/artifacts/create.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/artifacts/system_metric.py, sdk/aqueduct/artifacts/table_artifact.py, sdk/aqueduct/client.py
Adds the `system_metric` capability to GenericArtifacts. Creates a mixin SystemMetricMixin that both GenericArtifact and TableArtifact use.
[Eng-2436](eng-2436-fix-regression-in-system-metrics)
=> Add system_metric function to GenericArtifact

src/ui/common/src/components/pages/workflow/id/index.tsx, src/ui/common/src/components/workflows/version_selector.tsx, src/ui/common/src/components/workflows/workflowHeader.tsx
Previously, we were hardcoding the workflow status to show an indicator for the execution status of the most recent workflow run. That had two issues: 
1. When you switched workflow runs, it would not update accordingly.
2. If you hit the refresh button on the UI, the status would not change.
1 was fixable simply by updating the index of the status check to match the selected run, but 2 was a tougher challenge because we would have to load the whole workflow state again, which would cause the whole page to go white and then re-render.
#1108 introduced the workflow history store which enabled us to fix this problem more simply. Now, the workflow header reads the status from the workflow history rather than from the workflow reducers `dagResults` list. The refresh button can simply refresh …
=> [ENG-2621] Fix bug where status in workflow header is not correctly updated

src/golang/lib/k8s/clients.go
This *should* fix at least the flaky `test_all_param_types` tests.
ENG-2729
=> [K8s] Handle case where multiple tests race to create the aqueduct namespace 

.github/workflows/periodic-integration-tests.yml, src/golang/cmd/server/handler/connect_integration.go
This is a small tweak to make sure we aren't uploading 0.5 GBs of artifact data on every periodic failure - only when the cluster cleanup fails, since the point of uploading this artifact is to finish cluster deletion in such cases.
=> Only upload terraform directory when the K8s cleanup fails

integration_tests/sdk/aqueduct_tests/checks_test.py, sdk/aqueduct/backend/api_client.py
Check for data in failed workflow execution response payload. If there is valid data, it is deserialized and returned as artifact result. This is helpful for boolean operator that returns True or False
ENG-2629
=> Check for data in response payload for failed execution

src/ui/common/src/components/workflows/nodes/Node.tsx
This PR fixes misaligned metrics / checks icons in UI when they have long names. The cause being an additional flex box that wraps the texts, and as a result the text width is extended
=> Fix misaligned metrics / checks when they have long names

src/ui/common/src/components/operators/WithOperatorHeader.tsx
This PR fixes a bug where we attemp to render integration and save details on all operators. This causes unexpected space in sidesheet when the information is missing.
save page (should be the same as current main)
metrics page
check page
also verified on regular operators and op / artf details page (instead of sidesheet)
=> Fix a bug where sidesheet is showing unexpected spaces

src/ui/common/src/components/workflows/artifact/check/history.tsx
This PR fixes an issue where check history list items are incorrectly rendered for warning checks that fail.
Now they should show up with the warning logo and warning background color.
ENG-2753
https://www.loom.com/share/461760bd7c344397b04fe34e3615e69f
=> ENG-2753: Fix issue where warning level checks show as failed in history list.

sdk/aqueduct/artifacts/numeric_artifact.py, sdk/aqueduct/schedule.py
Fixes bugs discovered via running through the code snippets in Gitbook (https://github.com/aqueducthq/aqueduct/pull/1172):
- The monthly function instance type check incorrect for day (`DayOfWeek` --> `DayOfMonth`).
- Fix `DayOfMonth` exception statement from "Invalid *hour* value" to "Invalid *day* value".
- Fix assertion for bounds to work when `bound_value` is falsey (e.g. 0).
ENG-2757
- `skip_integration_test`: Skips …
=> ENG-2757 Fix SDK function arg validation failures

src/ui/common/src/components/operators/WithOperatorHeader.tsx, src/ui/common/src/components/pages/metric/id/index.tsx
This PR brings back the Logs component that was missing on the metrics details page so that we can now show errors / sddout/err logs on Metric operators once again.
ENG-2761
https://www.loom.com/share/acdb6c3d58c141caa9abcf4b8063bca2
=> ENG-2761 Fix issue where errors were not being shown in Metric details pages

src/dockerfiles/spark/spark-py310-env.dockerfile, src/dockerfiles/spark/spark-py37-env.dockerfile, src/dockerfiles/spark/spark-py38-env.dockerfile, src/dockerfiles/spark/spark-py39-env.dockerfile
Corrects the version of aqueduct-ml in spark containers. With the changes https://github.com/aqueducthq/release/pull/8, this issue is fixed moving forwards.
Eng 2762
=> Eng 2762 add aqueduct ml version to spark docker

integration_tests/sdk/aqueduct_tests/checks_test.py, integration_tests/sdk/aqueduct_tests/error_handling_test.py, integration_tests/sdk/aqueduct_tests/external_compute_test.py, integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/aqueduct_tests/lazy_execution_test.py, integration_tests/sdk/aqueduct_tests/local_test.py, integration_tests/sdk/aqueduct_tests/metrics_test.py, integration_tests/sdk/aqueduct_tests/multiple_output_test.py, integration_tests/sdk/aqueduct_tests/naming_test.py, integration_tests/sdk/aqueduct_tests/no_input_test.py, integration_tests/sdk/aqueduct_tests/operator_test.py, integration_tests/sdk/aqueduct_tests/param_test.py, integration_tests/sdk/aqueduct_tests/preview_test.py, integration_tests/sdk/aqueduct_tests/table_artifact_test.py, integration_tests/sdk/aqueduct_tests/test_functions/simple/file_dependency_model.py, integration_tests/sdk/aqueduct_tests/test_functions/simple/model.py, integration_tests/sdk/conftest.py, scripts/data/redshift_test.py, src/golang/lib/job/spark.go
Modifies tests to work with Spark. Most of the changes involve adding a case in the test functions to use Pyspark Dataframe specific code. I also add the `pytest.mark.skip_for_spark_engines() `fixture to skip tests that don't work with Spark.
=> Get sdk integration tests working with Spark

integration_tests/sdk/README.md, integration_tests/sdk/run_tests.py, sdk/aqueduct/client.py
It's pretty annoying that there are only a subset of the pytest flags implemented in run_tests.py. It would be much better just to pass any flags down to the pytest command, and have run_tests.py be a kind of convenience helper.
ENG-2766
=> Allow more flexibility in the run_tests.py script

src/golang/lib/databricks/jobs.go, src/golang/lib/job/config.go, src/golang/lib/job/databricks.go, src/golang/lib/models/shared/integration_config.go, src/ui/common/src/components/integrations/dialogs/databricksDialog.tsx, src/ui/common/src/utils/integrations.ts
Adds option for users to specify a Databricks instance pool. All JobClusters that Aqueduct creates will create clusters using instances from this pool. If not specified, we default to a node type and request spot instances from AWS.
Eng-2765
https://www.loom.com/share/a12b0ca34fc04ad495b39b69422e72ec
=> Adds instance pool option to Databricks integration

.github/actions/setup-server/action.yml, integration_tests/sdk/aqueduct_tests/param_test.py, sdk/aqueduct/utils/serialization.py, src/dockerfiles/param/param.dockerfile
This PR contains two changes regarding local tensorflow data parameter test:
1. Latest Tensorflow does not support Python 3.7. With older tensorflow, it does not have package module `keras.saving.load_model`. Therefore, we change the loading method to `keras.models.load_model` which presents in both new and older version of tensorflow.
2. Local tensorflow model parameter tests fail with our Periodic Integration test. The reason is that we didn't have tensorflow as a part of param docker image. I added the image with latest version of tensorflow and mark the failed test inactive to k8s which should be reverted next release. 
=> Fix creating local tensorflow model data fails with module import and tensorflow versioning

.github/actions/fetch-test-config/action.yml
This PR fetches the BigQuery shared credentials to a location from which it can be used for data integration tests.
ENG 2696
=> Adds support for running BigQuery tests periodically

src/ui/common/src/components/AnnouncementBanner/AnnouncementBanner.tsx
This PR sends a GET request to PyPI to check if there is a newer version of aqueduct than the version currently installed. If a new version is available we now show announcement banner.
ENG-2804
https://www.loom.com/share/216e9952b6de4d5f84e691fec26e5606
=> ENG-2804 Check PyPI to determine whether to show Announcement Banner

sdk/aqueduct/decorator.py, sdk/aqueduct/models/dag_rules.py, sdk/aqueduct/models/operators.py
Adds cuda_version to the ResourceConfig for the Operator Class.
Eng-2808
=> Fix bug with CUDA versioning on GPUs

src/ui/common/src/components/integrations/dialogs/bigqueryDialog.tsx, src/ui/common/src/components/integrations/dialogs/databricksDialog.tsx, src/ui/common/src/components/integrations/dialogs/gcsDialog.tsx, src/ui/common/src/components/integrations/dialogs/kubernetesDialog.tsx, src/ui/common/src/components/integrations/dialogs/lambdaDialog.tsx, src/ui/common/src/components/integrations/dialogs/mariadbDialog.tsx, src/ui/common/src/components/integrations/dialogs/mongoDbDialog.tsx, src/ui/common/src/components/integrations/dialogs/mysqlDialog.tsx, src/ui/common/src/components/integrations/dialogs/postgresDialog.tsx, src/ui/common/src/components/integrations/dialogs/redshiftDialog.tsx, src/ui/common/src/components/integrations/dialogs/slackDialog.tsx, src/ui/common/src/components/integrations/dialogs/snowflakeDialog.tsx, src/ui/common/src/components/integrations/dialogs/sparkDialog.tsx, src/ui/common/src/components/integrations/dialogs/sqliteDialog.tsx
This PR resolves error messages that appeared in integrations dialogs related to passing in null when the input's state was empty.
To resolve this, we use empty strings for empty input values. This change impacts some of the validation functions in our integrations, which will be resolved in another PR.
ENG-2805
https://linear.app/aqueducthq/issue/ENG-2805/fix-console-errors-on-existing-integrations-dialogs
=> [1/2]: ENG-2805: Integration Form Empty State Console Error Fixes

src/golang/cmd/server/handler/v2/dag_results_get.go, src/golang/cmd/server/routes/routes.go, src/golang/cmd/server/server/handlers.go, src/ui/common/src/handlers/AqueductApi.ts, src/ui/common/src/handlers/v2/DagResultsGet.ts
This PR adds `wf/<id>/results` that retrieves all results for a given workflow
ENG-2793
Go compiles. UI didn't crash with a full build
=> Adds v2 route to retrieve workflow historical results

.github/workflows/periodic-integration-tests.yml
Reduces concurrency of K8s tests to 1 for stability reasons. Sets the timeout to 180 min to account for test time. Created a [task](https://linear.app/aqueducthq/issue/ENG-2815/investigate-why-k8s-tests-fail-with-increased-concurrency) to track the investigation of the test failures with higher concurrency.
Eng-2811
https://github.com/aqueducthq/aqueduct/actions/runs/4726107721 Run of the periodic tests.
=> Reduce concurrency of k8s tests to 1

.github/workflows/periodic-integration-tests.yml, integration_tests/sdk/setup_integration.py
Adds automated periodic testing coverage for MariaDB.
TODO: Once merged, update the `periodic-data-integration-test-config.yml` file and delete `periodic-data-integration-test-config-eunice-chan.yml`.
ENG 2635
Successfully ran: https://github.com/aqueducthq/aqueduct/actions/runs/4734950881/jobs/8404563971
=> Eng 2635 Add automated periodic testing coverage for MariaDB

src/ui/common/src/components/integrations/cards/databricksCard.tsx, src/ui/common/src/components/integrations/dialogs/databricksDialog.tsx, src/ui/common/src/components/integrations/dialogs/lambdaDialog.tsx, src/ui/common/src/components/integrations/dialogs/sparkDialog.tsx
Improved the placeholder values for the Spark, Databricks, and Lambda integrations.
https://linear.app/aqueducthq/issue/ENG-2837/improve-the-placeholder-values-for-integration-connections
=> Improve placeholder values for integrations

regression_tests/tests/gitbook/test_docs.py
This PR attempts to ignore snippets that use local data parameter. The reason is that we don't have local data file in gitbook to feed into the create_params.
To ignore the specific code snippet, the current implementation is to match the exact snippet such as below:
'from aqueduct.constants.enums import ArtifactType\nlocal_data = client.create_param(\n                    name ="table_data", \n                    default="path/to/data.csv",\n                    use_local=True,\n                    as_type=ArtifactType.TABLE,\n                    format="csv",\n                    ) ', 'client.publish_flow(\n                    name = "local_data_workflow",\n                    artifacts = [local_data, ...],\n                    use_local = True,\n                    ) '
This might be a …
=> Fix documentation bug for missing local file

src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/layouts/menuSidebar.styles.tsx
This PR fixes broken sidebar styling around Aqueduct logo and box sizing issue with AddIntegration list items.
ENG-2862
Screenshot:
=> ENG-2862, ENG-2863 Fix broken sidebar styling and add integration list item box styling.

src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/integrations/logo.tsx
This PR updates the styling for integration cards according to the new figma mocks. 
ENG-2863
Screenshot:
=> ENG-2863 New add integrations styling

src/golang/lib/engine/aq_engine.go, src/golang/lib/workflow/artifact/artifact.go, src/golang/lib/workflow/utils/storage.go
This PR improves logging when a operator failed without generating artifact metadata. The current situation being:
* operator failed without generating artifact metadata
* we attempt to upload artifact metadata
* we failed to read that metadata and thus result in showing a missing storage object failure in most error logs
As the improvements, we modifies the logging with minimum change on current life-cycle management behavior:
* If artif metadata is failed to read, we will log the error rather than fail the function call. We expect orchestration to handle downstream execution based on operator's state.
* when reading the metadata, we assume empty metadata path + metadata field implies empty metadata, rather than an error state.
* In orchestrator, we log operator's failure reason together …
=> Improve logging when operator failed before generating artifact

integration_tests/sdk/conftest.py, integration_tests/sdk/shared/compute.py, integration_tests/sdk/shared/flow_helpers.py, scripts/compute/airflow_test_setup.sh, sdk/aqueduct/integrations/connect_config.py
This PR adds initial support for running integration tests against Airflow. It has a setup script for starting a local Airflow instance. It also adds logic for manually copying the Airflow DAG file to the appropriate folder.
There is still follow on work that needs to be done before these tests can be run on Github actions:
- Fix syncing bugs https://linear.app/aqueducthq/issue/ENG-2794/fix-bug-where-airflow-dags-created-by-integration-test-are-not-syncing
- Configure running these tests on github actions https://linear.app/aqueducthq/issue/ENG-2796/configure-airflow-tests-to-run-on-github-actions
ENG 2116
Ran the basic flow_test locally and uncovered the syncing bug.
- `skip_integration_test`: Skips integration tests (Should be used when …
=> Adds support for running integration tests against Airflow

.github/workflows/periodic-integration-tests.yml, scripts/data/redshift_test.py
This PR adds some extra checking to make sure the Redshift cluster is in the correct state when resuming and pausing it before/after the data integration tests.
See example github action here as a test: https://github.com/aqueducthq/aqueduct/actions/runs/4825449922/jobs/8596314618
ENG 2776
=> Adds status checks for integration test Redshift cluster

.github/workflows/integration-tests.yml, .github/workflows/lint-golang.yml, .github/workflows/mypy.yml, .github/workflows/periodic-integration-tests.yml, .github/workflows/regression-tests.yml, .github/workflows/run-notebooks.yml, .github/workflows/skipped-integration-tests.yml
This PR increases server setup timeouts from 5 min to 7 min. Based on recent integration test failures, the current setup time appear to start reaching the boundary.
```
Installing collected packages: tomli, regex, pluggy, joblib, iniconfig, execnet, exceptiongroup, pytest, nltk, pytest-xdist
Successfully installed exceptiongroup-1.1.1 execnet-1.9.0 iniconfig-2.0.0 joblib-1.2.0 nltk-3.8.1 pluggy-1.0.0 pytest-7.3.1 pytest-xdist-3.2.1 regex-2023.3.23 tomli-2.0.1
Notice:  A new release of pip is available: 22.0.4 -> 23.1.2
Notice:  To update, run: pip install --upgrade pip
Error: The action has timed out.
```
=> Increase server setup timeouts in integration tests

src/golang/cmd/server/handler/connect_integration.go
Improves the error message that users will see so it is not some vague message that is simply forwarded along from Airflow. Instead, we wrap some context that the credentials are probably incorrect.
ENG 2894
=> Improves error message returned to user when Airflow creds are incorrect

src/ui/common/src/components/integrations/dialogs/dialog.tsx
=> Fix leftover integration renaming on the UI

integration_tests/sdk/setup_integration.py
Adds guardrails for checks on config
https://linear.app/aqueducthq/issue/ENG-2942/fix-global-lazy-setting-for-periodic-test
Periodic tests run here: https://github.com/aqueducthq/aqueduct/actions/runs/4919283902
=> Adds guardrails for checks on config

.github/workflows/periodic-integration-tests.yml
Based on a few instances this past week of seeing timeouts for the conda tests after >95% of the test cases have finished successfully, this PR increases the timeout from 40 to 50 min.
ENG 2945
=> Bumps up timeout for conda integration tests

.github/workflows/periodic-integration-tests.yml, scripts/data/redshift_test.py
Sometimes we are seeing transient issues where the Redshift cluster start process times out. This PR bumps the overall start and stop timeout from 20 to 25 min each, and for each state change (i.e. waiting from resuming to ready) the timeout has been modified from 10 to 15 min.
ENG 2920
=> Increases timeout for Redshift integration test cluster start and stop

src/python/aqueduct_executor/operators/connectors/data/s3.py, src/python/aqueduct_executor/operators/connectors/data/s3_serialization.py
Create user supplied root directory (path) on s3 storage bucket if one does not exist. This object path is used for storing Aqueduct workflow artifacts.
ENG-1269
- [ x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x ] I have run the integration tests locally and they are passing.
- [x ] All features on the UI continue to work correctly.
=> Create user supplied root directory on s3 bucket if it does not exist

sdk/aqueduct/resources/validation.py
Simple bug fix that shows the docstring for even those methods using the @validate_is_connected() decorator.
ENG-2886
=> Fix generated docstrings when viewing resource methods in Jupyter

src/python/aqueduct_executor/operators/connectors/data/bigquery.py
This PR adds error checking to the BigQuery executor to see if the dataset exists before trying to save an artifact to it.
ENG 2947
=> Adds error checking for whether big query dataset exists

sdk/aqueduct/utils/serialization.py
There are known problems with `cloudpickle` for Python 3.7. This was causing issues with our `PICKLEABLE` artifact type. 
ENG 2815
Ran the full integration test suite for Python [3.7](https://github.com/aqueducthq/aqueduct/actions/runs/4994381162/jobs/8944891978) and [3.10](https://github.com/aqueducthq/aqueduct/actions/runs/4994381162/jobs/8944891978). (They are in progress.) 
=> Fixes cloudpickle serialization for Python 3.7

src/ui/common/src/components/integrations/dialogs/bigqueryDialog.tsx, src/ui/common/src/components/integrations/dialogs/gcsDialog.tsx, src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx
This PR fixes an issue where the GCS and BigQuery dialogs were crashing after a file upload.
ENG-2979
=> ENG-2979: Fixes bigquery and gcs dialogs that were crashing after file uploads.

src/ui/common/src/components/pages/workflows/components/ResourceItem.tsx, src/ui/common/src/stories/ResourceLogoStory.stories.tsx, src/ui/common/src/utils/integrations.ts
This has been bothering me for a while. Our logos have been uploaded in a very adhoc fashion, so the sizing is significantly off sometimes.
This PR:
1) Fixes a storybook bug with circular imports.
2) Adds a story that puts all our resource logos side by side, with padding=1 so we can easily visualize the logos side by side.
3) Uses the Spark-only logo instead of the wordy one.
I have the uploaded logo png files on my local filesystem. Once I merge this in, I'll update the public assets bucket with the updated ones on the next release.
This is what things used to look like:
The Redshift, S3, Lambda, MariaDB, and MySQL logos were sized way too small. After adjusting, we get the following (MySQL and MariaDB still seem a little small, but that's just what their logos look like)
I realize …
=> Make resource logo sizing more consistent

integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/data_integration_tests/s3_test.py, integration_tests/sdk/shared/flow_helpers.py, sdk/aqueduct/client.py, sdk/aqueduct/tests/flow_test.py, sdk/aqueduct/utils/utils.py
The Flow API had 2 distinct arguments for UUID and Name. This PR merges both of them to one argument as 
a Union[uuid, str]
ENG-2760
- [ x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x ] I have run the integration tests locally and they are passing.
- [x ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
=> Merge id and name arguments to one field

src/golang/cmd/server/handler/v2/get_server_environment.go, src/golang/cmd/server/routes/routes.go, src/golang/cmd/server/server/handlers.go, src/ui/common/src/components/integrations/dialogs/kubernetesDialog.tsx, src/ui/common/src/components/integrations/dialogs/onDemandKubernetesDialog.tsx, src/ui/common/src/components/layouts/menuSidebar.tsx, src/ui/common/src/handlers/AqueductApi.ts, src/ui/common/src/handlers/v2/EnvironmentGet.ts
This PR moves the getEnvironment API call from the kubernetes dialog and the menusidebar to use RTKQuery. 
Also moves the getEnvironment route to the new v2 routes.
ENG-2964
=> ENG-2964 GetEnvironment RTKQuery

.github/workflows/airflow-periodic-tests.yml, .github/workflows/periodic-integration-tests.yml
This PR adds a github action for running the Airflow compute tests once a week. 
See https://github.com/aqueducthq/aqueduct/actions/runs/5043163833/jobs/9044608060 for an example run. Ignore the failures for now. These will all be filed as linear tasks that are beyond the scope of this task.
ENG 2599
=> Adds Github Action for Airflow compute test

src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx, src/ui/common/src/handlers/AqueductApi.ts
This PR fixes an issue where the S3 Dialog was not sending down the proper type for use_as_metadata.
ENG-3010
=> ENG-3010: S3 Dialog Use as Metadata Checkbox fix

src/ui/common/src/components/integrations/dialogs/kubernetesDialog.tsx, src/ui/common/src/components/integrations/dialogs/onDemandKubernetesDialog.tsx
This PR fixes infinite rendering issues with the Kubernetes dialog and OnDemandKubernetes dialogs.
ENG-3011
https://linear.app/aqueducthq/issue/ENG-3011/confusing-dialog-behavior-when-connecting-to-integrations
ENG-3012
https://linear.app/aqueducthq/issue/ENG-3012/k8s-dialog-calling-environments-endpoints-in-infinite-loop
=> ENG-3011 and ENG-3012 Kubernetes/OnDemandKubernetes Dialog Fixes

integration_tests/sdk/aqueduct_tests/flow_test.py
Annotate a test case to restrict it for relational data integration only
ENG-3017
- [ x] I have run the integration tests locally and they are passing.
- [x ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x ] All features on the UI continue to work correctly.
=> Add annotation to gate a test case only for relational data integration

.gitignore
It would be nice to be able to keep multiple versions of `test-config.yml` in `integration_tests/sdk` to easily switch between them (eg. periodic-conda-test-config.yml)
=> Add wildcard prefix to test-config file in gitignore

sdk/aqueduct/tests/flow_test.py, sdk/aqueduct/utils/utils.py
Map flow name to uuid before before fetching from backend instead of using name.
ENG-3019
- [ X] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [ X] I have performed a self-review of my code.
- [X ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ X] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [X ] All features on the UI continue to work correctly.
=> Fix regression of fetching flow by name

src/python/aqueduct_executor/operators/connectors/data/bigquery.py, src/python/aqueduct_executor/operators/connectors/data/execute.py, src/python/bin/aqueduct
Description here: https://linear.app/aqueducthq/issue/ENG-3026/aqueduct-install-bigquery-is-not-sufficient-for-bigquery-extracts-to
What the PR does:
- Better (or at least more consistent) error message if it doesn't exist:
- Also adds `db-dtypes` to the `aqueduct install bigquery` command.
ENG-3026
=> Fix bug where bigquery extracts fail due to missing import

src/ui/common/src/components/integrations/addIntegrations.tsx, src/ui/common/src/components/integrations/connectedIntegrations.tsx, src/ui/common/src/components/pages/account/MetadataStorageInfo.tsx
I'm actually not sure if these are actually improvements anymore, but wanted to send it out just in case any of these appealed to you guys.
On the DAG view, for operators, I removed the padding so that there wasn't as large of a gap between the header icon the text.
On the resources/ page, I made everything justified with the left side since it looked a little funny, but I'm not sure it looks any better.
OLD:
NEW:
------------------------------------------------------------------------------------------
OLD:
NEW:
=> Adjust padding around icons in resources/ and dag view

src/ui/common/src/components/pages/data/index.tsx
This PR fixes data page crash by adding proper changes that should have been introduced in #1345
ENG-3041
* Verified data page is working
* Verified workflow list page does not have any regressions
=> Fix data page loading

src/ui/common/src/components/integrations/dialogs/s3Dialog.tsx
This PR fixes an issue where users were not able to register S3 integrations using the S3 dialog since there was not a default value set.
ENG-3039
=> Eng 3039 UI bug when registering a s3 resource

src/ui/common/src/components/integrations/dialogs/emailDialog.tsx, src/ui/common/src/components/integrations/dialogs/mariadbDialog.tsx
This PR makes it so strings are used for port field in the email dialog and mariadb dialog.
ENG-3028
=> ENG-3028: Use string to validate port for email dialog and maria db dialog

src/ui/common/src/components/integrations/dialogs/bigqueryDialog.tsx, src/ui/common/src/components/integrations/dialogs/gcsDialog.tsx
This PR fixes a broken documentation link in the GCS dialog.
ENG-3030
=> ENG-3030: fix broken GCS documentation link in GCS dialog

sdk/aqueduct/backend/api_client.py, sdk/aqueduct/models/config.py, sdk/aqueduct/utils/utils.py
In the SDK, when we assemble the engine config, we are using a field called resource_id , but when it reaches the backend, we are trying to parse json tag integration_id , which caused the zero UUID issue.
- [] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
=> Fix k8s bug introduced by resource renaming

sdk/aqueduct/backend/api_client.py, sdk/aqueduct/models/config.py, sdk/aqueduct/utils/utils.py
=> Fix broken engine_configs due to integration/resource naming inconsistency

sdk/aqueduct/utils/utils.py, src/golang/lib/workflow/dag/workflow_dag.go, src/ui/common/src/components/pages/workflow/id/hook.ts
This PR updates all user-facing workflow links after UI refactor. There are only two places we produce such links (in notifications and in sdk) and we changed the way we refer to results from `?workflowDagResultId=<value>` to `result/<value>`.
ENG-3063
Verified SDK, notification, and workflow breadcrumbs that they all points to the proper result / dag, for workflow with / without runs.
=> Update workflow links after UI refactor

CHANGELOG.md, src/ui/common/src/components/resources/dialogs/dialog.tsx, src/ui/common/src/components/resources/dialogs/garDialog.tsx
This PR fixes an issue where integrations are able to be registered without a name field present on the UI.
ENG-3027
Before:
After fix:
=> ENG-3027: Require Integration Name

src/ui/common/src/components/resources/dialogs/gcsDialog.tsx
Default GCS for being used as metadata storage. https://github.com/aqueducthq/aqueduct/pull/1380/files#diff-c1f12a54b37e8b729377f7edfa3df5d38166dbc6bd9398b1555858776e420817 wrongly changed this default value to try to make it consistent with S3.
ENG-3050
* Confirmed on dialog box.
* Confirmed `use_as_storage` is true in server logs.
=> Fix default GCS store metadata value

src/ui/common/src/components/resources/cards/card.tsx, src/ui/common/src/components/resources/cards/headerDetailsCard.tsx, src/ui/common/src/utils/resources.ts
This PR fixed the issue where we are showing aws icon rather than k8s. This is introduced in #1380
Verified the icon is correct and the add resource dialog still showing AWS:
=> Fix ondemand k8s showing aws icon rather than k8s

scripts/generate_docs.sh
This PR finishes some left over renames for integration - resource renaming.
https://github.com/aqueducthq/gitbook/pull/112
=> Fix integration - resource rename for doc gen

examples/system-tests/Simple_Model_Large_Data.ipynb
This notebook takes a set of data (currently "LARGE_HOTEL_REVIEWS") and generates rows of data based on the parameter provided.
Ran this with a ~400GiB sized dataset and it ran in about 40 minutes including cluster spin up time. Most of this time is reading/writing the data to the views of the SparkSession and spin up/teardown of executors. This is expected behavior, but will try and understand more deeply what is happening under the hood.
=> Added notebook for running Simple Model with large data

src/ui/app/package.json, src/ui/common/package-lock.json, src/ui/common/package.json
This PR fixes a warning in the ui/app build related to a mismatch in the version of the "buffer package"
Warning: 
```
@parcel/resolver-default: Could not find module "buffer" satisfying ^5.5.0.
/home/runner/work/aqueduct/aqueduct/src/ui/app/package.json:48:5
47 |     "@typescript-eslint/parser": "5.59.5",
> 48 |     "buffer": "6.0.3",
>    |     ^^^^^^^^ Found this conflicting local requirement.
49 |     "eslint": "8.40.0",
50 |     "eslint-config-prettier": "8.8.0",
```
ENg-3095
https://www.loom.com/share/5bdb49ac937c4f8ab641759ef18be6c7
=> ENG-3095: Fixes console warning related to @parcel-resolver/buffer

.github/workflows/mypy.yml, integration_tests/sdk/aqueduct_tests/flow_test.py, integration_tests/sdk/shared/flow_helpers.py, sdk/aqueduct/artifacts/base_artifact.py, sdk/aqueduct/artifacts/bool_artifact.py, sdk/aqueduct/artifacts/generic_artifact.py, sdk/aqueduct/artifacts/numeric_artifact.py, sdk/aqueduct/artifacts/table_artifact.py, sdk/aqueduct/backend/api_client.py, sdk/aqueduct/flow_run.py, sdk/requirements/python-3-10.txt, sdk/requirements/python-3-7.txt, sdk/requirements/python-3-8.txt, sdk/requirements/python-3-9.txt, src/ui/common/src/components/pages/artifact/id/components/Preview.tsx, src/ui/common/src/components/pages/artifact/id/index.tsx, src/ui/common/src/components/pages/workflows/index.tsx, src/ui/common/src/components/tables/CheckTableItem.tsx, src/ui/common/src/components/tables/OperatorExecStateTable.tsx, src/ui/common/src/components/workflows/artifact/content.tsx, src/ui/common/src/components/workflows/artifact/metricsAndChecksOverview.tsx, src/ui/common/src/components/workflows/nodes/Node.tsx, src/ui/common/src/components/workflows/workflowStatus.tsx, src/ui/common/src/utils/shared.ts
This PR adds necessary changes to render artifacts who has snapshots disabled. Note that we show the results that get disabled but not implying that future workflow run will have the snapshot disabled.
We also added some small fix so that we show check status that aligns with op results rather than artf results
ENG-3000
Verified in manual QA that no regressions to relevant features:
https://www.loom.com/share/12a3015af65b47e6b2511c17aeab1c6b
Verified on the manual QA with disabled API calls:
=> [4/n] Add UI changes to render deleted artifacts
